# HungerHub Analytics - End-to-End Oracle Analysis

##  Project Overview
This notebook demonstrates a complete **Oracle → Python → Graphics** workflow for HungerHub food distribution analytics.

### Complete Workflow:
1. ** Oracle Database Connection**: Direct connection to Choice & AgencyExpress databases
2. ** Data Extraction**: SQL queries to extract raw data from Oracle tables
3. ** ETL Pipeline**: Transform and standardize data, store locally in CSV/Parquet
4. ** Exploratory Data Analysis**: Uni-, bi-, and multi-variable statistical analysis
5. ** Visual Reports**: Interactive Plotly Express charts and dashboards
6. ** Data Quality**: Identify issues and execute cleaning strategies
7. ** Business Insights**: Draw actionable conclusions for hunger relief operations

### Oracle Data Sources:
- **Choice Database**: Service delivery, client demographics, food distribution
- **AgencyExpress Database**: Donor management, agency operations, geographical data

---

## 1. Environment Setup & Library Imports

Loading all required libraries for the complete Oracle-to-Graphics pipeline.

** Prerequisites:**
- Jupyter kernel: `HungerHub POC` (with Oracle libraries installed)
- Virtual environment activated with cx_Oracle, oracledb, scipy, tqdm

In [46]:
# Core data manipulation and analysis
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Oracle database connectivity
import cx_Oracle
import oracledb
import pyodbc
from sqlalchemy import create_engine
import sqlalchemy

# File I/O and configuration
import os
import sys
import json
from pathlib import Path
from dotenv import load_dotenv

# Visualization libraries
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.templates.default = "plotly_white"

# Statistical analysis and visualization
from scipy import stats as scipy_stats
import seaborn as sns
import matplotlib.pyplot as plt

# Progress tracking
from tqdm import tqdm

print("✅ All libraries loaded successfully!")
print(f" Oracle-to-Graphics analysis started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f" Oracle cx_Oracle version: {cx_Oracle.version}")
print(f" Oracle oracledb version: {oracledb.__version__}")

✅ All libraries loaded successfully!
 Oracle-to-Graphics analysis started: 2025-08-09 16:56:17
 Oracle cx_Oracle version: 8.3.0
 Oracle oracledb version: 3.3.0

In [47]:
# Configure display and analysis options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 100)
np.random.seed(42)  # For reproducible results

# Set up project paths
project_root = Path('../')
data_path = project_root / 'data'
config_path = project_root / 'config'
src_path = project_root / 'src'
output_path = Path('notebook_output')
output_path.mkdir(exist_ok=True)

# Add src to Python path for custom modules
sys.path.append(str(src_path))

print(f" Project root: {project_root.absolute()}")
print(f" Data path: {data_path.absolute()}")
print(f" Config path: {config_path.absolute()}")
print(f" Output path: {output_path.absolute()}")

 Project root: /home/tagazureuser/cgorr/2week_poc_execution/hungerhub_poc/notebooks/..
 Data path: /home/tagazureuser/cgorr/2week_poc_execution/hungerhub_poc/notebooks/../data
 Config path: /home/tagazureuser/cgorr/2week_poc_execution/hungerhub_poc/notebooks/../config
 Output path: /home/tagazureuser/cgorr/2week_poc_execution/hungerhub_poc/notebooks/notebook_output

In [48]:
# Analysis execution timer - START
analysis_start_time = datetime.now()
print(f"Analysis execution started at: {analysis_start_time.strftime('%Y-%m-%d %H:%M:%S')}")
print(f"Notebook type: SAMPLE DATA ANALYSIS")
print("-" * 50)

Analysis execution started at: 2025-08-09 16:56:17
Notebook type: SAMPLE DATA ANALYSIS
--------------------------------------------------

In [49]:
# Create notebook output directory structure
notebook_outputs = {
    'base': Path('notebook_output'),
    'csv': Path('notebook_output/csv'),
    'parquet': Path('notebook_output/parquet'),
    'reports': Path('notebook_output/reports'),
    'visualizations': Path('notebook_output/visualizations')
}

# Create all output directories
for name, path in notebook_outputs.items():
    path.mkdir(parents=True, exist_ok=True)
    print(f" Created: {path}")

# Update output_path to use notebook directory
output_path = notebook_outputs['base']
print(f"\n✅ All notebook outputs will be saved to: {output_path.absolute()}")
print(f" Available subdirectories: {list(notebook_outputs.keys())}")

 Created: notebook_output
 Created: notebook_output/csv
 Created: notebook_output/parquet
 Created: notebook_output/reports
 Created: notebook_output/visualizations

✅ All notebook outputs will be saved to: /home/tagazureuser/cgorr/2week_poc_execution/hungerhub_poc/notebooks/notebook_output
 Available subdirectories: ['base', 'csv', 'parquet', 'reports', 'visualizations']

In [50]:
# Load environment variables and Oracle connection settings
env_file = config_path / '.env'
if env_file.exists():
    load_dotenv(env_file)
    print("✅ Environment variables loaded from .env file")
    
    # Display available Oracle connection parameters (without showing sensitive data)
    oracle_params = ['ORACLE_HOST', 'ORACLE_PORT', 'ORACLE_SERVICE', 'ORACLE_USER']
    available_params = []
    for param in oracle_params:
        if os.getenv(param):
            available_params.append(param)
    
    if available_params:
        print(f" Oracle connection parameters available: {', '.join(available_params)}")
        # Test Oracle Instant Client availability
        try:
            cx_Oracle.clientversion()
            print("✅ Oracle Instant Client is available")
        except cx_Oracle.DatabaseError as e:
            print(f" Oracle Instant Client issue: {e}")
    else:
        print(" No Oracle connection parameters found in environment")
else:
    print(" .env file not found - will use existing processed data for analysis")

print("\n Environment setup complete! Ready for Oracle database connection and analysis.")

✅ Environment variables loaded from .env file
 No Oracle connection parameters found in environment

 Environment setup complete! Ready for Oracle database connection and analysis.

## 2. Oracle Database Connection & Data Extraction

Connecting to the actual HungerHub Oracle databases using the existing project configuration.

### Database Architecture:
- **Choice Sandbox**: Donations and Choice program data (`52.43.135.66:1521/staging`)
- **AgencyExpress Sandbox**: Agency operations data (`52.43.135.66:1521/staging`)

### Connection Strategy:
- Use the same connection parameters as existing project modules
- Test connectivity to both databases
- Extract sample data from priority tables
- Fall back to existing processed data if connections fail

In [51]:
# Oracle connection setup based on existing project configuration
class HungerHubOracleConnector:
    """Oracle database connector matching existing project setup"""
    
    def __init__(self):
        # Database configurations from .env file
        self.databases = {
            'choice': {
                'host': os.getenv('CHOICE_ORACLE_HOST'),
                'port': os.getenv('CHOICE_ORACLE_PORT', '1521'),
                'service': os.getenv('CHOICE_ORACLE_SERVICE_NAME'),
                'user': os.getenv('CHOICE_USERNAME'),
                'password': os.getenv('CHOICE_PASSWORD'),
                'name': 'Choice Sandbox'
            },
            'agency': {
                'host': os.getenv('AGENCY_ORACLE_HOST'),
                'port': os.getenv('AGENCY_ORACLE_PORT', '1521'),
                'service': os.getenv('AGENCY_ORACLE_SERVICE_NAME'),
                'user': os.getenv('AGENCY_USERNAME'),
                'password': os.getenv('AGENCY_PASSWORD'),
                'name': 'Agency Sandbox'
            }
        }
    
    def test_connection(self, db_key):
        """Test connection to a specific database"""
        config = self.databases[db_key]
        
        print(f"\nTesting {config['name']} Database:")
        print("-" * 40)
        
        # Check configuration
        missing_config = [k for k, v in config.items() if not v]
        if missing_config:
            print(f"❌ Missing configuration: {', '.join(missing_config)}")
            return None
        
        try:
            # Create DSN connection string
            dsn = cx_Oracle.makedsn(
                config['host'], 
                config['port'], 
                service_name=config['service']
            )
            
            print(f"Connecting to: {config['host']}:{config['port']}/{config['service']}")
            print(f"User: {config['user']}")
            
            # Establish connection
            connection = cx_Oracle.connect(
                config['user'], 
                config['password'], 
                dsn
            )
            
            print("✅ Connected successfully!")
            print(f"Oracle Version: {connection.version}")
            
            # Test basic query
            cursor = connection.cursor()
            cursor.execute("SELECT USER, SYSDATE FROM DUAL")
            user, sysdate = cursor.fetchone()
            
            print(f"Connected as: {user}")
            print(f"Server time: {sysdate}")
            
            # Test table access
            try:
                cursor.execute("SELECT COUNT(*) FROM user_tables")
                table_count = cursor.fetchone()[0]
                print(f"Accessible tables: {table_count}")
            except Exception as e:
                print(f"⚠️ Table query warning: {e}")
            
            cursor.close()
            return connection
            
        except cx_Oracle.Error as error:
            print(f"❌ Oracle connection failed: {error}")
            return None
        except Exception as error:
            print(f"❌ Unexpected error: {error}")
            return None
    def get_table_list(self, connection):
        """Get list of accessible tables"""
        try:
            cursor = connection.cursor()
            cursor.execute("""
                SELECT table_name, num_rows 
                FROM user_tables 
                ORDER BY table_name
            """)
            results = cursor.fetchall()
            cursor.close()
            
            df = pd.DataFrame(results, columns=['TABLE_NAME', 'NUM_ROWS'])
            return df
        except Exception as e:
            print(f"❌ Error getting table list: {e}")
            return None

# Initialize Oracle connector
oracle_connector = HungerHubOracleConnector()
print("✅ Oracle connector initialized with project configuration")

✅ Oracle connector initialized with project configuration

In [52]:
# Test Oracle database connections
oracle_connections = {}

print("Testing Oracle Database Connections")
print("=" * 50)

# Test Choice database
choice_conn = oracle_connector.test_connection('choice')
if choice_conn:
    oracle_connections['choice'] = choice_conn
    print("  ✅ Choice database connection successful")
else:
    print("  ❌ Choice database connection failed")

# Test Agency database
agency_conn = oracle_connector.test_connection('agency')
if agency_conn:
    oracle_connections['agency'] = agency_conn
    print("  ✅ Agency database connection successful")
else:
    print("  ❌ Agency database connection failed")

print(f"\nConnection Summary: {len(oracle_connections)}/2 databases connected")

if oracle_connections:
    print("✅ At least one Oracle database connection successful!")
    print("Ready to proceed with data extraction.")
    
    # Simple 5-second delay to let connections stabilize
    import time
    print("\nLetting connections stabilize...")
    time.sleep(5)
    print("✅ Connections ready for use")
else:
    print("⚠️ No Oracle connections available - will use existing processed data")

Testing Oracle Database Connections
==================================================

Testing Choice Sandbox Database:
----------------------------------------
Connecting to: 52.43.135.66:1521/staging
User: rwtxn_46
✅ Connected successfully!
Oracle Version: 11.2.0.1.0
Connected as: RWTXN_46
Server time: 2025-08-09 11:57:03
Accessible tables: 283
  ✅ Choice database connection successful

Testing Agency Sandbox Database:
----------------------------------------
Connecting to: 52.43.135.66:1521/staging
User: tran_user
✅ Connected successfully!
Oracle Version: 11.2.0.1.0
Connected as: TRAN_USER
Server time: 2025-08-09 11:57:04
Accessible tables: 367
  ✅ Agency database connection successful

Connection Summary: 2/2 databases connected
✅ At least one Oracle database connection successful!
Ready to proceed with data extraction.

Letting connections stabilize...
✅ Connections ready for use

In [53]:
# Extract sample data from priority tables
def extract_table_sample(connection, table_name, sample_size=1000):
    """Extract sample data from Oracle table"""
    try:
        # Oracle-specific query with ROWNUM for performance
        query = f"""
        SELECT * FROM {table_name} 
        WHERE ROWNUM <= {sample_size}
        """
        
        cursor = connection.cursor()
        cursor.execute(query)
        results = cursor.fetchall()
        columns = [desc[0] for desc in cursor.description]
        cursor.close()
        
        df = pd.DataFrame(results, columns=columns)
        print(f"    ✅ Extracted {len(df)} rows, {len(df.columns)} columns")
        return df
        
    except Exception as e:
        print(f"    ❌ Error extracting {table_name}: {e}")
        return None

# Priority tables based on existing project structure
priority_tables = {
    'choice': [
        'DOCUMENTHEADER',
        'AMX_DONATION_HEADER', 
        'AMX_DONATION_LINES',
        'RW_ORG'
    ],
    'agency': [
        'DOCUMENTHEADER',
        'DOCUMENTLINES',
        'RW_ORG'
    ]
}

extracted_oracle_data = {}

if oracle_connections:
    print(" Extracting Sample Data from Priority Tables")
    print("=" * 50)
    
    for db_key, connection in oracle_connections.items():
        print(f"\n Extracting from {oracle_connector.databases[db_key]['name']}:")
        
        # Get available tables for this database
        available_tables = set()
        # Extract all priority tables (no pre-validation needed)
        
        # Extract priority tables that exist
        for table_name in priority_tables.get(db_key, []):
            if table_name in available_tables or not available_tables:
                print(f"   Extracting {table_name}...")
                df = extract_table_sample(connection, table_name, sample_size=500)
                if df is not None:
                    key = f"{db_key}_{table_name}"
                    extracted_oracle_data[key] = df
                    
                    # Save to notebook output directory
                    output_file = output_path / f"{key}_sample.csv"
                    df.to_csv(output_file, index=False)
                    print(f"     Saved to {output_file.name}")
            else:
                print(f"   Table {table_name} not found in {db_key} database")
    
    print(f"\n✅ Successfully extracted {len(extracted_oracle_data)} datasets from Oracle")
else:
    print(" Loading existing processed data as fallback...")
    
    # Load existing processed data
    processed_data_path = data_path / 'processed'
    for file_path in processed_data_path.rglob('*.csv'):
        if 'unified_real' in str(file_path) or '_sample' in str(file_path.name):
            table_name = file_path.stem.replace('_sample', '')
            try:
                df = pd.read_csv(file_path)
                extracted_oracle_data[table_name] = df
                print(f"   Loaded {table_name}: {len(df)} rows × {len(df.columns)} columns")
            except Exception as e:
                print(f"  ❌ Error loading {file_path.name}: {e}")
    
    print(f"\n✅ Loaded {len(extracted_oracle_data)} datasets from existing files")

# Display summary of extracted data
if extracted_oracle_data:
    print(f"\n Data Extraction Summary:")
    print("-" * 60)
    total_rows = 0
    for dataset_name, df in extracted_oracle_data.items():
        rows, cols = df.shape
        total_rows += rows
        print(f"   {dataset_name:<30} {rows:>6} rows × {cols:>3} columns")
    
    print(f"\n Total extracted records: {total_rows:,} rows across {len(extracted_oracle_data)} tables")
else:
    print("❌ No data available for analysis")

 Extracting Sample Data from Priority Tables
==================================================

 Extracting from Choice Sandbox:
   Extracting DOCUMENTHEADER...
    ✅ Extracted 500 rows, 51 columns
     Saved to choice_DOCUMENTHEADER_sample.csv
   Extracting AMX_DONATION_HEADER...
    ✅ Extracted 500 rows, 30 columns
     Saved to choice_AMX_DONATION_HEADER_sample.csv
   Extracting AMX_DONATION_LINES...
    ✅ Extracted 500 rows, 26 columns
     Saved to choice_AMX_DONATION_LINES_sample.csv
   Extracting RW_ORG...
    ✅ Extracted 500 rows, 44 columns
     Saved to choice_RW_ORG_sample.csv

 Extracting from Agency Sandbox:
   Extracting DOCUMENTHEADER...
    ✅ Extracted 500 rows, 35 columns
     Saved to agency_DOCUMENTHEADER_sample.csv
   Extracting DOCUMENTLINES...
    ✅ Extracted 500 rows, 57 columns
     Saved to agency_DOCUMENTLINES_sample.csv
   Extracting RW_ORG...
    ✅ Extracted 500 rows, 50 columns
     Saved to agency_RW_ORG_sample.csv

✅ Successfully extracted 7 datasets from Oracle

 Data Extraction Summary:
------------------------------------------------------------
   choice_DOCUMENTHEADER             500 rows ×  51 columns
   choice_AMX_DONATION_HEADER        500 rows ×  30 columns
   choice_AMX_DONATION_LINES         500 rows ×  26 columns
   choice_RW_ORG                     500 rows ×  44 columns
   agency_DOCUMENTHEADER             500 rows ×  35 columns
   agency_DOCUMENTLINES              500 rows ×  57 columns
   agency_RW_ORG                     500 rows ×  50 columns

 Total extracted records: 3,500 rows across 7 tables

## 2.5 Database Schema Documentation

Comprehensive documentation of the HungerHub Oracle database schemas, table structures, and data characteristics.

### Database Architecture Overview:
- **Choice Sandbox**: Primary food distribution and client management system
- **AgencyExpress Sandbox**: Donor management and agency operations system

This section provides detailed schema analysis, record counts, data types, and relationship mapping between the two database systems.

In [54]:
# Comprehensive Database Documentation Generator
class DatabaseDocumentor:
    """Generate comprehensive database schema documentation"""
    
    def __init__(self, oracle_connections):
        self.connections = oracle_connections
        self.schema_info = {}
        self.documentation = {}
    
    def get_detailed_schema_info(self, connection, db_name):
        """Get comprehensive schema information"""
        try:
            cursor = connection.cursor()
            
            # Get table information with detailed stats
            table_query = """
            SELECT 
                table_name,
                num_rows,
                blocks,
                avg_row_len,
                last_analyzed,
                partitioned
            FROM user_tables 
            ORDER BY NVL(num_rows, 0) DESC
            """
            
            cursor.execute(table_query)
            tables_data = cursor.fetchall()
            
            tables_info = []
            for row in tables_data:
                table_info = {
                    'table_name': row[0],
                    'num_rows': row[1] if row[1] is not None else 0,
                    'blocks': row[2] if row[2] is not None else 0,
                    'avg_row_len': row[3] if row[3] is not None else 0,
                    'last_analyzed': row[4],
                    'partitioned': row[5]
                }
                tables_info.append(table_info)
            
            # Get column information for key tables (top 10 by size)
            top_tables = sorted(tables_info, key=lambda x: x['num_rows'], reverse=True)[:10]
            
            detailed_tables = {}
            for table in top_tables:
                table_name = table['table_name']
                
                # Get column details
                column_query = """
                SELECT 
                    column_name,
                    data_type,
                    data_length,
                    data_precision,
                    data_scale,
                    nullable,
                    column_id
                FROM user_tab_columns 
                WHERE table_name = :table_name
                ORDER BY column_id
                """
                
                cursor.execute(column_query, {'table_name': table_name})
                columns_data = cursor.fetchall()
                
                columns_info = []
                for col_row in columns_data:
                    col_info = {
                        'column_name': col_row[0],
                        'data_type': col_row[1],
                        'data_length': col_row[2],
                        'data_precision': col_row[3],
                        'data_scale': col_row[4],
                        'nullable': col_row[5],
                        'column_id': col_row[6]
                    }
                    columns_info.append(col_info)
                
                table['columns'] = columns_info
                detailed_tables[table_name] = table
            
            cursor.close()
            
            return {
                'database_name': db_name,
                'total_tables': len(tables_info),
                'total_records': sum(t['num_rows'] for t in tables_info),
                'tables_summary': tables_info,
                'detailed_tables': detailed_tables
            }
            
        except Exception as e:
            print(f"Error getting schema info for {db_name}: {e}")
            return None
    
    def generate_database_summary(self, schema_info):
        """Generate human-readable database summary"""
        db_name = schema_info['database_name']
        
        print(f"\n{'='*60}")
        print(f"DATABASE: {db_name.upper()}")
        print(f"{'='*60}")
        
        print(f"\nDATABASE OVERVIEW:")
        print(f"  Total Tables: {schema_info['total_tables']:,}")
        print(f"  Total Records: {schema_info['total_records']:,}")
        
        # Table size distribution
        tables = schema_info['tables_summary']
        large_tables = [t for t in tables if t['num_rows'] > 10000]
        medium_tables = [t for t in tables if 1000 <= t['num_rows'] <= 10000]
        small_tables = [t for t in tables if 0 < t['num_rows'] < 1000]
        empty_tables = [t for t in tables if t['num_rows'] == 0]
        
        print(f"\nTABLE SIZE DISTRIBUTION:")
        print(f"  Large (>10K records): {len(large_tables)} tables")
        print(f"  Medium (1K-10K records): {len(medium_tables)} tables")
        print(f"  Small (<1K records): {len(small_tables)} tables")
        print(f"  Empty (0 records): {len(empty_tables)} tables")
        
        # Top tables by size
        print(f"\nTOP 10 TABLES BY RECORD COUNT:")
        top_tables = sorted(tables, key=lambda x: x['num_rows'], reverse=True)[:10]
        for i, table in enumerate(top_tables, 1):
            avg_len = f"({table['avg_row_len']} bytes avg)" if table['avg_row_len'] else ""
            print(f"  {i:2d}. {table['table_name']:<30} {table['num_rows']:>10,} rows {avg_len}")
        
        return {
            'large_tables': len(large_tables),
            'medium_tables': len(medium_tables),
            'small_tables': len(small_tables),
            'empty_tables': len(empty_tables)
        }
    
    def generate_table_details(self, schema_info, max_tables=5):
        """Generate detailed table documentation"""
        db_name = schema_info['database_name']
        detailed_tables = schema_info['detailed_tables']
        
        print(f"\nDETAILED TABLE SCHEMAS ({db_name.upper()}):")
        print(f"{'='*50}")
        
        # Show details for top tables
        table_names = sorted(detailed_tables.keys(), 
                           key=lambda x: detailed_tables[x]['num_rows'], 
                           reverse=True)[:max_tables]
        
        for table_name in table_names:
            table = detailed_tables[table_name]
            
            print(f"\nTABLE: {table_name}")
            print("-" * 40)
            print(f"Records: {table['num_rows']:,}")
            print(f"Columns: {len(table['columns'])}")
            print(f"Avg Row Length: {table['avg_row_len']} bytes")
            print(f"Last Analyzed: {table['last_analyzed']}")
            
            print(f"\nCOLUMN STRUCTURE:")
            print(f"{'#':<3} {'Column Name':<25} {'Data Type':<15} {'Length':<8} {'Nullable':<8}")
            print("-" * 65)
            
            for col in table['columns'][:15]:  # Show first 15 columns
                col_type = col['data_type']
                if col['data_precision'] and col['data_scale']:
                    col_type += f"({col['data_precision']},{col['data_scale']})"
                elif col['data_length'] and col['data_type'] in ['VARCHAR2', 'CHAR']:
                    col_type += f"({col['data_length']})"
                
                nullable = "YES" if col['nullable'] == 'Y' else "NO"
                
                print(f"{col['column_id']:<3} {col['column_name']:<25} {col_type:<15} {col['data_length'] or '':<8} {nullable:<8}")
            
            if len(table['columns']) > 15:
                print(f"     ... and {len(table['columns']) - 15} more columns")
    
    def document_all_databases(self):
        """Generate complete database documentation"""
        print("COMPREHENSIVE DATABASE SCHEMA DOCUMENTATION")
        print("=" * 60)
        
        all_stats = {}
        
        for db_key, connection in self.connections.items():
            db_name = oracle_connector.databases[db_key]['name']
            
            print(f"\nAnalyzing {db_name} schema...")
            schema_info = self.get_detailed_schema_info(connection, db_name)
            
            if schema_info:
                # Generate summary
                stats = self.generate_database_summary(schema_info)
                all_stats[db_name] = stats
                
                # Generate detailed table documentation
                self.generate_table_details(schema_info)
                
                # Store for later use
                self.schema_info[db_key] = schema_info
        
        return all_stats

# Initialize database documentation if Oracle connections are available
if 'oracle_connections' in globals() and oracle_connections:
    db_documentor = DatabaseDocumentor(oracle_connections)
    print("✅ Database documentation toolkit initialized")
    print(f"Ready to document {len(oracle_connections)} Oracle databases")
else:
    print("❌ Database documentation requires active Oracle connections")
    print("Please run Section 2 Oracle connections first")

✅ Database documentation toolkit initialized
Ready to document 2 Oracle databases

In [55]:
# Generate Complete Database Documentation
if 'db_documentor' in globals():
    database_stats = db_documentor.document_all_databases()
    
    # Generate cross-database comparison
    if len(database_stats) > 1:
        print(f"\n\nCROSS-DATABASE COMPARISON")
        print("=" * 40)
        
        for db_name, stats in database_stats.items():
            schema_info = None
            for key, info in db_documentor.schema_info.items():
                if info['database_name'] == db_name:
                    schema_info = info
                    break
            
            if schema_info:
                print(f"\n{db_name}:")
                print(f"  Total Tables: {schema_info['total_tables']}")
                print(f"  Total Records: {schema_info['total_records']:,}")
                print(f"  Large Tables: {stats['large_tables']}")
                print(f"  Empty Tables: {stats['empty_tables']}")
    
    print(f"\n✅ Database documentation complete!")
else:
    print("❌ Database documentation toolkit not available")

COMPREHENSIVE DATABASE SCHEMA DOCUMENTATION
============================================================

Analyzing Choice Sandbox schema...

============================================================
DATABASE: CHOICE SANDBOX
============================================================

DATABASE OVERVIEW:
  Total Tables: 283
  Total Records: 7,646,604

TABLE SIZE DISTRIBUTION:
  Large (>10K records): 23 tables
  Medium (1K-10K records): 23 tables
  Small (<1K records): 132 tables
  Empty (0 records): 105 tables

TOP 10 TABLES BY RECORD COUNT:
   1. RW_FLEX                         4,393,524 rows (49 bytes avg)
   2. RW_PO_FLEX                        578,995 rows (54 bytes avg)
   3. RW_CONTACT_INFO                   566,783 rows (157 bytes avg)
   4. ACSHARES_ARCHIVE                  554,550 rows (100 bytes avg)
   5. RW_SHPMNT_METHOD                  231,675 rows (35 bytes avg)
   6. RW_ORDR_ITM_SCHDL                 230,282 rows (132 bytes avg)
   7. RW_ORDER_ITEM                     230,282 rows (236 bytes avg)
   8. RW_DOC_TRANS                      108,861 rows (55 bytes avg)
   9. BIDDINGSESSION_SNAPSHOT           102,470 rows (18 bytes avg)
  10. RW_ORDER_SUPPLIER                  96,552 rows (57 bytes avg)

DETAILED TABLE SCHEMAS (CHOICE SANDBOX):
==================================================

TABLE: RW_FLEX
----------------------------------------
Records: 4,393,524
Columns: 11
Avg Row Length: 49 bytes
Last Analyzed: 2017-01-14 12:43:32

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   AM_BASE_ID                VARCHAR2(30)    30       NO
2   REF_ID                    VARCHAR2(30)    30       NO
3   OT_BASE_ID                VARCHAR2(30)    30       NO
4   BLOB_VALUE                LONG RAW                 YES
5   BOOL_VALUE                VARCHAR2(1)     1        YES
6   DATE_VALUE                DATE            7        YES
7   DOUBLE_VALUE              FLOAT           22       YES
8   INTEGER_VALUE             NUMBER          22       YES
9   NUMERIC_VALUE             NUMBER(38,5)    22       YES
10  STRING_VALUE              VARCHAR2(2048)  2048     YES
11  RESERVED                  VARCHAR2(1)     1        YES

TABLE: RW_PO_FLEX
----------------------------------------
Records: 578,995
Columns: 11
Avg Row Length: 54 bytes
Last Analyzed: 2017-01-14 12:42:45

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   AM_BASE_ID                VARCHAR2(30)    30       NO
2   REF_ID                    VARCHAR2(30)    30       NO
3   OT_BASE_ID                VARCHAR2(30)    30       NO
4   BLOB_VALUE                LONG RAW                 YES
5   BOOL_VALUE                VARCHAR2(1)     1        YES
6   DATE_VALUE                DATE            7        YES
7   DOUBLE_VALUE              FLOAT           22       YES
8   INTEGER_VALUE             NUMBER          22       YES
9   NUMERIC_VALUE             NUMBER(38,5)    22       YES
10  STRING_VALUE              VARCHAR2(2048)  2048     YES
11  RESERVED                  VARCHAR2(1)     1        YES

TABLE: RW_CONTACT_INFO
----------------------------------------
Records: 566,783
Columns: 30
Avg Row Length: 157 bytes
Last Analyzed: 2017-01-14 12:43:11

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   ID                        VARCHAR2(30)    30       NO
2   OCA                       NUMBER          22       NO
3   REV_START                 NUMBER          22       NO
4   REV_END                   NUMBER          22       YES
5   CONTACT_NAME              VARCHAR2(255)   255      YES
6   ADDRESS_LINE_1            VARCHAR2(255)   255      YES
7   ADDRESS_LINE_2            VARCHAR2(255)   255      YES
8   ADDRESS_LINE_3            VARCHAR2(255)   255      YES
9   CITY                      VARCHAR2(30)    30       YES
10  STATE_PROV                VARCHAR2(30)    30       YES
11  POSTAL_CODE               VARCHAR2(30)    30       YES
12  COUNTRY                   VARCHAR2(60)    60       YES
13  LOCATION                  VARCHAR2(60)    60       YES
14  EMAIL                     VARCHAR2(255)   255      YES
15  PHONE                     VARCHAR2(30)    30       YES
     ... and 15 more columns

TABLE: ACSHARES_ARCHIVE
----------------------------------------
Records: 554,550
Columns: 19
Avg Row Length: 100 bytes
Last Analyzed: 2025-05-09 17:03:14

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   ORGNAME                   VARCHAR2(50)    50       YES
2   CITY                      VARCHAR2(50)    50       YES
3   NEWGOALFACTOR             FLOAT           22       YES
4   FOODBANKGOALFACTOR        FLOAT           22       YES
5   ISFRO                     NUMBER          22       YES
6   FROGOALFACTORWITHFEC      FLOAT           22       YES
7   INITIALSHARES             FLOAT           22       YES
8   INITIALCREDIT             FLOAT           22       YES
9   TEMPCOLUMN1               FLOAT           22       YES
10  TEMPCOLUMN2               FLOAT           22       YES
11  TEMPCOLUMN3               FLOAT           22       YES
12  TEMPCOLUMN4               FLOAT           22       YES
13  STATE                     VARCHAR2(4)     4        YES
14  CURRENTSHARES             FLOAT           22       YES
15  CURRENTCREDIT             FLOAT           22       YES
     ... and 4 more columns

TABLE: RW_SHPMNT_METHOD
----------------------------------------
Records: 231,675
Columns: 5
Avg Row Length: 35 bytes
Last Analyzed: 2017-01-14 12:42:41

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   ID                        VARCHAR2(30)    30       NO
2   OCA                       NUMBER          22       NO
3   SHIPMENT_CARRIER          VARCHAR2(60)    60       YES
4   SHIPMENT_MODE             VARCHAR2(60)    60       YES
5   ACCOUNT                   VARCHAR2(60)    60       YES

Analyzing Agency Sandbox schema...

============================================================
DATABASE: AGENCY SANDBOX
============================================================

DATABASE OVERVIEW:
  Total Tables: 367
  Total Records: 11,320,844

TABLE SIZE DISTRIBUTION:
  Large (>10K records): 54 tables
  Medium (1K-10K records): 13 tables
  Small (<1K records): 135 tables
  Empty (0 records): 165 tables

TOP 10 TABLES BY RECORD COUNT:
   1. DOCUMENTLINES                   3,509,953 rows (102 bytes avg)
   2. RW_UOM_CONV                     1,827,662 rows (106 bytes avg)
   3. RW_UOM                            630,787 rows (41 bytes avg)
   4. RW_CONTACT_INFO                   433,788 rows (95 bytes avg)
   5. RW_TOKENS                         340,636 rows (57 bytes avg)
   6. DOCUMENTHEADER                    340,157 rows (140 bytes avg)
   7. DOCUMENTHEADER_ARCHIVE            307,193 rows (143 bytes avg)
   8. RW_PARAMETER                      305,472 rows (166 bytes avg)
   9. RW_GROUP_PRIVILEGE                260,998 rows (29 bytes avg)
  10. RW_SHPMNT_METHOD                  224,256 rows (25 bytes avg)

DETAILED TABLE SCHEMAS (AGENCY SANDBOX):
==================================================

TABLE: DOCUMENTLINES
----------------------------------------
Records: 3,509,953
Columns: 57
Avg Row Length: 102 bytes
Last Analyzed: 2025-07-09 17:00:48

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   HEADERID                  VARCHAR2(25)    25       NO
2   LINEITEMNUMBER            NUMBER          22       NO
3   ITEMNAME                  VARCHAR2(255)   255      YES
4   ITEMCODE                  VARCHAR2(25)    25       YES
5   TRADINGGROUP              VARCHAR2(25)    25       YES
6   DESTINATIONORG            VARCHAR2(25)    25       YES
7   DONATEDQUANTITY           FLOAT           22       YES
8   PROP1                     VARCHAR2(50)    50       YES
9   PROP2                     VARCHAR2(50)    50       YES
10  PROP3                     VARCHAR2(50)    50       YES
11  PROP4                     VARCHAR2(50)    50       YES
12  PROP5                     VARCHAR2(50)    50       YES
13  PROP6                     VARCHAR2(50)    50       YES
14  PROP7                     VARCHAR2(50)    50       YES
15  PROP8                     VARCHAR2(50)    50       YES
     ... and 42 more columns

TABLE: RW_UOM_CONV
----------------------------------------
Records: 1,827,662
Columns: 14
Avg Row Length: 106 bytes
Last Analyzed: 2017-05-19 17:02:26

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   UOM_CONV_ID               VARCHAR2(30)    30       NO
2   TYPE                      VARCHAR2(20)    20       YES
3   CONVERSION                FLOAT           22       NO
4   SPECI_LEVEL               VARCHAR2(20)    20       NO
5   ARCHIVE_FLAG              VARCHAR2(1)     1        NO
6   BATCH_REF                 VARCHAR2(20)    20       YES
7   LAST_MODI_DATE            DATE            7        YES
8   EXPIRY_DATE               DATE            7        NO
9   EFFECTIVE_DATE            DATE            7        NO
10  FROM_UOM_T_ID             NUMBER          22       NO
11  TO_UOM_T_ID               NUMBER          22       NO
12  LAST_MODI_BY_ID           VARCHAR2(30)    30       YES
13  OCA                       NUMBER          22       NO
14  ORG_ID                    VARCHAR2(30)    30       NO

TABLE: RW_UOM
----------------------------------------
Records: 630,787
Columns: 6
Avg Row Length: 41 bytes
Last Analyzed: 2017-05-19 17:02:06

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   UOM_ID                    VARCHAR2(30)    30       NO
2   TOKEN_ID                  NUMBER          22       NO
3   ISO_CODE                  VARCHAR2(10)    10       YES
4   UOM_PRECISION             VARCHAR2(15)    15       YES
5   OCA                       NUMBER          22       NO
6   ORG_ID                    VARCHAR2(30)    30       NO

TABLE: RW_CONTACT_INFO
----------------------------------------
Records: 433,788
Columns: 30
Avg Row Length: 95 bytes
Last Analyzed: 2017-05-19 17:02:14

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   ID                        VARCHAR2(30)    30       NO
2   OCA                       NUMBER          22       NO
3   REV_START                 NUMBER          22       NO
4   REV_END                   NUMBER          22       YES
5   CONTACT_NAME              VARCHAR2(60)    60       YES
6   ADDRESS_LINE_1            VARCHAR2(30)    30       YES
7   ADDRESS_LINE_2            VARCHAR2(30)    30       YES
8   ADDRESS_LINE_3            VARCHAR2(30)    30       YES
9   CITY                      VARCHAR2(30)    30       YES
10  STATE_PROV                VARCHAR2(30)    30       YES
11  POSTAL_CODE               VARCHAR2(30)    30       YES
12  COUNTRY                   VARCHAR2(30)    30       YES
13  LOCATION                  VARCHAR2(60)    60       YES
14  EMAIL                     VARCHAR2(255)   255      YES
15  PHONE                     VARCHAR2(20)    20       YES
     ... and 15 more columns

TABLE: RW_TOKENS
----------------------------------------
Records: 340,636
Columns: 9
Avg Row Length: 57 bytes
Last Analyzed: 2017-05-19 17:02:04

COLUMN STRUCTURE:
#   Column Name               Data Type       Length   Nullable
-----------------------------------------------------------------
1   TOKENS_PK_ID              VARCHAR2(30)    30       NO
2   TOKEN_ID                  NUMBER          22       NO
3   TOKEN_VALUE               VARCHAR2(255)   255      NO
4   FLAG                      NUMBER          22       NO
5   COUNTRY                   VARCHAR2(2)     2        YES
6   LANGUAGE                  VARCHAR2(2)     2        YES
7   VARIANT                   VARCHAR2(4)     4        YES
8   OCA                       NUMBER          22       NO
9   ORG_ID                    VARCHAR2(30)    30       NO


CROSS-DATABASE COMPARISON
========================================

Choice Sandbox:
  Total Tables: 283
  Total Records: 7,646,604
  Large Tables: 23
  Empty Tables: 105

Agency Sandbox:
  Total Tables: 367
  Total Records: 11,320,844
  Large Tables: 54
  Empty Tables: 165

✅ Database documentation complete!

### Database Documentation Summary

The above analysis provides:

1. **Schema Overview**: Total tables and records per database
2. **Table Size Distribution**: Large, medium, small, and empty tables
3. **Top Tables**: Ranked by record count with size metrics
4. **Detailed Schema**: Column structures for largest tables
5. **Cross-Database Comparison**: Relative sizes and characteristics

This documentation serves as a reference for:
- Understanding data volume and distribution
- Identifying key tables for analysis
- Planning data extraction and ETL strategies
- Assessing data quality and completeness

## 3. ETL Pipeline Implementation

Implementing Extract, Transform, and Load processes to clean and standardize the Oracle data for analysis.

### ETL Strategy:
1. **Extract**: Raw data from Oracle (completed in Section 2) or existing processed files
2. **Transform**: Clean, standardize, and unify data across both databases
3. **Load**: Store processed data in optimized formats (CSV and Parquet)

### Data Quality Focus:
- **Standardize column names** and data types
- **Handle missing values** and duplicates
- **Unify date formats** and currency values
- **Create unified datasets** for cross-database analysis

### Output Formats:
- **CSV files**: Human-readable for inspection
- **Parquet files**: Optimized for fast analysis and visualization

In [56]:
# ETL Pipeline implementation
class HungerHubETLPipeline:
    """ETL Pipeline for HungerHub Oracle data processing"""
    
    def __init__(self, output_directory):
        self.output_dir = Path(output_directory)
        self.output_dir.mkdir(exist_ok=True)
        
        # Create subdirectories for organized output
        (self.output_dir / 'csv').mkdir(exist_ok=True)
        (self.output_dir / 'parquet').mkdir(exist_ok=True)
        
        self.transformation_log = []
        
    def log_transformation(self, step, details):
        """Log transformation steps"""
        timestamp = datetime.now().strftime('%H:%M:%S')
        log_entry = f"[{timestamp}] {step}: {details}"
        self.transformation_log.append(log_entry)
        print(f"   {step}: {details}")
    
    def standardize_column_names(self, df, dataset_name):
        """Standardize column names across datasets"""
        original_columns = df.columns.tolist()
        
        # Convert to lowercase and replace spaces/special chars
        df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('[^a-z0-9_]', '', regex=True)
        
        # Common column mappings for consistency
        column_mappings = {
            'id': 'record_id',
            'name': 'entity_name',
            'date': 'record_date',
            'amount': 'transaction_amount',
            'qty': 'quantity',
            'description': 'item_description'
        }
        
        # Apply mappings if columns exist
        for old_name, new_name in column_mappings.items():
            if old_name in df.columns:
                df.rename(columns={old_name: new_name}, inplace=True)
        
        renamed_count = sum(1 for old, new in zip(original_columns, df.columns) if old != new)
        self.log_transformation(f"Column Standardization ({dataset_name})", 
                              f"Standardized {renamed_count}/{len(df.columns)} column names")
        
        return df
    
    def clean_missing_values(self, df, dataset_name):
        """Handle missing values strategically"""
        initial_shape = df.shape
        missing_summary = df.isnull().sum()
        missing_cols = missing_summary[missing_summary > 0]
        
        if len(missing_cols) > 0:
            self.log_transformation(f"Missing Values Analysis ({dataset_name})", 
                                  f"Found missing data in {len(missing_cols)} columns")
            
            for col in missing_cols.index:
                missing_pct = (missing_cols[col] / len(df)) * 100
                print(f"     {col}: {missing_cols[col]} missing ({missing_pct:.1f}%)")
                
                # Strategic missing value handling
                if missing_pct > 90:
                    # Drop columns that are mostly empty
                    df.drop(columns=[col], inplace=True)
                    print(f"     Dropped {col} (>90% missing)")
                elif df[col].dtype in ['object', 'string']:
                    # Fill string columns with 'Unknown'
                    df[col].fillna('Unknown', inplace=True)
                elif df[col].dtype in ['int64', 'float64']:
                    # Fill numeric columns with median
                    df[col].fillna(df[col].median(), inplace=True)
                elif df[col].dtype == 'datetime64[ns]':
                    # Fill date columns with a default date
                    df[col].fillna(pd.Timestamp('1900-01-01'), inplace=True)
        
        final_shape = df.shape
        self.log_transformation(f"Missing Values Cleanup ({dataset_name})", 
                              f"Shape changed from {initial_shape} to {final_shape}")
        
        return df
    
    def standardize_data_types(self, df, dataset_name):
        """Standardize data types for consistency"""
        type_changes = 0
        
        for col in df.columns:
            original_type = str(df[col].dtype)
            
            # Convert date-like columns
            if 'date' in col.lower() or 'time' in col.lower():
                try:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                    if str(df[col].dtype) != original_type:
                        type_changes += 1
                except:
                    pass
            
            # Convert amount/price columns to float
            elif any(keyword in col.lower() for keyword in ['amount', 'price', 'cost', 'value']):
                try:
                    df[col] = pd.to_numeric(df[col], errors='coerce')
                    if str(df[col].dtype) != original_type:
                        type_changes += 1
                except:
                    pass
            
            # Convert ID columns to string for consistency
            elif 'id' in col.lower() and df[col].dtype != 'object':
                try:
                    df[col] = df[col].astype(str)
                    if 'object' != original_type:
                        type_changes += 1
                except:
                    pass
        
        self.log_transformation(f"Data Type Standardization ({dataset_name})", 
                              f"Converted {type_changes} column types")
        
        return df
    
    def remove_duplicates(self, df, dataset_name):
        """Remove duplicate records"""
        initial_count = len(df)
        df_cleaned = df.drop_duplicates()
        duplicates_removed = initial_count - len(df_cleaned)
        
        if duplicates_removed > 0:
            self.log_transformation(f"Duplicate Removal ({dataset_name})", 
                                  f"Removed {duplicates_removed} duplicate records")
        else:
            self.log_transformation(f"Duplicate Check ({dataset_name})", 
                                  f"No duplicates found")
        
        return df_cleaned
    
    def process_dataset(self, df, dataset_name):
        """Apply full ETL transformation to a dataset"""
        print(f"\n Processing {dataset_name}...")
        print(f"   Input: {df.shape[0]} rows × {df.shape[1]} columns")
        
        # Apply transformations in sequence
        df_processed = df.copy()
        df_processed = self.standardize_column_names(df_processed, dataset_name)
        df_processed = self.clean_missing_values(df_processed, dataset_name)
        df_processed = self.standardize_data_types(df_processed, dataset_name)
        df_processed = self.remove_duplicates(df_processed, dataset_name)
        
        print(f"  ✅ Output: {df_processed.shape[0]} rows × {df_processed.shape[1]} columns")
        
        return df_processed
    
    def save_dataset(self, df, dataset_name, formats=['csv', 'parquet']):
        """Save processed dataset in specified formats"""
        files_saved = []
        
        for format_type in formats:
            if format_type == 'csv':
                file_path = self.output_dir / 'csv' / f"{dataset_name}_processed.csv"
                df.to_csv(file_path, index=False)
                files_saved.append(file_path)
            
            elif format_type == 'parquet':
                file_path = self.output_dir / 'parquet' / f"{dataset_name}_processed.parquet"
                df.to_parquet(file_path, index=False)
                files_saved.append(file_path)
        
        self.log_transformation(f"Data Export ({dataset_name})", 
                              f"Saved in {len(files_saved)} formats")
        
        return files_saved
    
    def generate_processing_report(self):
        """Generate ETL processing report"""
        report = {
            'timestamp': datetime.now().isoformat(),
            'transformations': self.transformation_log,
            'total_steps': len(self.transformation_log)
        }
        
        report_file = self.output_dir / 'etl_processing_report.json'
        with open(report_file, 'w') as f:
            json.dump(report, f, indent=2)
        
        print(f"\n ETL Processing Report saved to: {report_file}")
        return report

# Initialize ETL Pipeline
etl_pipeline = HungerHubETLPipeline(output_path)
print("✅ ETL Pipeline initialized")
print(f" Output directory: {output_path.absolute()}")

✅ ETL Pipeline initialized
 Output directory: /home/tagazureuser/cgorr/2week_poc_execution/hungerhub_poc/notebooks/notebook_output

In [57]:
# Process extracted Oracle data through ETL pipeline
processed_datasets = {}

if extracted_oracle_data:
    print(" Starting ETL Processing of Oracle Data")
    print("=" * 50)
    
    # Process each extracted dataset
    for dataset_name, raw_df in tqdm(extracted_oracle_data.items(), desc="Processing datasets"):
        if len(raw_df) > 0:  # Only process non-empty datasets
            try:
                # Apply ETL transformations
                processed_df = etl_pipeline.process_dataset(raw_df, dataset_name)
                
                # Save processed data
                saved_files = etl_pipeline.save_dataset(processed_df, dataset_name)
                
                # Store in memory for analysis
                processed_datasets[dataset_name] = processed_df
                
                # Display sample of processed data
                print(f"   Sample of processed {dataset_name}:")
                print(f"     Columns: {list(processed_df.columns[:5])}{'...' if len(processed_df.columns) > 5 else ''}")
                if len(processed_df) > 0:
                    print(f"     Data types: {dict(processed_df.dtypes.head())}")
                
            except Exception as e:
                print(f"  ❌ Error processing {dataset_name}: {e}")
        else:
            print(f"   Skipping empty dataset: {dataset_name}")
    
    print(f"\n✅ ETL Processing Complete: {len(processed_datasets)} datasets processed")
else:
    print(" No extracted data available for ETL processing")

 Starting ETL Processing of Oracle Data
==================================================

Processing datasets:  29%|██▊       | 2/7 [00:00<00:00, 19.53it/s]

 Processing choice_DOCUMENTHEADER...
   Input: 500 rows × 51 columns
   Column Standardization (choice_DOCUMENTHEADER): Standardized 51/51 column names
   Missing Values Analysis (choice_DOCUMENTHEADER): Found missing data in 46 columns
     sourceorg: 4 missing (0.8%)
     userid: 440 missing (88.0%)
     createddate: 447 missing (89.4%)
     expirydate: 1 missing (0.2%)
     modifieddate: 500 missing (100.0%)
     Dropped modifieddate (>90% missing)
     warehouseid: 452 missing (90.4%)
     Dropped warehouseid (>90% missing)
     prop1: 195 missing (39.0%)
     prop2: 38 missing (7.6%)
     prop3: 29 missing (5.8%)
     prop4: 54 missing (10.8%)
     prop5: 9 missing (1.8%)
     prop6: 181 missing (36.2%)
     prop7: 6 missing (1.2%)
     prop8: 5 missing (1.0%)
     prop9: 5 missing (1.0%)
     prop10: 5 missing (1.0%)
     prop11: 5 missing (1.0%)
     prop12: 5 missing (1.0%)
     prop13: 5 missing (1.0%)
     prop14: 500 missing (100.0%)
     Dropped prop14 (>90% missing)
     prop15: 190 missing (38.0%)
     notify: 442 missing (88.4%)
     doctype: 500 missing (100.0%)
     Dropped doctype (>90% missing)
     username: 442 missing (88.4%)
     useremail: 442 missing (88.4%)
     domainid: 442 missing (88.4%)
     domainname: 442 missing (88.4%)
     prop16: 5 missing (1.0%)
     prop17: 500 missing (100.0%)
     Dropped prop17 (>90% missing)
     prop18: 21 missing (4.2%)
     prop19: 2 missing (0.4%)
     prop20: 9 missing (1.8%)
     prop21: 2 missing (0.4%)
     prop22: 2 missing (0.4%)
     prop23: 12 missing (2.4%)
     prop24: 2 missing (0.4%)
     prop25: 42 missing (8.4%)
     prop26: 428 missing (85.6%)
     prop27: 92 missing (18.4%)
     prop28: 25 missing (5.0%)
     prop29: 5 missing (1.0%)
     prop31: 263 missing (52.6%)
     prop32: 5 missing (1.0%)
     prop33: 5 missing (1.0%)
     prop34: 5 missing (1.0%)
     prop35: 29 missing (5.8%)
   Missing Values Cleanup (choice_DOCUMENTHEADER): Shape changed from (500, 51) to (500, 46)
   Data Type Standardization (choice_DOCUMENTHEADER): Converted 2 column types
   Duplicate Check (choice_DOCUMENTHEADER): No duplicates found
  ✅ Output: 500 rows × 46 columns
   Data Export (choice_DOCUMENTHEADER): Saved in 2 formats
   Sample of processed choice_DOCUMENTHEADER:
     Columns: ['documentid', 'refnumber', 'sourceorg', 'userid', 'status']...
     Data types: {'documentid': dtype('O'), 'refnumber': dtype('O'), 'sourceorg': dtype('O'), 'userid': dtype('O'), 'status': dtype('int64')}

 Processing choice_AMX_DONATION_HEADER...
   Input: 500 rows × 30 columns
   Column Standardization (choice_AMX_DONATION_HEADER): Standardized 30/30 column names
   Missing Values Analysis (choice_AMX_DONATION_HEADER): Found missing data in 26 columns
     dcontactname: 7 missing (1.4%)
     dcontactcitystatezip: 492 missing (98.4%)
     Dropped dcontactcitystatezip (>90% missing)
     dcontactphone: 58 missing (11.6%)
     dcontactfax: 441 missing (88.2%)
     donorreferencenumber: 217 missing (43.4%)
     donationdate: 8 missing (1.6%)
     releasedate: 11 missing (2.2%)
     dcontactemail: 19 missing (3.8%)
     rcontactname: 38 missing (7.6%)
     rcontactphone: 76 missing (15.2%)
     rcontactemail: 45 missing (9.0%)
     wcontactname: 10 missing (2.0%)
     warehousename: 8 missing (1.6%)
     wcontactaddress: 9 missing (1.8%)
     wcontactcitystatezip: 8 missing (1.6%)
     wcontactphone: 48 missing (9.6%)
     wcontactfax: 464 missing (92.8%)
     Dropped wcontactfax (>90% missing)
     releasenumber: 171 missing (34.2%)
     shipmentmethod: 5 missing (1.0%)
     stagingmethod: 6 missing (1.2%)
     deliveryinstructions: 167 missing (33.4%)
     magrefnumber: 492 missing (98.4%)
     Dropped magrefnumber (>90% missing)
     htmlfilename: 500 missing (100.0%)
     Dropped htmlfilename (>90% missing)
     outbydate: 32 missing (6.4%)
     rcontactfax: 454 missing (90.8%)
     Dropped rcontactfax (>90% missing)
     wcontactemail: 68 missing (13.6%)
   Missing Values Cleanup (choice_AMX_DONATION_HEADER): Shape changed from (500, 30) to (500, 25)
   Data Type Standardization (choice_AMX_DONATION_HEADER): Converted 3 column types
   Duplicate Check (choice_AMX_DONATION_HEADER): No duplicates found
  ✅ Output: 500 rows × 25 columns
   Data Export (choice_AMX_DONATION_HEADER): Saved in 2 formats
   Sample of processed choice_AMX_DONATION_HEADER:
     Columns: ['donationnumber', 'donorid', 'donorname', 'dcontactname', 'dcontactphone']...
     Data types: {'donationnumber': dtype('O'), 'donorid': dtype('O'), 'donorname': dtype('O'), 'dcontactname': dtype('O'), 'dcontactphone': dtype('O')}

 Processing choice_AMX_DONATION_LINES...
   Input: 500 rows × 26 columns
   Column Standardization (choice_AMX_DONATION_LINES): Standardized 26/26 column names
   Missing Values Analysis (choice_AMX_DONATION_LINES): Found missing data in 21 columns
     donationreason: 4 missing (0.8%)
     pack: 48 missing (9.6%)
     size_: 348 missing (69.6%)
     sizeuom: 164 missing (32.8%)
     packagingtype: 330 missing (66.0%)
     unitofmeasure: 89 missing (17.8%)
     quantity: 4 missing (0.8%)
     quantityperpallet: 8 missing (1.6%)
     totalpallets: 8 missing (1.6%)
     totalgrossweight: 4 missing (0.8%)
     netweight: 441 missing (88.2%)
     cube: 500 missing (100.0%)
     Dropped cube (>90% missing)
     storagerequirement: 4 missing (0.8%)
     manufacturedate: 164 missing (32.8%)
     expirationdate: 425 missing (85.0%)
     shelflife: 351 missing (70.2%)
     extension: 320 missing (64.0%)
     usebydate: 20 missing (4.0%)
     billofladingnumber: 485 missing (97.0%)
     Dropped billofladingnumber (>90% missing)
     status: 228 missing (45.6%)
     codedatetype: 500 missing (100.0%)
     Dropped codedatetype (>90% missing)
   Missing Values Cleanup (choice_AMX_DONATION_LINES): Shape changed from (500, 26) to (500, 23)
   Data Type Standardization (choice_AMX_DONATION_LINES): Converted 3 column types
   Duplicate Check (choice_AMX_DONATION_LINES): No duplicates found
  ✅ Output: 500 rows × 23 columns
   Data Export (choice_AMX_DONATION_LINES): Saved in 2 formats
   Sample of processed choice_AMX_DONATION_LINES:
     Columns: ['donationnumber', 'itemnumber', 'itemdescription', 'donationreason', 'pack']...
     Data types: {'donationnumber': dtype('O'), 'itemnumber': dtype('O'), 'itemdescription': dtype('O'), 'donationreason': dtype('O'), 'pack': dtype('O')}

 Processing choice_RW_ORG...
   Input: 500 rows × 44 columns
   Column Standardization (choice_RW_ORG): Standardized 44/44 column names
   Missing Values Analysis (choice_RW_ORG): Found missing data in 23 columns
     printable_name: 122 missing (24.4%)
     e_mail: 499 missing (99.8%)
     Dropped e_mail (>90% missing)
     item_description: 491 missing (98.2%)
     Dropped item_description (>90% missing)
     one_approver_flag: 500 missing (100.0%)
     Dropped one_approver_flag (>90% missing)
     final_amount: 500 missing (100.0%)
     Dropped final_amount (>90% missing)
     variant: 500 missing (100.0%)
     Dropped variant (>90% missing)
     domain: 500 missing (100.0%)
     Dropped domain (>90% missing)
     url: 500 missing (100.0%)
     Dropped url (>90% missing)
     division_id: 500 missing (100.0%)
     Dropped division_id (>90% missing)
     external_id: 500 missing (100.0%)
     Dropped external_id (>90% missing)
     duns_number: 500 missing (100.0%)
     Dropped duns_number (>90% missing)
     tax_id: 500 missing (100.0%)
     Dropped tax_id (>90% missing)
     industry_code: 500 missing (100.0%)
     Dropped industry_code (>90% missing)
     contact_name: 500 missing (100.0%)
     Dropped contact_name (>90% missing)
     custom_type: 500 missing (100.0%)
     Dropped custom_type (>90% missing)
     years_in_business: 8 missing (1.6%)
     industry_val_num: 8 missing (1.6%)
     annual_rev_vid: 8 missing (1.6%)
     emp_count_vid: 8 missing (1.6%)
     parent_org_id: 1 missing (0.2%)
     final_approver_id: 500 missing (100.0%)
     Dropped final_approver_id (>90% missing)
     admin_user_id: 500 missing (100.0%)
     Dropped admin_user_id (>90% missing)
     supplier_id: 495 missing (99.0%)
     Dropped supplier_id (>90% missing)
   Missing Values Cleanup (choice_RW_ORG): Shape changed from (500, 44) to (500, 27)
   Data Type Standardization (choice_RW_ORG): Converted 3 column types
   Duplicate Check (choice_RW_ORG): No duplicates found
  ✅ Output: 500 rows × 27 columns
   Data Export (choice_RW_ORG): Saved in 2 formats
   Sample of processed choice_RW_ORG:
     Columns: ['org_id', 'entity_name', 'printable_name', 'status_flag', 'currency']...
     Data types: {'org_id': dtype('O'), 'entity_name': dtype('O'), 'printable_name': dtype('O'), 'status_flag': dtype('O'), 'currency': dtype('O')}

 Processing agency_DOCUMENTHEADER...
   Input: 500 rows × 35 columns
   Column Standardization (agency_DOCUMENTHEADER): Standardized 35/35 column names
   Missing Values Analysis (agency_DOCUMENTHEADER): Found missing data in 27 columns
     userid: 426 missing (85.2%)
     createddate: 6 missing (1.2%)
     modifieddate: 6 missing (1.2%)
     warehouseid: 438 missing (87.6%)
     prop1: 196 missing (39.2%)
     prop2: 457 missing (91.4%)
     Dropped prop2 (>90% missing)
     prop3: 460 missing (92.0%)
     Dropped prop3 (>90% missing)
     prop4: 460 missing (92.0%)
     Dropped prop4 (>90% missing)
     prop5: 457 missing (91.4%)
     Dropped prop5 (>90% missing)
     prop6: 500 missing (100.0%)
     Dropped prop6 (>90% missing)
     prop7: 500 missing (100.0%)
     Dropped prop7 (>90% missing)
     prop8: 500 missing (100.0%)
     Dropped prop8 (>90% missing)
     prop9: 500 missing (100.0%)
     Dropped prop9 (>90% missing)
     prop10: 500 missing (100.0%)
     Dropped prop10 (>90% missing)
     prop11: 500 missing (100.0%)
     Dropped prop11 (>90% missing)
     prop12: 500 missing (100.0%)
     Dropped prop12 (>90% missing)
     prop13: 500 missing (100.0%)
     Dropped prop13 (>90% missing)
     prop14: 500 missing (100.0%)
     Dropped prop14 (>90% missing)
     prop15: 479 missing (95.8%)
     Dropped prop15 (>90% missing)
     notify: 426 missing (85.2%)
     doctype: 500 missing (100.0%)
     Dropped doctype (>90% missing)
     username: 426 missing (85.2%)
     useremail: 426 missing (85.2%)
     sourceorgname: 426 missing (85.2%)
     domainid: 432 missing (86.4%)
     domainname: 426 missing (85.2%)
     modifiedby: 500 missing (100.0%)
     Dropped modifiedby (>90% missing)
   Missing Values Cleanup (agency_DOCUMENTHEADER): Shape changed from (500, 35) to (500, 19)
   Data Type Standardization (agency_DOCUMENTHEADER): Converted 4 column types
   Duplicate Check (agency_DOCUMENTHEADER): No duplicates found
  ✅ Output: 500 rows × 19 columns
   Data Export (agency_DOCUMENTHEADER): Saved in 2 formats
   Sample of processed agency_DOCUMENTHEADER:
     Columns: ['documentid', 'refnumber', 'sourceorg', 'userid', 'status']...
     Data types: {'documentid': dtype('O'), 'refnumber': dtype('O'), 'sourceorg': dtype('O'), 'userid': dtype('O'), 'status': dtype('int64')}

 Processing agency_DOCUMENTLINES...
   Input: 500 rows × 57 columns
   Column Standardization (agency_DOCUMENTLINES): Standardized 57/57 column names
   Missing Values Analysis (agency_DOCUMENTLINES): Found missing data in 48 columns
     tradinggroup: 500 missing (100.0%)
     Dropped tradinggroup (>90% missing)
     destinationorg: 500 missing (100.0%)
     Dropped destinationorg (>90% missing)
     prop1: 10 missing (2.0%)
     prop4: 132 missing (26.4%)
     prop5: 236 missing (47.2%)
     prop6: 114 missing (22.8%)
     prop8: 500 missing (100.0%)
     Dropped prop8 (>90% missing)
     prop9: 500 missing (100.0%)
     Dropped prop9 (>90% missing)
     prop10: 500 missing (100.0%)
     Dropped prop10 (>90% missing)
     prop11: 500 missing (100.0%)
     Dropped prop11 (>90% missing)
     prop12: 500 missing (100.0%)

Processing datasets: 100%|██████████| 7/7 [00:00<00:00, 24.73it/s]

     Dropped prop12 (>90% missing)
     prop13: 500 missing (100.0%)
     Dropped prop13 (>90% missing)
     prop14: 500 missing (100.0%)
     Dropped prop14 (>90% missing)
     prop16: 500 missing (100.0%)
     Dropped prop16 (>90% missing)
     prop17: 500 missing (100.0%)
     Dropped prop17 (>90% missing)
     prop18: 500 missing (100.0%)
     Dropped prop18 (>90% missing)
     prop19: 500 missing (100.0%)
     Dropped prop19 (>90% missing)
     prop20: 500 missing (100.0%)
     Dropped prop20 (>90% missing)
     notify: 481 missing (96.2%)
     Dropped notify (>90% missing)
     prop15: 500 missing (100.0%)
     Dropped prop15 (>90% missing)
     acceptedquantity: 6 missing (1.2%)
     accepteddate: 6 missing (1.2%)
     receiptedquantity: 500 missing (100.0%)
     Dropped receiptedquantity (>90% missing)
     receipteddate: 500 missing (100.0%)
     Dropped receipteddate (>90% missing)
     destinationorgname: 500 missing (100.0%)
     Dropped destinationorgname (>90% missing)
     comments: 500 missing (100.0%)
     Dropped comments (>90% missing)
     userid: 500 missing (100.0%)
     Dropped userid (>90% missing)
     userfirstname: 500 missing (100.0%)
     Dropped userfirstname (>90% missing)
     userlastname: 500 missing (100.0%)
     Dropped userlastname (>90% missing)
     useremail: 500 missing (100.0%)
     Dropped useremail (>90% missing)
     rprop1: 7 missing (1.4%)
     rprop2: 500 missing (100.0%)
     Dropped rprop2 (>90% missing)
     rprop3: 500 missing (100.0%)
     Dropped rprop3 (>90% missing)
     rprop4: 500 missing (100.0%)
     Dropped rprop4 (>90% missing)
     rprop5: 500 missing (100.0%)
     Dropped rprop5 (>90% missing)
     rprop6: 500 missing (100.0%)
     Dropped rprop6 (>90% missing)
     rprop7: 500 missing (100.0%)
     Dropped rprop7 (>90% missing)
     rprop8: 500 missing (100.0%)
     Dropped rprop8 (>90% missing)
     rprop9: 500 missing (100.0%)
     Dropped rprop9 (>90% missing)
     rprop10: 500 missing (100.0%)
     Dropped rprop10 (>90% missing)
     rprop11: 500 missing (100.0%)
     Dropped rprop11 (>90% missing)
     rprop12: 500 missing (100.0%)
     Dropped rprop12 (>90% missing)
     rprop13: 500 missing (100.0%)
     Dropped rprop13 (>90% missing)
     rprop14: 500 missing (100.0%)
     Dropped rprop14 (>90% missing)
     rprop15: 500 missing (100.0%)
     Dropped rprop15 (>90% missing)
     nutritionalcode: 500 missing (100.0%)
     Dropped nutritionalcode (>90% missing)
     foodsource: 500 missing (100.0%)
     Dropped foodsource (>90% missing)
     featuretype: 500 missing (100.0%)
     Dropped featuretype (>90% missing)
   Missing Values Cleanup (agency_DOCUMENTLINES): Shape changed from (500, 57) to (500, 16)
   Data Type Standardization (agency_DOCUMENTLINES): Converted 1 column types
   Duplicate Check (agency_DOCUMENTLINES): No duplicates found
  ✅ Output: 500 rows × 16 columns
   Data Export (agency_DOCUMENTLINES): Saved in 2 formats
   Sample of processed agency_DOCUMENTLINES:
     Columns: ['headerid', 'lineitemnumber', 'itemname', 'itemcode', 'donatedquantity']...
     Data types: {'headerid': dtype('O'), 'lineitemnumber': dtype('int64'), 'itemname': dtype('O'), 'itemcode': dtype('O'), 'donatedquantity': dtype('float64')}

 Processing agency_RW_ORG...
   Input: 500 rows × 50 columns
   Column Standardization (agency_RW_ORG): Standardized 50/50 column names
   Missing Values Analysis (agency_RW_ORG): Found missing data in 30 columns
     printable_name: 2 missing (0.4%)
     e_mail: 281 missing (56.2%)
     item_description: 499 missing (99.8%)
     Dropped item_description (>90% missing)
     one_approver_flag: 500 missing (100.0%)
     Dropped one_approver_flag (>90% missing)
     final_amount: 500 missing (100.0%)
     Dropped final_amount (>90% missing)
     variant: 500 missing (100.0%)
     Dropped variant (>90% missing)
     domain: 500 missing (100.0%)
     Dropped domain (>90% missing)
     url: 494 missing (98.8%)
     Dropped url (>90% missing)
     division_id: 500 missing (100.0%)
     Dropped division_id (>90% missing)
     external_id: 500 missing (100.0%)
     Dropped external_id (>90% missing)
     duns_number: 500 missing (100.0%)
     Dropped duns_number (>90% missing)
     tax_id: 500 missing (100.0%)
     Dropped tax_id (>90% missing)
     industry_code: 500 missing (100.0%)
     Dropped industry_code (>90% missing)
     contact_name: 500 missing (100.0%)
     Dropped contact_name (>90% missing)
     custom_type: 500 missing (100.0%)
     Dropped custom_type (>90% missing)
     path: 1 missing (0.2%)
     years_in_business: 1 missing (0.2%)
     industry_val_num: 1 missing (0.2%)
     annual_rev_vid: 1 missing (0.2%)
     emp_count_vid: 1 missing (0.2%)
     parent_org_id: 1 missing (0.2%)
     final_approver_id: 500 missing (100.0%)
     Dropped final_approver_id (>90% missing)
     admin_user_id: 500 missing (100.0%)
     Dropped admin_user_id (>90% missing)
     supplier_id: 499 missing (99.8%)
     Dropped supplier_id (>90% missing)
     onlineorderstatus: 500 missing (100.0%)
     Dropped onlineorderstatus (>90% missing)
     questionnairegroupcode: 500 missing (100.0%)
     Dropped questionnairegroupcode (>90% missing)
     deliveryzone: 500 missing (100.0%)
     Dropped deliveryzone (>90% missing)
     creditlimit: 500 missing (100.0%)
     Dropped creditlimit (>90% missing)
     holdcode: 500 missing (100.0%)
     Dropped holdcode (>90% missing)
     isactiveforae4: 500 missing (100.0%)
     Dropped isactiveforae4 (>90% missing)
   Missing Values Cleanup (agency_RW_ORG): Shape changed from (500, 50) to (500, 28)
   Data Type Standardization (agency_RW_ORG): Converted 3 column types
   Duplicate Check (agency_RW_ORG): No duplicates found
  ✅ Output: 500 rows × 28 columns
   Data Export (agency_RW_ORG): Saved in 2 formats
   Sample of processed agency_RW_ORG:
     Columns: ['org_id', 'entity_name', 'printable_name', 'status_flag', 'e_mail']...
     Data types: {'org_id': dtype('O'), 'entity_name': dtype('O'), 'printable_name': dtype('O'), 'status_flag': dtype('O'), 'e_mail': dtype('O')}

✅ ETL Processing Complete: 7 datasets processed

In [58]:
# Create unified datasets for cross-database analysis
def create_unified_dataset(datasets, dataset_type, etl_pipeline):
    """Create unified dataset by combining similar tables from both databases"""
    
    matching_datasets = []
    dataset_sources = []
    
    # Find datasets that match the type (e.g., 'DOCUMENTHEADER')
    for name, df in datasets.items():
        if dataset_type.lower() in name.lower():
            # Add source database column
            df_with_source = df.copy()
            source_db = 'choice' if 'choice' in name.lower() else 'agency'
            df_with_source['source_database'] = source_db
            df_with_source['source_table'] = name
            
            matching_datasets.append(df_with_source)
            dataset_sources.append(name)
    
    if len(matching_datasets) == 0:
        print(f"   No datasets found for type: {dataset_type}")
        return None
    
    print(f"   Unifying {len(matching_datasets)} datasets: {', '.join(dataset_sources)}")
    
    try:
        # Find common columns across all datasets
        common_columns = set(matching_datasets[0].columns)
        for df in matching_datasets[1:]:
            common_columns = common_columns.intersection(set(df.columns))
        
        common_columns = list(common_columns)
        print(f"   Found {len(common_columns)} common columns")
        
        # Combine datasets using common columns
        unified_dfs = []
        for df in matching_datasets:
            unified_dfs.append(df[common_columns])
        
        unified_df = pd.concat(unified_dfs, ignore_index=True, sort=False)
        
        # Apply ETL processing to unified dataset
        unified_df = etl_pipeline.process_dataset(unified_df, f"unified_{dataset_type}")
        
        print(f"  ✅ Created unified dataset: {unified_df.shape[0]} rows × {unified_df.shape[1]} columns")
        
        return unified_df
        
    except Exception as e:
        print(f"  ❌ Error creating unified dataset for {dataset_type}: {e}")
        return None

# Create unified datasets
unified_datasets = {}

if processed_datasets:
    print(" Creating Unified Datasets for Cross-Database Analysis")
    print("=" * 55)
    
    # Define dataset types to unify
    unify_types = [
        'DOCUMENTHEADER',
        'DONATION_HEADER', 
        'RW_ORG'
    ]
    
    for dataset_type in unify_types:
        print(f"\n Creating unified {dataset_type} dataset...")
        
        unified_df = create_unified_dataset(processed_datasets, dataset_type, etl_pipeline)
        if unified_df is not None:
            unified_datasets[f"unified_{dataset_type.lower()}"] = unified_df
            
            # Save unified dataset
            etl_pipeline.save_dataset(unified_df, f"unified_{dataset_type.lower()}")
    
    print(f"\n✅ Created {len(unified_datasets)} unified datasets")
else:
    print(" No processed datasets available for unification")

# Display summary of all processed data
all_datasets = {**processed_datasets, **unified_datasets}

if all_datasets:
    print(f"\n ETL Pipeline Results Summary")
    print("=" * 40)
    print(f" Individual Datasets: {len(processed_datasets)}")
    print(f" Unified Datasets: {len(unified_datasets)}")
    print(f" Total Datasets Available: {len(all_datasets)}")
    
    print(f"\n Dataset Inventory:")
    total_records = 0
    for name, df in all_datasets.items():
        rows, cols = df.shape
        total_records += rows
        dataset_type = " Unified" if name.startswith('unified_') else " Individual"
        print(f"  {dataset_type:<12} {name:<35} {rows:>6,} rows × {cols:>3} columns")
    
    print(f"\n Total processed records: {total_records:,}")
else:
    print("❌ No datasets available after ETL processing")

 Creating Unified Datasets for Cross-Database Analysis
=======================================================

 Creating unified DOCUMENTHEADER dataset...
   Unifying 2 datasets: choice_DOCUMENTHEADER, agency_DOCUMENTHEADER
   Found 16 common columns

 Processing unified_DOCUMENTHEADER...
   Input: 1000 rows × 16 columns
   Column Standardization (unified_DOCUMENTHEADER): Standardized 0/16 column names
   Missing Values Cleanup (unified_DOCUMENTHEADER): Shape changed from (1000, 16) to (1000, 16)
   Data Type Standardization (unified_DOCUMENTHEADER): Converted 0 column types
   Duplicate Check (unified_DOCUMENTHEADER): No duplicates found
  ✅ Output: 1000 rows × 16 columns
  ✅ Created unified dataset: 1000 rows × 16 columns
   Data Export (unified_documentheader): Saved in 2 formats

 Creating unified DONATION_HEADER dataset...
   Unifying 1 datasets: choice_AMX_DONATION_HEADER
   Found 27 common columns

 Processing unified_DONATION_HEADER...
   Input: 500 rows × 27 columns
   Column Standardization (unified_DONATION_HEADER): Standardized 0/27 column names
   Missing Values Analysis (unified_DONATION_HEADER): Found missing data in 3 columns
     donationdate: 8 missing (1.6%)
     outbydate: 32 missing (6.4%)
     releasedate: 11 missing (2.2%)
   Missing Values Cleanup (unified_DONATION_HEADER): Shape changed from (500, 27) to (500, 27)
   Data Type Standardization (unified_DONATION_HEADER): Converted 0 column types
   Duplicate Check (unified_DONATION_HEADER): No duplicates found
  ✅ Output: 500 rows × 27 columns
  ✅ Created unified dataset: 500 rows × 27 columns
   Data Export (unified_donation_header): Saved in 2 formats

 Creating unified RW_ORG dataset...
   Unifying 2 datasets: choice_RW_ORG, agency_RW_ORG
   Found 29 common columns

 Processing unified_RW_ORG...
   Input: 1000 rows × 29 columns
   Column Standardization (unified_RW_ORG): Standardized 0/29 column names
   Missing Values Analysis (unified_RW_ORG): Found missing data in 1 columns
     time_zone: 1000 missing (100.0%)
     Dropped time_zone (>90% missing)
   Missing Values Cleanup (unified_RW_ORG): Shape changed from (1000, 29) to (1000, 28)
   Data Type Standardization (unified_RW_ORG): Converted 0 column types
   Duplicate Check (unified_RW_ORG): No duplicates found
  ✅ Output: 1000 rows × 28 columns
  ✅ Created unified dataset: 1000 rows × 28 columns
   Data Export (unified_rw_org): Saved in 2 formats

✅ Created 3 unified datasets

 ETL Pipeline Results Summary
========================================
 Individual Datasets: 7
 Unified Datasets: 3
 Total Datasets Available: 10

 Dataset Inventory:
   Individual  choice_DOCUMENTHEADER                  500 rows ×  46 columns
   Individual  choice_AMX_DONATION_HEADER             500 rows ×  25 columns
   Individual  choice_AMX_DONATION_LINES              500 rows ×  23 columns
   Individual  choice_RW_ORG                          500 rows ×  27 columns
   Individual  agency_DOCUMENTHEADER                  500 rows ×  19 columns
   Individual  agency_DOCUMENTLINES                   500 rows ×  16 columns
   Individual  agency_RW_ORG                          500 rows ×  28 columns
   Unified     unified_documentheader               1,000 rows ×  16 columns
   Unified     unified_donation_header                500 rows ×  27 columns
   Unified     unified_rw_org                       1,000 rows ×  28 columns

 Total processed records: 6,000

In [59]:
# Generate comprehensive ETL report and data quality summary
etl_report = etl_pipeline.generate_processing_report()

print("\n ETL Processing Report Summary")
print("=" * 40)
print(f"⏰ Processing completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print(f" Total transformation steps: {etl_report['total_steps']}")

# Data quality metrics
if all_datasets:
    print(f"\n Data Quality Metrics:")
    print("-" * 30)
    
    for dataset_name, df in all_datasets.items():
        if len(df) > 0:
            missing_pct = (df.isnull().sum().sum() / (len(df) * len(df.columns))) * 100
            duplicate_pct = ((len(df) - len(df.drop_duplicates())) / len(df)) * 100
            
            print(f"   {dataset_name[:30]:<30}")
            print(f"       Missing data: {missing_pct:.1f}%")
            print(f"       Duplicates: {duplicate_pct:.1f}%")
            print(f"       Data types: {len(df.dtypes.unique())} unique types")
            print()

# Save final summary
summary = {
    'etl_completion_time': datetime.now().isoformat(),
    'datasets_processed': len(processed_datasets),
    'unified_datasets_created': len(unified_datasets),
    'total_records_processed': sum(len(df) for df in all_datasets.values()) if all_datasets else 0,
    'output_directory': str(output_path),
    'transformation_steps': etl_report['total_steps']
}

summary_file = output_path / 'etl_summary.json'
with open(summary_file, 'w') as f:
    json.dump(summary, f, indent=2)

print(f" ETL summary saved to: {summary_file}")
print(f"\n ETL Pipeline Complete! Ready for Exploratory Data Analysis.")

 ETL Processing Report saved to: notebook_output/etl_processing_report.json

 ETL Processing Report Summary
========================================
⏰ Processing completed at: 2025-08-09 16:56:34
 Total transformation steps: 59

 Data Quality Metrics:
------------------------------
   choice_DOCUMENTHEADER
       Missing data: 0.0%
       Duplicates: 0.0%
       Data types: 4 unique types

   choice_AMX_DONATION_HEADER
       Missing data: 0.4%
       Duplicates: 0.0%
       Data types: 2 unique types

   choice_AMX_DONATION_LINES
       Missing data: 5.3%
       Duplicates: 0.0%
       Data types: 3 unique types

   choice_RW_ORG
       Missing data: 3.7%
       Duplicates: 0.0%
       Data types: 4 unique types

   agency_DOCUMENTHEADER
       Missing data: 0.0%
       Duplicates: 0.0%
       Data types: 4 unique types

   agency_DOCUMENTLINES
       Missing data: 0.0%
       Duplicates: 0.0%
       Data types: 4 unique types

   agency_RW_ORG
       Missing data: 3.6%
       Duplicates: 0.0%
       Data types: 4 unique types

   unified_documentheader
       Missing data: 0.0%
       Duplicates: 0.0%
       Data types: 4 unique types

   unified_donation_header
       Missing data: 0.0%
       Duplicates: 0.0%
       Data types: 2 unique types

   unified_rw_org
       Missing data: 0.0%
       Duplicates: 0.0%
       Data types: 4 unique types

 ETL summary saved to: notebook_output/etl_summary.json

 ETL Pipeline Complete! Ready for Exploratory Data Analysis.

## 4. Exploratory Data Analysis (EDA)

Comprehensive statistical analysis of the processed HungerHub data to understand patterns, relationships, and insights.

### EDA Strategy:
1. **Univariate Analysis**: Individual variable distributions and statistics
2. **Bivariate Analysis**: Relationships between pairs of variables
3. **Multivariate Analysis**: Complex relationships across multiple variables
4. **Visual Analysis**: Interactive charts and plots using Plotly Express
5. **Statistical Testing**: Hypothesis testing and correlation analysis

### Key Questions to Answer:
- What are the distributions of key metrics (donations, orders, organizations)?
- How do food assistance patterns vary by geography and time?
- What relationships exist between donor behavior and recipient needs?
- Are there seasonal or cyclical patterns in the data?
- What anomalies or outliers require attention?

In [60]:
# EDA Helper Functions and Setup
class HungerHubEDA:
    """Exploratory Data Analysis toolkit for HungerHub data"""
    
    def __init__(self, datasets, output_dir):
        self.datasets = datasets
        self.output_dir = Path(output_dir)
        self.viz_dir = self.output_dir / 'visualizations'
        self.viz_dir.mkdir(exist_ok=True)
        
        self.insights = []
        self.summary_stats = {}
    
    def add_insight(self, category, insight):
        """Add an analytical insight"""
        self.insights.append({
            'category': category,
            'insight': insight,
            'timestamp': datetime.now().isoformat()
        })
        print(f" {category}: {insight}")
    
    def get_dataset_overview(self):
        """Get comprehensive overview of all datasets"""
        overview = {}
        
        print(" Dataset Overview Analysis")
        print("=" * 40)
        
        for name, df in self.datasets.items():
            if len(df) > 0:
                stats = {
                    'rows': len(df),
                    'columns': len(df.columns),
                    'memory_mb': df.memory_usage(deep=True).sum() / 1024**2,
                    'missing_cells': df.isnull().sum().sum(),
                    'missing_percentage': (df.isnull().sum().sum() / (len(df) * len(df.columns))) * 100,
                    'numeric_columns': len(df.select_dtypes(include=[np.number]).columns),
                    'categorical_columns': len(df.select_dtypes(include=['object']).columns),
                    'datetime_columns': len(df.select_dtypes(include=['datetime64']).columns)
                }
                
                overview[name] = stats
                
                print(f"\n {name}:")
                print(f"   Dimensions: {stats['rows']:,} rows × {stats['columns']} columns")
                print(f"   Memory usage: {stats['memory_mb']:.1f} MB")
                print(f"   Missing data: {stats['missing_cells']:,} cells ({stats['missing_percentage']:.1f}%)")
                print(f"   Data types: {stats['numeric_columns']} numeric, {stats['categorical_columns']} categorical, {stats['datetime_columns']} datetime")
                
                # Add insights based on the data characteristics
                if stats['missing_percentage'] > 20:
                    self.add_insight('Data Quality', f"{name} has {stats['missing_percentage']:.1f}% missing data - requires careful handling")
                
                if stats['rows'] > 10000:
                    self.add_insight('Scale', f"{name} is a large dataset with {stats['rows']:,} records - suitable for robust analysis")
        
        self.summary_stats['overview'] = overview
        return overview
    
    def analyze_numeric_columns(self, df, dataset_name, max_columns=10):
        """Comprehensive analysis of numeric columns"""
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        
        if len(numeric_cols) == 0:
            print(f"   No numeric columns found in {dataset_name}")
            return None
        
        # Limit analysis to prevent overwhelming output
        cols_to_analyze = numeric_cols[:max_columns]
        
        print(f"\n Numeric Analysis: {dataset_name} ({len(cols_to_analyze)} columns)")
        print("-" * 50)
        
        numeric_summary = df[cols_to_analyze].describe()
        
        # Enhanced statistics
        for col in cols_to_analyze:
            if df[col].count() > 0:  # Only analyze non-empty columns
                series = df[col].dropna()
                
                stats = {
                    'count': len(series),
                    'mean': series.mean(),
                    'median': series.median(),
                    'std': series.std(),
                    'min': series.min(),
                    'max': series.max(),
                    'skewness': series.skew() if len(series) > 1 else 0,
                    'zeros': (series == 0).sum(),
                    'unique_values': series.nunique()
                }
                
                print(f"\n   {col}:")
                print(f"     Count: {stats['count']:,} | Unique: {stats['unique_values']:,} | Zeros: {stats['zeros']:,}")
                print(f"     Mean: {stats['mean']:.2f} | Median: {stats['median']:.2f} | Std: {stats['std']:.2f}")
                print(f"     Range: [{stats['min']:.2f}, {stats['max']:.2f}] | Skewness: {stats['skewness']:.2f}")
                
                # Generate insights
                if abs(stats['skewness']) > 2:
                    skew_type = 'highly right-skewed' if stats['skewness'] > 0 else 'highly left-skewed'
                    self.add_insight('Distribution', f"{col} in {dataset_name} is {skew_type} (skewness: {stats['skewness']:.2f})")
                
                if stats['zeros'] / stats['count'] > 0.5:
                    self.add_insight('Data Pattern', f"{col} in {dataset_name} has {(stats['zeros']/stats['count']*100):.1f}% zero values")
        
        return numeric_summary
    
    def analyze_categorical_columns(self, df, dataset_name, max_categories=20):
        """Analysis of categorical columns"""
        categorical_cols = df.select_dtypes(include=['object']).columns
        
        if len(categorical_cols) == 0:
            print(f"   No categorical columns found in {dataset_name}")
            return None
        
        print(f"\n Categorical Analysis: {dataset_name} ({len(categorical_cols)} columns)")
        print("-" * 50)
        
        categorical_summary = {}
        
        for col in categorical_cols[:10]:  # Limit to first 10 categorical columns
            if df[col].count() > 0:
                value_counts = df[col].value_counts()
                
                stats = {
                    'unique_count': df[col].nunique(),
                    'most_common': value_counts.index[0] if len(value_counts) > 0 else None,
                    'most_common_count': value_counts.iloc[0] if len(value_counts) > 0 else 0,
                    'top_categories': value_counts.head().to_dict()
                }
                
                categorical_summary[col] = stats
                
                print(f"\n   {col}:")
                print(f"     Unique values: {stats['unique_count']:,}")
                print(f"     Most common: '{stats['most_common']}' ({stats['most_common_count']:,} times)")
                
                if stats['unique_count'] <= max_categories:
                    print(f"     Top categories: {dict(list(stats['top_categories'].items())[:5])}")
                
                # Generate insights
                uniqueness_ratio = stats['unique_count'] / len(df)
                if uniqueness_ratio > 0.9:
                    self.add_insight('Data Quality', f"{col} in {dataset_name} has very high uniqueness ({uniqueness_ratio:.1%}) - possibly an identifier")
                elif stats['most_common_count'] / len(df) > 0.8:
                    dominance_pct = stats['most_common_count'] / len(df) * 100
                    self.add_insight('Data Pattern', f"{col} in {dataset_name} is dominated by '{stats['most_common']}' ({dominance_pct:.1f}% of records)")
        
        return categorical_summary

# Initialize EDA toolkit
if 'all_datasets' in globals() and all_datasets:
    eda = HungerHubEDA(all_datasets, notebook_outputs['base'])
    print("✅ EDA toolkit initialized with processed datasets")
    print(f" Ready to analyze {len(all_datasets)} datasets")
else:
    print(" No processed datasets available for EDA")
    print(" Please run Section 3 (ETL Pipeline) first to generate processed datasets")

✅ EDA toolkit initialized with processed datasets
 Ready to analyze 10 datasets

### Dataset Quick Inspection

Examining the structure and content of each processed dataset before detailed analysis.

In [61]:
# Quick inspection of all processed datasets
if 'all_datasets' in globals() and all_datasets:
    print("Dataset Quick Inspection")
    print("=" * 40)
    print(f"Total datasets available: {len(all_datasets)}")
    print()
    
    for dataset_name in all_datasets.keys():
        print(f"Dataset: {dataset_name}")
        print(f"Shape: {all_datasets[dataset_name].shape}")
        print()
else:
    print("No datasets available for inspection")
    print("Please run Section 3 (ETL Pipeline) first")

Dataset Quick Inspection
========================================
Total datasets available: 10

Dataset: choice_DOCUMENTHEADER
Shape: (500, 46)

Dataset: choice_AMX_DONATION_HEADER
Shape: (500, 25)

Dataset: choice_AMX_DONATION_LINES
Shape: (500, 23)

Dataset: choice_RW_ORG
Shape: (500, 27)

Dataset: agency_DOCUMENTHEADER
Shape: (500, 19)

Dataset: agency_DOCUMENTLINES
Shape: (500, 16)

Dataset: agency_RW_ORG
Shape: (500, 28)

Dataset: unified_documentheader
Shape: (1000, 16)

Dataset: unified_donation_header
Shape: (500, 27)

Dataset: unified_rw_org
Shape: (1000, 28)

In [62]:
# Dataset inspection will be generated dynamically
if 'all_datasets' in globals() and all_datasets:
    for dataset_name, df in all_datasets.items():
        print(f"\n{'='*60}")
        print(f"DATASET: {dataset_name.upper()}")
        print(f"{'='*60}")
        
        print(f"\n1. FIRST 10 ROWS:")
        print("-" * 30)
        display(df.head(10))
        
        print(f"\n2. DATASET INFO:")
        print("-" * 30)
        df.info()
        
        print(f"\n3. DESCRIPTIVE STATISTICS (ALL COLUMNS):")
        print("-" * 30)
        try:
            desc_stats = df.describe(include='all').T
            display(desc_stats)
        except Exception as e:
            print(f"Error generating descriptive statistics: {e}")
            # Fallback to basic describe
            try:
                display(df.describe().T)
            except:
                print("Unable to generate descriptive statistics for this dataset")
        
        print(f"\n" + "="*60 + "\n")
else:
    print("❌ No datasets available for detailed inspection")

============================================================
DATASET: CHOICE_DOCUMENTHEADER
============================================================

1. FIRST 10 ROWS:
------------------------------

,documentid,refnumber,sourceorg,userid,status,createddate,expirydate,prop1,prop2,prop3,prop4,prop5,prop6,prop7,prop8,prop9,prop10,prop11,prop12,prop13,prop15,notify,username,useremail,sourceorgname,domainid,domainname,prop16,prop18,prop19,prop20,prop21,prop22,prop23,prop24,prop25,prop26,prop27,prop28,prop29,prop30,prop31,prop32,prop33,prop34,prop35
0,L167066,L167066,ConAgraFoods,Unknown,3,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171107,Unknown,YD033,No,1,11/3/2017,Unknown,11/10/2017,Donor will deliver,Pallet Exchange,-2000,No,Truck Load,CSWANN,Ease on down the road Dan added shelf life and extenstion and storage as refrigerated for the 1...,202.0,Unknown,Unknown,ConAgra Consolidated,Unknown,Unknown,877-344-8070,cswann@feedingamerica.org,ConAgra,Kanesha Moss,1500 N Central Ave,Humboldt,TN,38343-1798,(859) 653-8989,Unknown,Kanesha.Moss@conagrafoods.com,0,No,-100,Unknown,Chicago,IL,60601,0
1,L167067,L167067,ConAgraFoods,Unknown,3,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171107,Unknown,YD033 (Load 2),No,1,11/3/2017,Unknown,11/10/2017,Donor will deliver,Pallet Exchange,-2000,No,Truck Load,CSWANN,Ease on down the road Dan added shelf life and extenstion and storage as refrigerated for the 1...,202.0,Unknown,Unknown,ConAgra Consolidated,Unknown,Unknown,877-344-8070,cswann@feedingamerica.org,ConAgra,Kanesha Moss,1500 N Central Ave,Humboldt,TN,38343-1798,(859) 653-8989,Unknown,Kanesha.Moss@conagrafoods.com,0,No,-33,Unknown,Chicago,IL,60601,0
2,ID_8709,ML8709,Chicago,USER_Z0007742,3,1970-01-01 00:00:00.020171106,1970-01-01 00:00:00.020171107,Chicago1,Soup jb,Yes,1,11/8/2017,C1234,11/15/2017,Member will pick up,Pallets - No Exchange,-100,No,Less Than Truck Load,SBARNES,Pick this load up ASAP please!,303.0,Mike Loeffl,mloeffl@feedingamerica.org,Greater Chicago Food Depository,DOM_00000001,DEFAULT,877-344-8070,sbarnes@feedingamerica.org,Greater Chicago Food Depository,Mike Loeffl,4100 West Ann Lurie Place,Chicago,IL,60632,(773) 247-3663,(773) 247-4232,mloeffl@chicago.org,0,Yes,1000,No Refers,Chicago,IL,60601,0
3,L167081,L167081,Kellogg,Unknown,3,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171107,Single LineChoice,AA YD022,No,2,10/10/2018,1,10/17/2018,Member will pick up,Slip Sheets,-2000,No,Truck Load,MLOEFFL,PO 498616 and 498162,202.0,Unknown,Unknown,Kellogg Company,Unknown,Unknown,877-344-8070,mloeffl@feedingamerica.org,Kellogg Montgomery DSD 2426,Gary Geisking,780 Industrial Park Blvd Ste F,Montgomery,AL,36117-5526,317-897-1726,Unknown,gary@hoosierwarehouses.com,0,No,-1800,FOR FULL TLs YOU WILL NEED A RELEASE NUMBER. YOU MUST CALL AT LEAST 48 HOURS AHEAD OF TIME TO M...,Chicago,IL,60601,0
4,L167082,L167082,Kellogg,Unknown,3,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171107,Single LineChoice,AA YD022 Rapid,Yes,1,10/10/2018,1,10/17/2018,Member will pick up,Slip Sheets,-2000,No,Truck Load,MLOEFFL,PO 498616 and 498162,202.0,Unknown,Unknown,Kellogg Company,Unknown,Unknown,877-344-8070,mloeffl@feedingamerica.org,Kellogg Montgomery DSD 2426,Gary Geisking,780 Industrial Park Blvd Ste F,Montgomery,AL,36117-5526,317-897-1726,Unknown,gary@hoosierwarehouses.com,0,No,200,FOR FULL TLs YOU WILL NEED A RELEASE NUMBER. YOU MUST CALL AT LEAST 48 HOURS AHEAD OF TIME TO M...,Chicago,IL,60601,0
5,L167113,L167113,SeaShare,Unknown,3,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171113,Unknown,AA SFL010,Yes,1,11/12/2017,Unknown,11/17/2017,Member will pick up,Arrange with Warehouse,-2000,No,Truck Load,MLOEFFL,This is from the special instructions line in the upload file,202.0,Unknown,Unknown,SEASHARE,Unknown,Unknown,877-344-8070,mloeffl@feedingamerica.org,SeaShare Fish Hut 1,Tom Noonen,256 Fish Head Lane,Green Bay,WI,54302,258-898-2235,Unknown,tn@seashare.org,0,No,-2000,Member must submit receipt (via Choice) within 48 hrs of pickup stating the NET WEIGHT. Any diff...,Chicago,IL,60601,0
6,L167283,L167283,SeaShare,Unknown,3,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171215,16 APA - 1,Dan seafood 12 14 17,Yes,1,12/13/2017,16 APA - 1,12/20/2017,Member will pick up,Arrange with Warehouse,-2000,No,Truck Load,DLABONTE,VAP Cost is $ $0.28/lb. 1 truckload new production,202.0,Unknown,Unknown,SEASHARE,Unknown,Unknown,877-344-8070,dlabonte@feedingamerica.org,Anacortes (Trident),Brian Michaelson,1400 4th St,Anacortes,WA,98221-1532,360-293-7701,Unknown,brianmichaelson@tridentseafoods.com,0,No,1,Member must submit receipt (via Choice) within 48 hrs of pickup stating the NET WEIGHT. Any diff...,Chicago,IL,60601,0
7,BL17120050-01,BL17120050-01,Dole,Unknown,6,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171219,Mike Test 2,Mike Test 12/18,Yes,1,1/9/2017,Mike2,1/16/2017,Member will pick up,Pallets - No Exchange,-2000,No,Truck Load,MLOEFFL,This is from the special instructions line in the upload file,202.0,Unknown,Unknown,Dole Packaged Frozen Foods,Unknown,Unknown,877-344-8070,mloeffl@feedingamerica.org,Dole Warehouse 1A,Tom Thimble,44 Artwind St,Grayslake,IL,60030,345-445-5656,Unknown,tthimble@dole.com,1,No,0,Unknown,Chicago,IL,60601,0
8,BL1712005101,BL1712005101,Dole,Unknown,3,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020171219,Mike Test 2,AA ML Test 121817,Yes,1,1/10/2017,Mike2,1/17/2017,Member will pick up,Pallets - No Exchange,-2000,No,Truck Load,MLOEFFL,This is from the special instructions line in the upload file,202.0,Unknown,Unknown,Dole Packaged Frozen Foods,Unknown,Unknown,877-344-8070,mloeffl@feedingamerica.org,Dole Warehouse 1A,Tom Thimble,44 Artwind St,Grayslake,IL,60030,345-445-5656,Unknown,tthimble@dole.com,0,No,600,Unknown,Chicago,IL,60601,0
9,BL1801003401,BL1801003401,Kraft,Unknown,6,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020180116,7533_42429_HW,snacks,No,1,3/2/2016,Unknown,3/9/2016,Member will pick up,CHEP Pallets,-2000,No,Truck Load,SBARNES,"0282 - Fill with Distressed Product, 0255 - Code Date to Fill, NOTE: None",202.0,Unknown,Unknown,Kraft Heinz,Unknown,Unknown,877-344-8070,sbarnes@feedingamerica.org,7533 SO CAL Dry Mixing Center,Olga Lopez,17789 Harvill Ave,Perris,CA,92570-9424,951-436-7109,Unknown,TBD,1,No,0,OUT BY DATE IS WHEN KRAFT WANTS PICKED UP.CARRIERS MUST CALL FOR APPT. 48 HOURS IN ADVANCE.*NOTE...,Chicago,IL,60601,0

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 46 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   documentid     500 non-null    object
 1   refnumber      500 non-null    object
 2   sourceorg      500 non-null    object
 3   userid         500 non-null    object
 4   status         500 non-null    int64
 5   createddate    500 non-null    datetime64[ns]
 6   expirydate     500 non-null    datetime64[ns]
 7   prop1          500 non-null    object
 8   prop2          500 non-null    object
 9   prop3          500 non-null    object
 10  prop4          500 non-null    object
 11  prop5          500 non-null    object
 12  prop6          500 non-null    object
 13  prop7          500 non-null    object
 14  prop8          500 non-null    object
 15  prop9          500 non-null    object
 16  prop10         500 non-null    object
 17  prop11         500 non-null    object
 18  prop12         500 non-null    object
 19  prop13         500 non-null    object
 20  prop15         500 non-null    object
 21  notify         500 non-null    float64
 22  username       500 non-null    object
 23  useremail      500 non-null    object
 24  sourceorgname  500 non-null    object
 25  domainid       500 non-null    object
 26  domainname     500 non-null    object
 27  prop16         500 non-null    object
 28  prop18         500 non-null    object
 29  prop19         500 non-null    object
 30  prop20         500 non-null    object
 31  prop21         500 non-null    object
 32  prop22         500 non-null    object
 33  prop23         500 non-null    object
 34  prop24         500 non-null    object
 35  prop25         500 non-null    object
 36  prop26         500 non-null    object
 37  prop27         500 non-null    object
 38  prop28         500 non-null    object
 39  prop29         500 non-null    object
 40  prop30         500 non-null    object
 41  prop31         500 non-null    object
 42  prop32         500 non-null    object
 43  prop33         500 non-null    object
 44  prop34         500 non-null    object
 45  prop35         500 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(1), object(42)
memory usage: 179.8+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
documentid,500,500,ML10289,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
refnumber,500,500,ML10289,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sourceorg,500,105,ConAgraFoods,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
userid,500,9,Unknown,440,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,500.0,NaN,NaN,NaN,6.444,-1.0,3.0,6.0,8.0,100.0,11.489599
createddate,500,NaN,NaN,NaN,1970-01-01 00:00:00.020219421,1970-01-01 00:00:00.020170823,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020250710,NaN
expirydate,500,NaN,NaN,NaN,1970-01-01 00:00:00.020198372,1970-01-01 00:00:00.020170804,1970-01-01 00:00:00.020180311,1970-01-01 00:00:00.020181115,1970-01-01 00:00:00.020220210,1970-01-01 00:00:00.020250710,NaN
prop1,500,227,Unknown,195,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop2,500,402,Unknown,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop3,500,3,No,291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop4,500,14,0,283,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop5,500,247,1/9/2017,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop6,500,142,Unknown,181,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop7,500,246,1/16/2017,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop8,500,5,Member will pick up,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop9,500,9,Arrange with Warehouse,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop10,500,24,-2000,335,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop11,500,2,No,495,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop12,500,3,Truck Load,311,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop13,500,30,DLABONTE,153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop15,500,180,Unknown,190,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notify,500.0,NaN,NaN,NaN,214.538,0.0,202.0,202.0,202.0,1618.0,141.763077
username,500,6,Unknown,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
useremail,500,6,Unknown,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sourceorgname,500,117,Kellogg Company,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
domainid,500,2,Unknown,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
domainname,500,2,Unknown,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop16,500,15,877-344-8070,471,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop18,500,20,dlabonte@feedingamerica.org,154,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop19,500,248,Americold (formerly Versacold Logistics),24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop20,500,266,MISTY HUGGINS,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop21,500,253,1313 Samuels Ave,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop22,500,190,Fort Worth,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop23,500,42,IL,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop24,500,234,76102-1130,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop25,500,244,Unknown,42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop26,500,36,Unknown,428,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop27,500,232,Unknown,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop28,500,13,0,342,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop29,500,3,No,413,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop30,500,82,0,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop31,500,46,Unknown,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop32,500,12,Chicago,475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop33,500,12,IL,472,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop34,500,14,60601,472,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop35,500,2,0,471,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================


============================================================
DATASET: CHOICE_AMX_DONATION_HEADER
============================================================

1. FIRST 10 ROWS:
------------------------------

,donationnumber,donorid,donorname,dcontactname,dcontactphone,dcontactfax,donorreferencenumber,donationdate,releasedate,dcontactemail,rcontactname,rcontactphone,rcontactemail,wcontactname,warehousename,wcontactaddress,wcontactcitystatezip,wcontactphone,releasenumber,shipmentmethod,stagingmethod,deliveryinstructions,status,outbydate,wcontactemail
0,WD17110017,Kellogg,Kellogg,Caren Smith,(269) 961-2000,Unknown,Choice bid multi line donation,2017-11-03,2017-11-03,csmith@kellogg.com,Eric Pettis,(269) 961-2000,osd.cpu@kellogg.com,Chris Loeffl,1759 Peacock - Bolingbrook,1100 Remington Blvd,"Bolingbrook, IL 60490-3308",(708) 566-9696,1,PICKUP,ARRANGE,Unknown,Acknowledged,2017-11-10,Cloeffl@gmail.com
1,WD17100019,Kraft,Kraft,Fred Smith 1,3121112222,Unknown,Unknown,2017-10-25,2017-10-25,fsmith1@kraft.com,Fred Smith 1,3121112222,fsmith1@kraft.com,Fred Smith 2,Kraft ML Test 2 12282016,Big Cheese BLVD,"Madison, WI 53705",800-456-8787,Unknown,PICKUP,ARRANGE,Please call Warehouse contact for pick up appointment ML,Acknowledged,2017-11-01,fsmith2@kraft.com
2,WD17110011,SeaShare,SeaShare,Ron Gister,225-5658-89,Unknown,ML SeaFod Test 1,2017-11-01,2017-12-25,rg@seashare.org,Ron Gister,225-5658-89,rg@seashare.org,Tom Noonen,SeaShare Fish Hut 1,256 Fish Head Lane,"Green Bay, WI 54302",258-898-2235,ML Seafood Test 1,PICKUP,ARRANGE,This is from the special instructions line in the upload file,Acknowledged,2018-01-02,tn@seashare.org
3,WD17110020,ConAgraFoods,ConAgraFoods,Caesar Amador,312-717-5822,Unknown,Unknown,2017-11-03,2017-11-03,caesar.amador@conagrafoods.com,Dawn Knotts,(312) 717-5822,dawn.knotts@conagrafoods.com,Kanesha Moss,ConAgra,1500 N Central Ave,"Humboldt, TN 38343-1798",(859) 653-8989,Unknown,DELIVER,PALLET EXC,Ease on down the road Dan added shelf life and extenstion and storage as refrigerated for the 1...,Acknowledged,2017-11-10,Kanesha.Moss@conagrafoods.com
4,WD17110019,Kellogg,Kellogg,Caren Smith,(269) 961-2000,Unknown,Direct Offer Multi line donation,2017-11-03,2017-11-03,csmith@kellogg.com,Eric Pettis,(269) 961-2000,osd.cpu@kellogg.com,Chris Loeffl,1759 Peacock - Bolingbrook,1100 Remington Blvd,"Bolingbrook, IL 60490-3308",(708) 566-9696,1,PICKUP,ARRANGE,Unknown,Acknowledged,2017-11-10,Cloeffl@gmail.com
5,WD17110031,ConAgraFoods,ConAgraFoods,Caesar Amador,312-717-5822,Unknown,Unknown,2017-11-03,2017-11-03,caesar.amador@conagrafoods.com,Dawn Knotts,(312) 717-5822,dawn.knotts@conagrafoods.com,Kanesha Moss,ConAgra,1500 N Central Ave,"Humboldt, TN 38343-1798",(859) 653-8989,Unknown,DELIVER,PALLET EXC,Ease on down the road Dan added shelf life and extenstion and storage as refrigerated for the 1...,Acknowledged,2017-11-10,Kanesha.Moss@conagrafoods.com
6,WD17110021,ConAgraFoods,ConAgraFoods,Caesar Amador,312-717-5822,Unknown,Direct Offer Single line donation,2017-11-03,2017-08-03,caesar.amador@conagrafoods.com,Dawn Knotts,(312) 717-5822,dawn.knotts@conagrafoods.com,Kanesha Moss,ConAgra,1500 N Central Ave,"Humboldt, TN 38343-1798",(859) 653-8989,Unknown,DELIVER,PALLET EXC,Ease on down the road,Acknowledged,2017-08-10,Kanesha.Moss@conagrafoods.com
7,WD17110022,ConAgraFoods,ConAgraFoods,Caesar Amador,312-717-5822,Unknown,Direct Offer Multi line donation,2017-11-03,2017-11-03,caesar.amador@conagrafoods.com,Dawn Knotts,(312) 717-5822,dawn.knotts@conagrafoods.com,Kanesha Moss,ConAgra,1500 N Central Ave,"Humboldt, TN 38343-1798",(859) 653-8989,Unknown,DELIVER,PALLET EXC,Ease on down the road,Acknowledged,2017-11-10,Kanesha.Moss@conagrafoods.com
8,WD17120021,Kellogg,Kellogg,Caren Smith,(773) 449-6969,Unknown,Disaster,2017-12-14,2017-12-14,csmith@kellogg.com,Eric Pettis,(773) 449-6969,osd.cpu@kellogg.com,Gary Geisking,Kelloggs Denver DC 2483,4740 Florence St,"Denver, CO 80238-2413",317-897-1726,Disaster,PICKUP,SLIP SHEET,PO 498616 and 498162,Acknowledged,2017-12-21,gary@hoosierwarehouses.com
9,WD17110049,Kellogg,Kellogg,Caren Smith,(269) 961-2000,Unknown,Choice bid multi line donation,2017-11-03,2017-11-03,csmith@kellogg.com,Eric Pettis,(269) 961-2000,osd.cpu@kellogg.com,Chris Loeffl,1759 Peacock - Bolingbrook,1100 Remington Blvd,"Bolingbrook, IL 60490-3308",(708) 566-9696,1,PICKUP,ARRANGE,Unknown,Acknowledged,2017-11-10,Cloeffl@gmail.com

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   donationnumber        500 non-null    object
 1   donorid               500 non-null    object
 2   donorname             500 non-null    object
 3   dcontactname          500 non-null    object
 4   dcontactphone         500 non-null    object
 5   dcontactfax           500 non-null    object
 6   donorreferencenumber  500 non-null    object
 7   donationdate          492 non-null    datetime64[ns]
 8   releasedate           489 non-null    datetime64[ns]
 9   dcontactemail         500 non-null    object
 10  rcontactname          500 non-null    object
 11  rcontactphone         500 non-null    object
 12  rcontactemail         500 non-null    object
 13  wcontactname          500 non-null    object
 14  warehousename         500 non-null    object
 15  wcontactaddress       500 non-null    object
 16  wcontactcitystatezip  500 non-null    object
 17  wcontactphone         500 non-null    object
 18  releasenumber         500 non-null    object
 19  shipmentmethod        500 non-null    object
 20  stagingmethod         500 non-null    object
 21  deliveryinstructions  500 non-null    object
 22  status                500 non-null    object
 23  outbydate             468 non-null    datetime64[ns]
 24  wcontactemail         500 non-null    object
dtypes: datetime64[ns](3), object(22)
memory usage: 97.8+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max
donationnumber,500,500,WD24090027,1,NaN,NaN,NaN,NaN,NaN,NaN
donorid,500,84,ConAgraFoods,63,NaN,NaN,NaN,NaN,NaN,NaN
donorname,500,84,ConAgraFoods,63,NaN,NaN,NaN,NaN,NaN,NaN
dcontactname,500,213,Mary Harmon,18,NaN,NaN,NaN,NaN,NaN,NaN
dcontactphone,500,202,Unknown,58,NaN,NaN,NaN,NaN,NaN,NaN
dcontactfax,500,30,Unknown,441,NaN,NaN,NaN,NaN,NaN,NaN
donorreferencenumber,500,228,Unknown,217,NaN,NaN,NaN,NaN,NaN,NaN
donationdate,492,NaN,NaN,NaN,2020-04-02 14:40:58.536585472,2017-01-23 00:00:00,2018-03-21 18:00:00,2019-04-22 00:00:00,2022-05-18 00:00:00,2025-07-10 00:00:00
releasedate,489,NaN,NaN,NaN,2019-12-06 04:54:28.711656448,2003-01-29 00:00:00,2018-02-08 00:00:00,2019-03-29 00:00:00,2022-04-01 00:00:00,2025-07-10 00:00:00
dcontactemail,500,211,Remarketing@kellogg.com,30,NaN,NaN,NaN,NaN,NaN,NaN
rcontactname,500,183,Unknown,38,NaN,NaN,NaN,NaN,NaN,NaN
rcontactphone,500,176,Unknown,76,NaN,NaN,NaN,NaN,NaN,NaN
rcontactemail,500,177,Unknown,45,NaN,NaN,NaN,NaN,NaN,NaN
wcontactname,500,267,Tom Thimble,21,NaN,NaN,NaN,NaN,NaN,NaN
warehousename,500,249,Dole Warehouse 1A,22,NaN,NaN,NaN,NaN,NaN,NaN
wcontactaddress,500,243,44 Artwind St,22,NaN,NaN,NaN,NaN,NaN,NaN
wcontactcitystatezip,500,242,"Grayslake, IL 60030",22,NaN,NaN,NaN,NaN,NaN,NaN
wcontactphone,500,244,Unknown,48,NaN,NaN,NaN,NaN,NaN,NaN
releasenumber,500,174,Unknown,171,NaN,NaN,NaN,NaN,NaN,NaN
shipmentmethod,500,6,PICKUP,419,NaN,NaN,NaN,NaN,NaN,NaN
stagingmethod,500,8,ARRANGE,219,NaN,NaN,NaN,NaN,NaN,NaN
deliveryinstructions,500,190,Unknown,167,NaN,NaN,NaN,NaN,NaN,NaN
status,500,8,Acknowledged,374,NaN,NaN,NaN,NaN,NaN,NaN
outbydate,468,NaN,NaN,NaN,2019-11-16 08:18:27.692307712,2003-03-07 00:00:00,2018-02-05 00:00:00,2019-02-10 00:00:00,2021-12-29 12:00:00,2025-09-30 00:00:00
wcontactemail,500,238,Unknown,68,NaN,NaN,NaN,NaN,NaN,NaN

============================================================


============================================================
DATASET: CHOICE_AMX_DONATION_LINES
============================================================

1. FIRST 10 ROWS:
------------------------------

,donationnumber,itemnumber,itemdescription,donationreason,pack,size_,sizeuom,packagingtype,unitofmeasure,quantity,quantityperpallet,totalpallets,grossweight,totalgrossweight,netweight,storagerequirement,manufacturedate,expirationdate,shelflife,extension,usebydate,status,magrefnumber
0,WD18020051,Chk63F321,BNLS BRST LRG SKNLS,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Case,10.0,50.0,0.2,20.0,200.0,432.0,FROZEN,2017-10-20,NaT,Unknown,Unknown,2017-10-20,Unknown,172000
1,WD18020051,Chk63F543,BNIN BRST LRG SKNON,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Case,10.0,50.0,0.2,25.0,250.0,432.0,FROZEN,2018-10-20,NaT,Unknown,Unknown,2018-10-20,Unknown,173000
2,WD18020051,Chk636T3,SML WING CSE,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Carton,10.0,50.0,0.2,30.0,300.0,432.0,FROZEN,2018-10-20,NaT,Unknown,Unknown,2018-10-20,Unknown,174000
3,WD18020051,Chk63F321,BNLS BRST LRG SKNLS,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Case,10.0,50.0,0.2,20.0,200.0,432.0,FROZEN,2017-10-20,NaT,Unknown,Unknown,2017-10-20,Unknown,175000
4,WD18020051,Chk63F543,BNIN BRST LRG SKNON,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Case,10.0,50.0,0.2,25.0,250.0,432.0,FROZEN,2018-10-20,NaT,Unknown,Unknown,2018-10-20,Unknown,176000
5,WD18020051,Chk636T3,SML WING CSE,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Carton,10.0,50.0,0.2,30.0,300.0,432.0,FROZEN,2018-10-20,NaT,Unknown,Unknown,2018-10-20,Unknown,177000
6,WD18020051,Chk63F321,BNLS BRST LRG SKNLS,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Case,10.0,50.0,0.2,20.0,200.0,432.0,FROZEN,2017-10-20,NaT,Unknown,Unknown,2017-10-20,Unknown,178000
7,WD18020051,Chk63F543,BNIN BRST LRG SKNON,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Case,10.0,50.0,0.2,25.0,250.0,432.0,FROZEN,2018-10-20,NaT,Unknown,Unknown,2018-10-20,Unknown,179000
8,WD18020051,Chk636T3,SML WING CSE,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Carton,10.0,50.0,0.2,30.0,300.0,432.0,FROZEN,2018-10-20,NaT,Unknown,Unknown,2018-10-20,Unknown,180000
9,WD18020051,Chk63F321,BNLS BRST LRG SKNLS,Discontinued Item,/ Bag,Unknown,Bag,Unknown,Case,10.0,50.0,0.2,20.0,200.0,432.0,FROZEN,2017-10-20,NaT,Unknown,Unknown,2017-10-20,Unknown,181000

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   donationnumber      500 non-null    object
 1   itemnumber          500 non-null    object
 2   itemdescription     500 non-null    object
 3   donationreason      500 non-null    object
 4   pack                500 non-null    object
 5   size_               500 non-null    object
 6   sizeuom             500 non-null    object
 7   packagingtype       500 non-null    object
 8   unitofmeasure       500 non-null    object
 9   quantity            500 non-null    float64
 10  quantityperpallet   500 non-null    float64
 11  totalpallets        500 non-null    float64
 12  grossweight         500 non-null    float64
 13  totalgrossweight    500 non-null    float64
 14  netweight           500 non-null    float64
 15  storagerequirement  500 non-null    object
 16  manufacturedate     336 non-null    datetime64[ns]
 17  expirationdate      75 non-null     datetime64[ns]
 18  shelflife           500 non-null    object
 19  extension           500 non-null    object
 20  usebydate           480 non-null    datetime64[ns]
 21  status              500 non-null    object
 22  magrefnumber        500 non-null    object
dtypes: datetime64[ns](3), float64(6), object(14)
memory usage: 90.0+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
donationnumber,500,40,WD18020051,152,NaN,NaN,NaN,NaN,NaN,NaN,NaN
itemnumber,500,98,Chk636T3,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
itemdescription,500,99,SML WING CSE,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN
donationreason,500,13,Discontinued Item,236,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pack,500,34,/ Bag,178,NaN,NaN,NaN,NaN,NaN,NaN,NaN
size_,500,19,Unknown,348,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sizeuom,500,12,Bag,178,NaN,NaN,NaN,NaN,NaN,NaN,NaN
packagingtype,500,10,Unknown,354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unitofmeasure,500,10,Case,306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
quantity,500.0,NaN,NaN,NaN,123.304,1.0,10.0,20.0,70.0,6001.0,360.473458
quantityperpallet,500.0,NaN,NaN,NaN,74.706,1.0,30.0,50.0,64.0,2231.0,199.300097
totalpallets,500.0,NaN,NaN,NaN,3.565503,0.0,0.2,0.666667,1.0,200.033333,11.802344
grossweight,500.0,NaN,NaN,NaN,152.536614,0.001,14.0,25.0,30.0,2231.0,480.212108
totalgrossweight,500.0,NaN,NaN,NaN,3014.607398,0.047,250.0,598.845,2044.0,60010.0,6979.863002
netweight,500.0,NaN,NaN,NaN,460.66097,2.191,432.0,432.0,432.0,2327.0,293.945231
storagerequirement,500,4,DRY,312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
manufacturedate,336,NaN,NaN,NaN,2017-05-03 16:21:25.714285824,1752-12-31 00:00:00,2017-10-20 00:00:00,2018-10-20 00:00:00,2018-10-20 00:00:00,2018-10-20 00:00:00,NaN
expirationdate,75,NaN,NaN,NaN,2014-11-17 14:43:12,1752-12-31 00:00:00,2018-03-04 00:00:00,2018-08-23 00:00:00,2018-09-26 12:00:00,2019-03-18 00:00:00,NaN
shelflife,500,15,Unknown,351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
extension,500,16,Unknown,320,NaN,NaN,NaN,NaN,NaN,NaN,NaN
usebydate,480,NaN,NaN,NaN,2018-05-14 02:27:00.000000256,2016-02-25 00:00:00,2018-01-16 18:00:00,2018-06-28 00:00:00,2018-10-20 00:00:00,2028-01-02 00:00:00,NaN
status,500,2,Acknowledged,272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
magrefnumber,500,154,1000,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================


============================================================
DATASET: CHOICE_RW_ORG
============================================================

1. FIRST 10 ROWS:
------------------------------

,org_id,entity_name,printable_name,status_flag,currency,currency_pattern,float_pattern,group_separator,group_size,decimal_char,language,country,time_zone,org_type,created_time,created_by,modified_time,modified_by,sys_flags,path,years_in_business,industry_val_num,annual_rev_vid,emp_count_vid,oca,parent_org_id,master_org_id
0,ORG_00004KEF,SanLeandro,San Leandro,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-06 05:09:58,USER_00004K1T,2003-05-06 05:10:49,USER_00004K1T,0,ORG_00000001.ORG_00004IFH.ORG_00004IFK.ORG_00004KEF,0.0,0.0,0.0,0.0,1,ORG_00004IFK,ORG_00004IFH
1,ORG_00004KH5,WinchesterPlant,WinchesterPlant,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-09 03:01:28,USER_00004K1T,2003-05-09 03:02:31,USER_00004K1T,0,ORG_00000001.ORG_00004IFH.ORG_00004IFK.ORG_00004KH5,0.0,0.0,0.0,0.0,1,ORG_00004IFK,ORG_00004IFH
2,ORG_00004KH6,Albuquerque,Albuquerque,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-18 17:14:51,USER_00004K1T,2009-04-24 15:14:39,USER_00004SE9,0,ORG_00000001.ORG_00004IFI.ORG_00004KH6,0.0,0.0,0.0,0.0,5,ORG_00004IFI,ORG_00004IFI
3,ORG_00004KH7,MemphisZC,MemphisZC,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-18 17:29:09,USER_00004K1T,2003-05-18 17:31:33,USER_00004K1T,0,ORG_00000001.ORG_00004IFI.ORG_00004KH7,0.0,0.0,0.0,0.0,2,ORG_00004IFI,ORG_00004IFI
4,ORG_00004KH8,FtMeyersZC,FtMeyersZC,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-18 17:37:20,USER_00004K1T,2006-01-05 00:27:12,USER_00004Q9N,0,ORG_00000001.ORG_00004IFI.ORG_00004KH8,0.0,0.0,0.0,0.0,5,ORG_00004IFI,ORG_00004IFI
5,ORG_00004KH9,Fargo,Fargo,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-18 20:46:17,USER_00004K1T,2006-01-05 00:19:25,USER_00004Q9N,0,ORG_00000001.ORG_00004IFI.ORG_00004KH9,0.0,0.0,0.0,0.0,3,ORG_00004IFI,ORG_00004IFI
6,ORG_00004KHA,Memphis,Mid-South Food Bank,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-18 20:54:13,USER_00004K1T,2008-12-02 14:20:39,USER_00004SE9,0,ORG_00000001.ORG_00004IFI.ORG_00004KHA,0.0,0.0,0.0,0.0,7,ORG_00004IFI,ORG_00004IFI
7,ORG_00004KHB,Pennsauken,Pennsauken,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-18 20:57:48,USER_00004K1T,2006-01-05 23:53:35,USER_00004Q9N,0,ORG_00000001.ORG_00004IFI.ORG_00004KHB,0.0,0.0,0.0,0.0,3,ORG_00004IFI,ORG_00004IFI
8,ORG_00004KHC,MemphisZD,MemphisZD,I,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-19 12:27:45,USER_00004K1T,2006-01-05 23:15:08,USER_00004Q9N,0,ORG_00000001.ORG_00004IFI.ORG_00004KHC,0.0,0.0,0.0,0.0,3,ORG_00004IFI,ORG_00004IFI
9,ORG_00004KK9,TestAffiliate6,Test Affiliate6,A,USD,"*###,##0.00","###,##0.###",",",3,.,en,US,NaT,S,2003-05-22 20:21:44,USER_00004K1T,2003-05-22 20:22:44,USER_00004K1T,0,ORG_00000001.ORG_00004IFI.ORG_00004KK9,0.0,0.0,0.0,0.0,2,ORG_00004IFI,ORG_00004IFI

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   org_id             500 non-null    object
 1   entity_name        500 non-null    object
 2   printable_name     500 non-null    object
 3   status_flag        500 non-null    object
 4   currency           500 non-null    object
 5   currency_pattern   500 non-null    object
 6   float_pattern      500 non-null    object
 7   group_separator    500 non-null    object
 8   group_size         500 non-null    int64
 9   decimal_char       500 non-null    object
 10  language           500 non-null    object
 11  country            500 non-null    object
 12  time_zone          0 non-null      datetime64[ns]
 13  org_type           500 non-null    object
 14  created_time       500 non-null    datetime64[ns]
 15  created_by         500 non-null    object
 16  modified_time      500 non-null    datetime64[ns]
 17  modified_by        500 non-null    object
 18  sys_flags          500 non-null    int64
 19  path               500 non-null    object
 20  years_in_business  500 non-null    float64
 21  industry_val_num   500 non-null    float64
 22  annual_rev_vid     500 non-null    object
 23  emp_count_vid      500 non-null    object
 24  oca                500 non-null    int64
 25  parent_org_id      500 non-null    object
 26  master_org_id      500 non-null    object
dtypes: datetime64[ns](3), float64(2), int64(3), object(19)
memory usage: 105.6+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
org_id,500,500,ORG_00004NB1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entity_name,500,500,Ottumwa,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
printable_name,500,374,Unknown,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status_flag,500,2,A,436,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency,500,1,USD,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency_pattern,500,1,"*###,##0.00",500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
float_pattern,500,1,"###,##0.###",500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_separator,500,1,",",500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_size,500.0,NaN,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,0.0
decimal_char,500,1,.,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
language,500,1,en,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,500,1,US,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time_zone,0,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
org_type,500,3,S,487,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_time,500,NaN,NaN,NaN,2005-08-17 03:45:12.020000,2001-01-01 00:00:00,2003-05-08 09:33:35.500000,2004-02-29 06:01:16.500000,2004-11-24 16:44:28.500000,2014-05-27 12:31:57,NaN
created_by,500,11,USER_00004IV5,243,NaN,NaN,NaN,NaN,NaN,NaN,NaN
modified_time,500,NaN,NaN,NaN,2006-09-25 04:12:20.052000,2001-08-23 00:50:46,2004-04-01 18:25:29.500000,2006-01-05 00:51:39.500000,2007-06-19 18:18:26.750000128,2014-05-27 12:31:57,NaN
modified_by,500,13,USER_00004Q9N,189,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sys_flags,500.0,NaN,NaN,NaN,0.002,0.0,0.0,0.0,0.0,1.0,0.044721
path,500,500,ORG_00000001.ORG_00004IFI.ORG_00004NB1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
years_in_business,500.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
industry_val_num,500.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
annual_rev_vid,500,1,0.0,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emp_count_vid,500,1,0.0,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oca,500.0,NaN,NaN,NaN,3.088,0.0,2.0,3.0,3.0,29.0,3.358991
parent_org_id,500,18,ORG_00004IFI,254,NaN,NaN,NaN,NaN,NaN,NaN,NaN
master_org_id,500,13,ORG_00004IFI,255,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================


============================================================
DATASET: AGENCY_DOCUMENTHEADER
============================================================

1. FIRST 10 ROWS:
------------------------------

,documentid,refnumber,sourceorg,userid,status,createddate,expirydate,modifieddate,warehouseid,prop1,notify,username,useremail,sourceorgname,domainid,domainname,archiveddate,isarchived,isae4order
0,003001-20477,01-20477,ORG_00004MML,Unknown,4,1970-01-01 00:00:00.020040601,1970-01-01 00:00:00.020040608,1970-01-01 00:00:00.020040601,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
1,003001-20371,01-20371,ORG_00004MG6,Unknown,4,1970-01-01 00:00:00.020040524,1970-01-01 00:00:00.020040524,1970-01-01 00:00:00.020040524,Unknown,9:00:00 AM,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
2,003001-20461,01-20461,ORG_00004MQ9,Unknown,4,1970-01-01 00:00:00.020040527,1970-01-01 00:00:00.020040608,1970-01-01 00:00:00.020040527,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
3,003001-20456,01-20456,ORG_00004MML,Unknown,4,1970-01-01 00:00:00.020040527,1970-01-01 00:00:00.020040608,1970-01-01 00:00:00.020040527,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
4,003001-20430,01-20430,ORG_00004MML,Unknown,4,1970-01-01 00:00:00.020040526,1970-01-01 00:00:00.020040608,1970-01-01 00:00:00.020040526,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
5,003001-20249,01-20249,ORG_00004MO1,Unknown,4,1970-01-01 00:00:00.020040517,1970-01-01 00:00:00.020040608,1970-01-01 00:00:00.020040517,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
6,003001-20409,01-20409,ORG_00004MIF,Unknown,4,1970-01-01 00:00:00.020040525,1970-01-01 00:00:00.020040608,1970-01-01 00:00:00.020040525,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
7,003001-20638,01-20638,0030PSF763,Unknown,7,1970-01-01 00:00:00.020040607,1970-01-01 00:00:00.020040607,1970-01-01 00:00:00.020040607,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
8,003001-20635,01-20635,0030PSF756,Unknown,4,1970-01-01 00:00:00.020040607,1970-01-01 00:00:00.020040607,1970-01-01 00:00:00.020040607,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0
9,003001-20641,01-20641,0030PSF772,Unknown,4,1970-01-01 00:00:00.020040607,1970-01-01 00:00:00.020040607,1970-01-01 00:00:00.020040607,Unknown,Unknown,101.0,Unknown,Unknown,Unknown,Unknown,Unknown,1970-01-01 00:00:00.020150713,1,0

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   documentid     500 non-null    object
 1   refnumber      500 non-null    object
 2   sourceorg      500 non-null    object
 3   userid         500 non-null    object
 4   status         500 non-null    int64
 5   createddate    500 non-null    datetime64[ns]
 6   expirydate     500 non-null    datetime64[ns]
 7   modifieddate   500 non-null    datetime64[ns]
 8   warehouseid    500 non-null    object
 9   prop1          500 non-null    object
 10  notify         500 non-null    float64
 11  username       500 non-null    object
 12  useremail      500 non-null    object
 13  sourceorgname  500 non-null    object
 14  domainid       500 non-null    object
 15  domainname     500 non-null    object
 16  archiveddate   500 non-null    datetime64[ns]
 17  isarchived     500 non-null    int64
 18  isae4order     500 non-null    int64
dtypes: datetime64[ns](4), float64(1), int64(3), object(11)
memory usage: 74.3+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
documentid,500,500,ID_505,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
refnumber,500,500,PO505,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sourceorg,500,314,ORG_00004N05,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
userid,500,38,Unknown,426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,500.0,NaN,NaN,NaN,6.496,1.0,4.0,4.0,7.0,100.0,11.284177
createddate,500,NaN,NaN,NaN,1970-01-01 00:00:00.020041822,1970-01-01 00:00:00.020040512,1970-01-01 00:00:00.020040727,1970-01-01 00:00:00.020040809,1970-01-01 00:00:00.020040907,1970-01-01 00:00:00.020120920,NaN
expirydate,500,NaN,NaN,NaN,1970-01-01 00:00:00.020001594,1970-01-01 00:00:00,1970-01-01 00:00:00.020040727,1970-01-01 00:00:00.020040818,1970-01-01 00:00:00.020040913,1970-01-01 00:00:00.020120921,NaN
modifieddate,500,NaN,NaN,NaN,1970-01-01 00:00:00.020041822,1970-01-01 00:00:00.020040512,1970-01-01 00:00:00.020040727,1970-01-01 00:00:00.020040809,1970-01-01 00:00:00.020040907,1970-01-01 00:00:00.020120920,NaN
warehouseid,500,29,Unknown,438,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop1,500,39,Unknown,196,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notify,500.0,NaN,NaN,NaN,100.604,0.0,101.0,101.0,101.0,301.0,15.582452
username,500,37,Unknown,426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
useremail,500,30,Unknown,426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sourceorgname,500,37,Unknown,426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
domainid,500,2,Unknown,432,NaN,NaN,NaN,NaN,NaN,NaN,NaN
domainname,500,2,Unknown,426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
archiveddate,500,NaN,NaN,NaN,1970-01-01 00:00:00.020150712,1970-01-01 00:00:00.020150609,1970-01-01 00:00:00.020150713,1970-01-01 00:00:00.020150713,1970-01-01 00:00:00.020150713,1970-01-01 00:00:00.020150813,NaN
isarchived,500.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,0.0
isae4order,500.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

============================================================


============================================================
DATASET: AGENCY_DOCUMENTLINES
============================================================

1. FIRST 10 ROWS:
------------------------------

,headerid,lineitemnumber,itemname,itemcode,donatedquantity,prop1,prop2,prop3,prop4,prop5,prop6,prop7,status,acceptedquantity,accepteddate,rprop1
0,003001-20740,2,Apples R 12/3 lbs D,10052,0.0,CS,1680,0,CASE,Unknown,Unknown,0,1,42.0,1970-01-01 00:00:00.020040610,0
1,003001-20740,3,Potatoes 1/10 lb Bag (D),10097,0.0,EA,2000,0,BAG,Unknown,Unknown,0,1,200.0,1970-01-01 00:00:00.020040610,0
2,003001-20740,4,Asst Punch 4/128oz (R),11874,0.0,CS,1900,0,CASE,Unknown,REF,0,1,50.0,1970-01-01 00:00:00.020040610,0
3,003001-20740,5,General Reclamation D Bulk Box,40004,0.0,LB,8039,0,BULKBOX,Unknown,Unknown,0,1,8039.0,1970-01-01 00:00:00.020040610,0
4,003001-20740,6,Orange Pumkin PoPs 24count,12303,0.0,CS,704,0,CASE,Unknown,DRY,0,1,32.0,1970-01-01 00:00:00.020040610,0
5,003001-20740,7,Waffle Cones 216/count (D),12272,0.0,CS,320,0,CASE,Unknown,DRY,0,1,20.0,1970-01-01 00:00:00.020040610,0
6,003001-20740,8,Boxed Canned Vegeies Bulk Box(D),50011,0.0,CS,1080,0,CASE,Unknown,Unknown,0,1,27.0,1970-01-01 00:00:00.020040610,0
7,003001-20740,9,USDA Non Fat Dry Milk 12/25.6oz (D),60126,0.0,CS,1188,0,CASE,Unknown,DRY,0,1,54.0,1970-01-01 00:00:00.020040610,0
8,003001-20738,2,Purchase Sliced Cheese 12/10oz(R),65794,0.0,CS,10,8.84,CASE,Unknown,REF,0,1,1.0,1970-01-01 00:00:00.020040610,8.84
9,003001-20738,3,Purchase Fruit Cocktail 24/15oz(D),65743,0.0,CS,26,14,CASE,Unknown,DRY,0,1,1.0,1970-01-01 00:00:00.020040610,14

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   headerid          500 non-null    object
 1   lineitemnumber    500 non-null    int64
 2   itemname          500 non-null    object
 3   itemcode          500 non-null    object
 4   donatedquantity   500 non-null    float64
 5   prop1             500 non-null    object
 6   prop2             500 non-null    object
 7   prop3             500 non-null    object
 8   prop4             500 non-null    object
 9   prop5             500 non-null    object
 10  prop6             500 non-null    object
 11  prop7             500 non-null    object
 12  status            500 non-null    object
 13  acceptedquantity  500 non-null    float64
 14  accepteddate      500 non-null    datetime64[ns]
 15  rprop1            500 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(12)
memory usage: 62.6+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
headerid,500,78,019537496,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lineitemnumber,500.0,NaN,NaN,NaN,9.706,1.0,4.0,6.0,11.0,43.0,9.172559
itemname,500,285,Milk 2% Reduced Fat 8oz,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
itemcode,500,287,82048,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
donatedquantity,500.0,NaN,NaN,NaN,0.74,0.0,0.0,0.0,0.0,30.0,3.413459
prop1,500,5,CASE,187,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop2,500,187,0,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop3,500,141,0,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop4,500,10,CASE,244,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop5,500,140,Unknown,236,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop6,500,6,DRY,274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop7,500,32,0,459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,500,3,1,466,NaN,NaN,NaN,NaN,NaN,NaN,NaN
acceptedquantity,500.0,NaN,NaN,NaN,95.7535,0.0,2.0,5.0,25.0,8039.0,622.051448
accepteddate,500,NaN,NaN,NaN,1970-01-01 00:00:00.020040733,1970-01-01 00:00:00.020040610,1970-01-01 00:00:00.020040624,1970-01-01 00:00:00.020040719,1970-01-01 00:00:00.020040719,1970-01-01 00:00:00.020060215,NaN
rprop1,500,231,0,118,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================


============================================================
DATASET: AGENCY_RW_ORG
============================================================

1. FIRST 10 ROWS:
------------------------------

,org_id,entity_name,printable_name,status_flag,e_mail,currency,currency_pattern,float_pattern,group_separator,group_size,decimal_char,language,country,time_zone,org_type,created_time,created_by,modified_time,modified_by,sys_flags,path,years_in_business,industry_val_num,annual_rev_vid,emp_count_vid,oca,parent_org_id,master_org_id
0,ORG_00004KA2,0014P459BOSR,Supp. Living YouthNFam/Durant,I,Unknown,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:36:09,USER_00000001,2002-08-16 18:09:15,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004K8D.ORG_00004KA2,0.0,0.0,0.0,0.0,8,ORG_00004K8D,ORG_00004J5D
1,ORG_00004KA3,0014468ADC,Logan Community Day Care,I,dbbeatt@dellepro.com,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:36:24,USER_00000001,2002-10-23 21:04:57,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KA3,0.0,0.0,0.0,0.0,15,ORG_00004J5D,ORG_00004J5D
2,ORG_00004KA4,0014P460ASN,Genesis Park Neighborhood Assn,I,GPNA@bellsouth.net,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:36:40,USER_00000001,2003-01-21 21:25:25,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004K8F.ORG_00004KA4,0.0,0.0,0.0,0.0,20,ORG_00004K8F,ORG_00004J5D
3,ORG_00004KA5,0014468BKC,Logan DC/Kids Cafe,I,Unknown,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:36:56,USER_00000001,2002-10-15 18:41:31,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KA5,0.0,0.0,0.0,0.0,15,ORG_00004J5D,ORG_00004J5D
4,ORG_00004KA6,0014469AOSR,The Gastonias Potters House,I,phrshs777@cs.com,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:37:32,USER_00000001,2003-01-16 18:36:07,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KA6,0.0,0.0,0.0,0.0,12,ORG_00004J5D,ORG_00004J5D
5,ORG_00004KA7,0014470AP,Belmont Foursquare Church,I,hopeatfoursquare@bellsouth.net,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:37:50,USER_00000001,2002-10-23 21:04:33,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KA7,0.0,0.0,0.0,0.0,15,ORG_00004J5D,ORG_00004J5D
6,ORG_00004KA8,0014471AR,Crossroads Rescue Mission,I,klinzey@crossroadsrescuemission.org,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:38:08,USER_00000001,2003-01-16 18:35:59,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KA8,0.0,0.0,0.0,0.0,12,ORG_00004J5D,ORG_00004J5D
7,ORG_00004KA9,0014472AOSR,Mt. Olive Adult Day Care,I,Unknown,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:38:26,USER_00000001,2002-11-01 12:09:48,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KA9,0.0,0.0,0.0,0.0,18,ORG_00004J5D,ORG_00004J5D
8,ORG_00004KAA,0014473AOSR,Higher Level Missions,I,kcc@acninc.net,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:38:43,USER_00000001,2002-08-16 18:09:23,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KAA,0.0,0.0,0.0,0.0,9,ORG_00004J5D,ORG_00004J5D
9,ORG_00004KAB,0014474AP,Wadesboro Area Comm. Out. Min.,I,cwagwhite@yahoo.com,USD,"*###,##0.00","###,##0.00",",",3,.,en,US,NaT,S,2002-08-13 20:39:01,USER_00000001,2002-11-07 12:55:44,USER_00000001,0,ORG_00000001.ORG_00004J5D.ORG_00004KAB,0.0,0.0,0.0,0.0,15,ORG_00004J5D,ORG_00004J5D

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   org_id             500 non-null    object
 1   entity_name        500 non-null    object
 2   printable_name     500 non-null    object
 3   status_flag        500 non-null    object
 4   e_mail             500 non-null    object
 5   currency           500 non-null    object
 6   currency_pattern   500 non-null    object
 7   float_pattern      500 non-null    object
 8   group_separator    500 non-null    object
 9   group_size         500 non-null    int64
 10  decimal_char       500 non-null    object
 11  language           500 non-null    object
 12  country            500 non-null    object
 13  time_zone          0 non-null      datetime64[ns]
 14  org_type           500 non-null    object
 15  created_time       500 non-null    datetime64[ns]
 16  created_by         500 non-null    object
 17  modified_time      500 non-null    datetime64[ns]
 18  modified_by        500 non-null    object
 19  sys_flags          500 non-null    int64
 20  path               500 non-null    object
 21  years_in_business  500 non-null    float64
 22  industry_val_num   500 non-null    float64
 23  annual_rev_vid     500 non-null    object
 24  emp_count_vid      500 non-null    object
 25  oca                500 non-null    int64
 26  parent_org_id      500 non-null    object
 27  master_org_id      500 non-null    object
dtypes: datetime64[ns](3), float64(2), int64(3), object(20)
memory usage: 109.5+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
org_id,500,500,ORG_00004JRL,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
entity_name,500,500,0014290BOSR,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
printable_name,500,487,Exceptions,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status_flag,500,2,I,471,NaN,NaN,NaN,NaN,NaN,NaN,NaN
e_mail,500,167,Unknown,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency,500,1,USD,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency_pattern,500,1,"*###,##0.00",500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
float_pattern,500,2,"###,##0.00",495,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_separator,500,1,",",500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_size,500.0,NaN,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,0.0
decimal_char,500,1,.,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
language,500,1,en,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,500,1,US,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
time_zone,0,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaT,NaT,NaN
org_type,500,3,S,495,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_time,500,NaN,NaN,NaN,2002-08-26 19:06:42.164000,2001-01-01 00:00:00,2002-08-13 18:03:10.250000,2002-08-13 18:35:09,2002-08-13 19:33:56,2024-05-02 00:00:00,NaN
created_by,500,1,USER_00000001,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
modified_time,500,NaN,NaN,NaN,2002-11-15 06:38:32.910000,2001-01-01 00:00:00,2002-08-16 18:09:17.250000,2002-10-26 11:42:51,2003-01-09 22:01:02,2024-05-02 00:00:00,NaN
modified_by,500,1,USER_00000001,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sys_flags,500.0,NaN,NaN,NaN,0.002,0.0,0.0,0.0,0.0,1.0,0.044721
path,500,500,ORG_00000001.ORG_00004J5D.ORG_00004JRL,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
years_in_business,500.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
industry_val_num,500.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
annual_rev_vid,500,1,0.0,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emp_count_vid,500,1,0.0,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oca,500.0,NaN,NaN,NaN,18.174,0.0,9.0,12.0,17.0,1199.0,74.900333
parent_org_id,500,232,ORG_00004J5D,259,NaN,NaN,NaN,NaN,NaN,NaN,NaN
master_org_id,500,6,ORG_00004J5D,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================


============================================================
DATASET: UNIFIED_DOCUMENTHEADER
============================================================

1. FIRST 10 ROWS:
------------------------------

,domainid,refnumber,notify,source_database,sourceorg,createddate,sourceorgname,userid,documentid,prop1,domainname,useremail,username,status,source_table,expirydate
0,Unknown,L167066,202.0,choice,ConAgraFoods,1970-01-01 00:00:00.020220912,ConAgra Consolidated,Unknown,L167066,Unknown,Unknown,Unknown,Unknown,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171107
1,Unknown,L167067,202.0,choice,ConAgraFoods,1970-01-01 00:00:00.020220912,ConAgra Consolidated,Unknown,L167067,Unknown,Unknown,Unknown,Unknown,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171107
2,DOM_00000001,ML8709,303.0,choice,Chicago,1970-01-01 00:00:00.020171106,Greater Chicago Food Depository,USER_Z0007742,ID_8709,Chicago1,DEFAULT,mloeffl@feedingamerica.org,Mike Loeffl,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171107
3,Unknown,L167081,202.0,choice,Kellogg,1970-01-01 00:00:00.020220912,Kellogg Company,Unknown,L167081,Single LineChoice,Unknown,Unknown,Unknown,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171107
4,Unknown,L167082,202.0,choice,Kellogg,1970-01-01 00:00:00.020220912,Kellogg Company,Unknown,L167082,Single LineChoice,Unknown,Unknown,Unknown,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171107
5,Unknown,L167113,202.0,choice,SeaShare,1970-01-01 00:00:00.020220912,SEASHARE,Unknown,L167113,Unknown,Unknown,Unknown,Unknown,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171113
6,Unknown,L167283,202.0,choice,SeaShare,1970-01-01 00:00:00.020220912,SEASHARE,Unknown,L167283,16 APA - 1,Unknown,Unknown,Unknown,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171215
7,Unknown,BL17120050-01,202.0,choice,Dole,1970-01-01 00:00:00.020220912,Dole Packaged Frozen Foods,Unknown,BL17120050-01,Mike Test 2,Unknown,Unknown,Unknown,6,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171219
8,Unknown,BL1712005101,202.0,choice,Dole,1970-01-01 00:00:00.020220912,Dole Packaged Frozen Foods,Unknown,BL1712005101,Mike Test 2,Unknown,Unknown,Unknown,3,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020171219
9,Unknown,BL1801003401,202.0,choice,Kraft,1970-01-01 00:00:00.020220912,Kraft Heinz,Unknown,BL1801003401,7533_42429_HW,Unknown,Unknown,Unknown,6,choice_DOCUMENTHEADER,1970-01-01 00:00:00.020180116

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   domainid         1000 non-null   object
 1   refnumber        1000 non-null   object
 2   notify           1000 non-null   float64
 3   source_database  1000 non-null   object
 4   sourceorg        1000 non-null   object
 5   createddate      1000 non-null   datetime64[ns]
 6   sourceorgname    1000 non-null   object
 7   userid           1000 non-null   object
 8   documentid       1000 non-null   object
 9   prop1            1000 non-null   object
 10  domainname       1000 non-null   object
 11  useremail        1000 non-null   object
 12  username         1000 non-null   object
 13  status           1000 non-null   int64
 14  source_table     1000 non-null   object
 15  expirydate       1000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1), object(12)
memory usage: 125.1+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
domainid,1000,2,Unknown,874,NaN,NaN,NaN,NaN,NaN,NaN,NaN
refnumber,1000,1000,PO505,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
notify,1000.0,NaN,NaN,NaN,157.571,0.0,101.0,101.0,202.0,1618.0,115.793346
source_database,1000,2,choice,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sourceorg,1000,419,ConAgraFoods,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
createddate,1000,NaN,NaN,NaN,1970-01-01 00:00:00.020130622,1970-01-01 00:00:00.020040512,1970-01-01 00:00:00.020040809,1970-01-01 00:00:00.020145871,1970-01-01 00:00:00.020220912,1970-01-01 00:00:00.020250710,NaN
sourceorgname,1000,154,Unknown,426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
userid,1000,46,Unknown,866,NaN,NaN,NaN,NaN,NaN,NaN,NaN
documentid,1000,1000,ID_505,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prop1,1000,265,Unknown,391,NaN,NaN,NaN,NaN,NaN,NaN,NaN
domainname,1000,2,Unknown,868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
useremail,1000,35,Unknown,868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
username,1000,42,Unknown,868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,1000.0,NaN,NaN,NaN,6.47,-1.0,4.0,4.0,7.0,100.0,11.38168
source_table,1000,2,choice_DOCUMENTHEADER,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
expirydate,1000,NaN,NaN,NaN,1970-01-01 00:00:00.020099983,1970-01-01 00:00:00,1970-01-01 00:00:00.020040818,1970-01-01 00:00:00.020145862,1970-01-01 00:00:00.020181115,1970-01-01 00:00:00.020250710,NaN

============================================================


============================================================
DATASET: UNIFIED_DONATION_HEADER
============================================================

1. FIRST 10 ROWS:
------------------------------

,rcontactphone,donorid,donationdate,dcontactfax,wcontactname,dcontactname,dcontactphone,donorname,rcontactname,shipmentmethod,outbydate,source_table,donorreferencenumber,source_database,wcontactaddress,stagingmethod,releasenumber,rcontactemail,releasedate,warehousename,wcontactcitystatezip,wcontactphone,deliveryinstructions,donationnumber,dcontactemail,status,wcontactemail
0,(269) 961-2000,Kellogg,2017-11-03,Unknown,Chris Loeffl,Caren Smith,(269) 961-2000,Kellogg,Eric Pettis,PICKUP,2017-11-10,choice_AMX_DONATION_HEADER,Choice bid multi line donation,choice,1100 Remington Blvd,ARRANGE,1,osd.cpu@kellogg.com,2017-11-03,1759 Peacock - Bolingbrook,"Bolingbrook, IL 60490-3308",(708) 566-9696,Unknown,WD17110017,csmith@kellogg.com,Acknowledged,Cloeffl@gmail.com
1,3121112222,Kraft,2017-10-25,Unknown,Fred Smith 2,Fred Smith 1,3121112222,Kraft,Fred Smith 1,PICKUP,2017-11-01,choice_AMX_DONATION_HEADER,Unknown,choice,Big Cheese BLVD,ARRANGE,Unknown,fsmith1@kraft.com,2017-10-25,Kraft ML Test 2 12282016,"Madison, WI 53705",800-456-8787,Please call Warehouse contact for pick up appointment ML,WD17100019,fsmith1@kraft.com,Acknowledged,fsmith2@kraft.com
2,225-5658-89,SeaShare,2017-11-01,Unknown,Tom Noonen,Ron Gister,225-5658-89,SeaShare,Ron Gister,PICKUP,2018-01-02,choice_AMX_DONATION_HEADER,ML SeaFod Test 1,choice,256 Fish Head Lane,ARRANGE,ML Seafood Test 1,rg@seashare.org,2017-12-25,SeaShare Fish Hut 1,"Green Bay, WI 54302",258-898-2235,This is from the special instructions line in the upload file,WD17110011,rg@seashare.org,Acknowledged,tn@seashare.org
3,(312) 717-5822,ConAgraFoods,2017-11-03,Unknown,Kanesha Moss,Caesar Amador,312-717-5822,ConAgraFoods,Dawn Knotts,DELIVER,2017-11-10,choice_AMX_DONATION_HEADER,Unknown,choice,1500 N Central Ave,PALLET EXC,Unknown,dawn.knotts@conagrafoods.com,2017-11-03,ConAgra,"Humboldt, TN 38343-1798",(859) 653-8989,Ease on down the road Dan added shelf life and extenstion and storage as refrigerated for the 1...,WD17110020,caesar.amador@conagrafoods.com,Acknowledged,Kanesha.Moss@conagrafoods.com
4,(269) 961-2000,Kellogg,2017-11-03,Unknown,Chris Loeffl,Caren Smith,(269) 961-2000,Kellogg,Eric Pettis,PICKUP,2017-11-10,choice_AMX_DONATION_HEADER,Direct Offer Multi line donation,choice,1100 Remington Blvd,ARRANGE,1,osd.cpu@kellogg.com,2017-11-03,1759 Peacock - Bolingbrook,"Bolingbrook, IL 60490-3308",(708) 566-9696,Unknown,WD17110019,csmith@kellogg.com,Acknowledged,Cloeffl@gmail.com
5,(312) 717-5822,ConAgraFoods,2017-11-03,Unknown,Kanesha Moss,Caesar Amador,312-717-5822,ConAgraFoods,Dawn Knotts,DELIVER,2017-11-10,choice_AMX_DONATION_HEADER,Unknown,choice,1500 N Central Ave,PALLET EXC,Unknown,dawn.knotts@conagrafoods.com,2017-11-03,ConAgra,"Humboldt, TN 38343-1798",(859) 653-8989,Ease on down the road Dan added shelf life and extenstion and storage as refrigerated for the 1...,WD17110031,caesar.amador@conagrafoods.com,Acknowledged,Kanesha.Moss@conagrafoods.com
6,(312) 717-5822,ConAgraFoods,2017-11-03,Unknown,Kanesha Moss,Caesar Amador,312-717-5822,ConAgraFoods,Dawn Knotts,DELIVER,2017-08-10,choice_AMX_DONATION_HEADER,Direct Offer Single line donation,choice,1500 N Central Ave,PALLET EXC,Unknown,dawn.knotts@conagrafoods.com,2017-08-03,ConAgra,"Humboldt, TN 38343-1798",(859) 653-8989,Ease on down the road,WD17110021,caesar.amador@conagrafoods.com,Acknowledged,Kanesha.Moss@conagrafoods.com
7,(312) 717-5822,ConAgraFoods,2017-11-03,Unknown,Kanesha Moss,Caesar Amador,312-717-5822,ConAgraFoods,Dawn Knotts,DELIVER,2017-11-10,choice_AMX_DONATION_HEADER,Direct Offer Multi line donation,choice,1500 N Central Ave,PALLET EXC,Unknown,dawn.knotts@conagrafoods.com,2017-11-03,ConAgra,"Humboldt, TN 38343-1798",(859) 653-8989,Ease on down the road,WD17110022,caesar.amador@conagrafoods.com,Acknowledged,Kanesha.Moss@conagrafoods.com
8,(773) 449-6969,Kellogg,2017-12-14,Unknown,Gary Geisking,Caren Smith,(773) 449-6969,Kellogg,Eric Pettis,PICKUP,2017-12-21,choice_AMX_DONATION_HEADER,Disaster,choice,4740 Florence St,SLIP SHEET,Disaster,osd.cpu@kellogg.com,2017-12-14,Kelloggs Denver DC 2483,"Denver, CO 80238-2413",317-897-1726,PO 498616 and 498162,WD17120021,csmith@kellogg.com,Acknowledged,gary@hoosierwarehouses.com
9,(269) 961-2000,Kellogg,2017-11-03,Unknown,Chris Loeffl,Caren Smith,(269) 961-2000,Kellogg,Eric Pettis,PICKUP,2017-11-10,choice_AMX_DONATION_HEADER,Choice bid multi line donation,choice,1100 Remington Blvd,ARRANGE,1,osd.cpu@kellogg.com,2017-11-03,1759 Peacock - Bolingbrook,"Bolingbrook, IL 60490-3308",(708) 566-9696,Unknown,WD17110049,csmith@kellogg.com,Acknowledged,Cloeffl@gmail.com

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rcontactphone         500 non-null    object
 1   donorid               500 non-null    object
 2   donationdate          500 non-null    datetime64[ns]
 3   dcontactfax           500 non-null    object
 4   wcontactname          500 non-null    object
 5   dcontactname          500 non-null    object
 6   dcontactphone         500 non-null    object
 7   donorname             500 non-null    object
 8   rcontactname          500 non-null    object
 9   shipmentmethod        500 non-null    object
 10  outbydate             500 non-null    datetime64[ns]
 11  source_table          500 non-null    object
 12  donorreferencenumber  500 non-null    object
 13  source_database       500 non-null    object
 14  wcontactaddress       500 non-null    object
 15  stagingmethod         500 non-null    object
 16  releasenumber         500 non-null    object
 17  rcontactemail         500 non-null    object
 18  releasedate           500 non-null    datetime64[ns]
 19  warehousename         500 non-null    object
 20  wcontactcitystatezip  500 non-null    object
 21  wcontactphone         500 non-null    object
 22  deliveryinstructions  500 non-null    object
 23  donationnumber        500 non-null    object
 24  dcontactemail         500 non-null    object
 25  status                500 non-null    object
 26  wcontactemail         500 non-null    object
dtypes: datetime64[ns](3), object(24)
memory usage: 105.6+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max
rcontactphone,500,176,Unknown,76,NaN,NaN,NaN,NaN,NaN,NaN
donorid,500,84,ConAgraFoods,63,NaN,NaN,NaN,NaN,NaN,NaN
donationdate,500,NaN,NaN,NaN,2018-04-30 20:47:02.400000256,1900-01-01 00:00:00,2018-03-12 00:00:00,2019-04-01 12:00:00,2022-04-26 06:00:00,2025-07-10 00:00:00
dcontactfax,500,30,Unknown,441,NaN,NaN,NaN,NaN,NaN,NaN
wcontactname,500,267,Tom Thimble,21,NaN,NaN,NaN,NaN,NaN,NaN
dcontactname,500,213,Mary Harmon,18,NaN,NaN,NaN,NaN,NaN,NaN
dcontactphone,500,202,Unknown,58,NaN,NaN,NaN,NaN,NaN,NaN
donorname,500,84,ConAgraFoods,63,NaN,NaN,NaN,NaN,NaN,NaN
rcontactname,500,183,Unknown,38,NaN,NaN,NaN,NaN,NaN,NaN
shipmentmethod,500,6,PICKUP,419,NaN,NaN,NaN,NaN,NaN,NaN
outbydate,500,NaN,NaN,NaN,2012-03-15 05:05:16.800000,1900-01-01 00:00:00,2018-01-29 00:00:00,2018-10-15 00:00:00,2021-09-25 00:00:00,2025-09-30 00:00:00
source_table,500,1,choice_AMX_DONATION_HEADER,500,NaN,NaN,NaN,NaN,NaN,NaN
donorreferencenumber,500,228,Unknown,217,NaN,NaN,NaN,NaN,NaN,NaN
source_database,500,1,choice,500,NaN,NaN,NaN,NaN,NaN,NaN
wcontactaddress,500,243,44 Artwind St,22,NaN,NaN,NaN,NaN,NaN,NaN
stagingmethod,500,8,ARRANGE,219,NaN,NaN,NaN,NaN,NaN,NaN
releasenumber,500,174,Unknown,171,NaN,NaN,NaN,NaN,NaN,NaN
rcontactemail,500,177,Unknown,45,NaN,NaN,NaN,NaN,NaN,NaN
releasedate,500,NaN,NaN,NaN,2017-04-16 12:48:57.599999744,1900-01-01 00:00:00,2018-01-25 00:00:00,2019-02-19 00:00:00,2022-03-06 12:00:00,2025-07-10 00:00:00
warehousename,500,249,Dole Warehouse 1A,22,NaN,NaN,NaN,NaN,NaN,NaN
wcontactcitystatezip,500,242,"Grayslake, IL 60030",22,NaN,NaN,NaN,NaN,NaN,NaN
wcontactphone,500,244,Unknown,48,NaN,NaN,NaN,NaN,NaN,NaN
deliveryinstructions,500,190,Unknown,167,NaN,NaN,NaN,NaN,NaN,NaN
donationnumber,500,500,WD24090027,1,NaN,NaN,NaN,NaN,NaN,NaN
dcontactemail,500,211,Remarketing@kellogg.com,30,NaN,NaN,NaN,NaN,NaN,NaN
status,500,8,Acknowledged,374,NaN,NaN,NaN,NaN,NaN,NaN
wcontactemail,500,238,Unknown,68,NaN,NaN,NaN,NaN,NaN,NaN

============================================================


============================================================
DATASET: UNIFIED_RW_ORG
============================================================

1. FIRST 10 ROWS:
------------------------------

,entity_name,parent_org_id,annual_rev_vid,org_id,printable_name,source_table,currency_pattern,path,source_database,currency,created_time,master_org_id,modified_by,industry_val_num,float_pattern,sys_flags,country,org_type,years_in_business,modified_time,group_size,status_flag,language,oca,decimal_char,created_by,group_separator,emp_count_vid
0,SanLeandro,ORG_00004IFK,0.0,ORG_00004KEF,San Leandro,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFH.ORG_00004IFK.ORG_00004KEF,choice,USD,2003-05-06 05:09:58,ORG_00004IFH,USER_00004K1T,0.0,"###,##0.###",0,US,S,0.0,2003-05-06 05:10:49,3,A,en,1,.,USER_00004K1T,",",0.0
1,WinchesterPlant,ORG_00004IFK,0.0,ORG_00004KH5,WinchesterPlant,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFH.ORG_00004IFK.ORG_00004KH5,choice,USD,2003-05-09 03:01:28,ORG_00004IFH,USER_00004K1T,0.0,"###,##0.###",0,US,S,0.0,2003-05-09 03:02:31,3,A,en,1,.,USER_00004K1T,",",0.0
2,Albuquerque,ORG_00004IFI,0.0,ORG_00004KH6,Albuquerque,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KH6,choice,USD,2003-05-18 17:14:51,ORG_00004IFI,USER_00004SE9,0.0,"###,##0.###",0,US,S,0.0,2009-04-24 15:14:39,3,A,en,5,.,USER_00004K1T,",",0.0
3,MemphisZC,ORG_00004IFI,0.0,ORG_00004KH7,MemphisZC,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KH7,choice,USD,2003-05-18 17:29:09,ORG_00004IFI,USER_00004K1T,0.0,"###,##0.###",0,US,S,0.0,2003-05-18 17:31:33,3,A,en,2,.,USER_00004K1T,",",0.0
4,FtMeyersZC,ORG_00004IFI,0.0,ORG_00004KH8,FtMeyersZC,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KH8,choice,USD,2003-05-18 17:37:20,ORG_00004IFI,USER_00004Q9N,0.0,"###,##0.###",0,US,S,0.0,2006-01-05 00:27:12,3,A,en,5,.,USER_00004K1T,",",0.0
5,Fargo,ORG_00004IFI,0.0,ORG_00004KH9,Fargo,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KH9,choice,USD,2003-05-18 20:46:17,ORG_00004IFI,USER_00004Q9N,0.0,"###,##0.###",0,US,S,0.0,2006-01-05 00:19:25,3,A,en,3,.,USER_00004K1T,",",0.0
6,Memphis,ORG_00004IFI,0.0,ORG_00004KHA,Mid-South Food Bank,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KHA,choice,USD,2003-05-18 20:54:13,ORG_00004IFI,USER_00004SE9,0.0,"###,##0.###",0,US,S,0.0,2008-12-02 14:20:39,3,A,en,7,.,USER_00004K1T,",",0.0
7,Pennsauken,ORG_00004IFI,0.0,ORG_00004KHB,Pennsauken,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KHB,choice,USD,2003-05-18 20:57:48,ORG_00004IFI,USER_00004Q9N,0.0,"###,##0.###",0,US,S,0.0,2006-01-05 23:53:35,3,A,en,3,.,USER_00004K1T,",",0.0
8,MemphisZD,ORG_00004IFI,0.0,ORG_00004KHC,MemphisZD,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KHC,choice,USD,2003-05-19 12:27:45,ORG_00004IFI,USER_00004Q9N,0.0,"###,##0.###",0,US,S,0.0,2006-01-05 23:15:08,3,I,en,3,.,USER_00004K1T,",",0.0
9,TestAffiliate6,ORG_00004IFI,0.0,ORG_00004KK9,Test Affiliate6,choice_RW_ORG,"*###,##0.00",ORG_00000001.ORG_00004IFI.ORG_00004KK9,choice,USD,2003-05-22 20:21:44,ORG_00004IFI,USER_00004K1T,0.0,"###,##0.###",0,US,S,0.0,2003-05-22 20:22:44,3,A,en,2,.,USER_00004K1T,",",0.0

2. DATASET INFO:
------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   entity_name        1000 non-null   object
 1   parent_org_id      1000 non-null   object
 2   annual_rev_vid     1000 non-null   object
 3   org_id             1000 non-null   object
 4   printable_name     1000 non-null   object
 5   source_table       1000 non-null   object
 6   currency_pattern   1000 non-null   object
 7   path               1000 non-null   object
 8   source_database    1000 non-null   object
 9   currency           1000 non-null   object
 10  created_time       1000 non-null   datetime64[ns]
 11  master_org_id      1000 non-null   object
 12  modified_by        1000 non-null   object
 13  industry_val_num   1000 non-null   float64
 14  float_pattern      1000 non-null   object
 15  sys_flags          1000 non-null   int64
 16  country            1000 non-null   object
 17  org_type           1000 non-null   object
 18  years_in_business  1000 non-null   float64
 19  modified_time      1000 non-null   datetime64[ns]
 20  group_size         1000 non-null   int64
 21  status_flag        1000 non-null   object
 22  language           1000 non-null   object
 23  oca                1000 non-null   int64
 24  decimal_char       1000 non-null   object
 25  created_by         1000 non-null   object
 26  group_separator    1000 non-null   object
 27  emp_count_vid      1000 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(3), object(21)
memory usage: 218.9+ KB

3. DESCRIPTIVE STATISTICS (ALL COLUMNS):
------------------------------

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
entity_name,1000,999,DEFAULT,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
parent_org_id,1000,246,ORG_00004J5D,259,NaN,NaN,NaN,NaN,NaN,NaN,NaN
annual_rev_vid,1000,1,0.0,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
org_id,1000,929,ORG_00004K4Q,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
printable_name,1000,858,Unknown,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
source_table,1000,2,choice_RW_ORG,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency_pattern,1000,1,"*###,##0.00",1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
path,1000,995,ORG_00000001.ORG_00004IIL,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
source_database,1000,2,choice,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
currency,1000,1,USD,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_time,1000,NaN,NaN,NaN,2004-02-20 23:25:57.092000,2001-01-01 00:00:00,2002-08-13 18:33:44.750000,2002-08-14 21:07:32.500000,2004-03-03 07:33:34,2024-05-02 00:00:00,NaN
master_org_id,1000,15,ORG_00004J5D,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN
modified_by,1000,13,USER_00000001,525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
industry_val_num,1000.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
float_pattern,1000,2,"###,##0.###",505,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sys_flags,1000.0,NaN,NaN,NaN,0.002,0.0,0.0,0.0,0.0,1.0,0.044699
country,1000,1,US,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
org_type,1000,3,S,982,NaN,NaN,NaN,NaN,NaN,NaN,NaN
years_in_business,1000.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
modified_time,1000,NaN,NaN,NaN,2004-10-20 05:25:26.481000064,2001-01-01 00:00:00,2002-10-26 11:37:10.250000,2003-02-07 08:21:31.500000,2006-01-05 00:52:24.750000,2024-05-02 00:00:00,NaN
group_size,1000.0,NaN,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,0.0
status_flag,1000,2,I,535,NaN,NaN,NaN,NaN,NaN,NaN,NaN
language,1000,1,en,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oca,1000.0,NaN,NaN,NaN,10.631,0.0,3.0,8.0,13.0,1199.0,53.523935
decimal_char,1000,1,.,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_by,1000,11,USER_00000001,524,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group_separator,1000,1,",",1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emp_count_vid,1000,1,0.0,1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================

### 4.1 Univariate Analysis - Individual Variable Distributions

Analyzing each variable independently to understand distributions, central tendencies, and outliers.

In [63]:
# Comprehensive Univariate Analysis
if 'eda' in globals():
    print(" UNIVARIATE ANALYSIS")
    print("=" * 50)
    
    # Dataset Overview
    overview = eda.get_dataset_overview()
    
    # Analyze each dataset
    univariate_results = {}
    
    print(f" Analyzing datasets... ({len(eda.datasets)} total)\n")
    for dataset_name, df in eda.datasets.items():
        if len(df) > 0:
            print(f" Processing {dataset_name}...\n")
            print(f"\n{'='*60}")
            print(f" DETAILED ANALYSIS: {dataset_name.upper()}")
            print(f"{'='*60}")
            
            # Numeric analysis
            numeric_summary = eda.analyze_numeric_columns(df, dataset_name)
            
            # Categorical analysis 
            categorical_summary = eda.analyze_categorical_columns(df, dataset_name)
            
            # Store results
            univariate_results[dataset_name] = {
                'numeric_summary': numeric_summary,
                'categorical_summary': categorical_summary
            }
            
            # Look for datetime columns
            datetime_cols = df.select_dtypes(include=['datetime64']).columns
            if len(datetime_cols) > 0:
                print(f"\n DateTime Analysis: {len(datetime_cols)} columns")
                for col in datetime_cols[:3]:  # Limit to first 3 datetime columns
                    if df[col].count() > 0:
                        date_range = df[col].dropna()
                        print(f"   {col}: {date_range.min()} to {date_range.max()} ({len(date_range)} records)")
                        
                        # Check for date patterns
                        date_span_days = (date_range.max() - date_range.min()).days
                        if date_span_days > 365:
                            eda.add_insight('Temporal Coverage', f"{col} in {dataset_name} spans {date_span_days} days - good for trend analysis")

    print(f"\n✅ Univariate analysis completed for {len(univariate_results)} datasets")
else:
    print(" EDA toolkit not available - run previous section first")

 UNIVARIATE ANALYSIS
==================================================
 Dataset Overview Analysis
========================================

 choice_DOCUMENTHEADER:
   Dimensions: 500 rows × 46 columns
   Memory usage: 1.3 MB
   Missing data: 0 cells (0.0%)
   Data types: 2 numeric, 42 categorical, 2 datetime

 choice_AMX_DONATION_HEADER:
   Dimensions: 500 rows × 25 columns
   Memory usage: 0.7 MB
   Missing data: 51 cells (0.4%)
   Data types: 0 numeric, 22 categorical, 3 datetime

 choice_AMX_DONATION_LINES:
   Dimensions: 500 rows × 23 columns
   Memory usage: 0.4 MB
   Missing data: 609 cells (5.3%)
   Data types: 6 numeric, 14 categorical, 3 datetime

 choice_RW_ORG:
   Dimensions: 500 rows × 27 columns
   Memory usage: 0.6 MB
   Missing data: 500 cells (3.7%)
   Data types: 5 numeric, 19 categorical, 3 datetime

 agency_DOCUMENTHEADER:
   Dimensions: 500 rows × 19 columns
   Memory usage: 0.3 MB
   Missing data: 0 cells (0.0%)
   Data types: 4 numeric, 11 categorical, 4 datetime

 agency_DOCUMENTLINES:
   Dimensions: 500 rows × 16 columns
   Memory usage: 0.3 MB
   Missing data: 0 cells (0.0%)
   Data types: 3 numeric, 12 categorical, 1 datetime

 agency_RW_ORG:
   Dimensions: 500 rows × 28 columns
   Memory usage: 0.6 MB
   Missing data: 500 cells (3.6%)
   Data types: 5 numeric, 20 categorical, 3 datetime

 unified_documentheader:
   Dimensions: 1,000 rows × 16 columns
   Memory usage: 0.7 MB
   Missing data: 0 cells (0.0%)
   Data types: 2 numeric, 12 categorical, 2 datetime

 unified_donation_header:
   Dimensions: 500 rows × 27 columns
   Memory usage: 0.7 MB
   Missing data: 0 cells (0.0%)
   Data types: 0 numeric, 24 categorical, 3 datetime

 unified_rw_org:
   Dimensions: 1,000 rows × 28 columns
   Memory usage: 1.2 MB
   Missing data: 0 cells (0.0%)
   Data types: 5 numeric, 21 categorical, 2 datetime
 Analyzing datasets... (10 total)

 Processing choice_DOCUMENTHEADER...


============================================================
 DETAILED ANALYSIS: CHOICE_DOCUMENTHEADER
============================================================

 Numeric Analysis: choice_DOCUMENTHEADER (2 columns)
--------------------------------------------------

   status:
     Count: 500 | Unique: 6 | Zeros: 48
     Mean: 6.44 | Median: 6.00 | Std: 11.49
     Range: [-1.00, 100.00] | Skewness: 7.58
 Distribution: status in choice_DOCUMENTHEADER is highly right-skewed (skewness: 7.58)

   notify:
     Count: 500 | Unique: 18 | Zeros: 5
     Mean: 214.54 | Median: 202.00 | Std: 141.76
     Range: [0.00, 1618.00] | Skewness: 8.62
 Distribution: notify in choice_DOCUMENTHEADER is highly right-skewed (skewness: 8.62)

 Categorical Analysis: choice_DOCUMENTHEADER (42 columns)
--------------------------------------------------

   documentid:
     Unique values: 500
     Most common: 'ML10289' (1 times)
 Data Quality: documentid in choice_DOCUMENTHEADER has very high uniqueness (100.0%) - possibly an identifier

   refnumber:
     Unique values: 500
     Most common: 'ML10289' (1 times)
 Data Quality: refnumber in choice_DOCUMENTHEADER has very high uniqueness (100.0%) - possibly an identifier

   sourceorg:
     Unique values: 105
     Most common: 'ConAgraFoods' (52 times)

   userid:
     Unique values: 9
     Most common: 'Unknown' (440 times)
     Top categories: {'Unknown': 440, 'USER_Z0007641': 21, 'USER_Z0003402': 18, 'USER_Z0007603': 10, 'USER_Z0007581': 5}
 Data Pattern: userid in choice_DOCUMENTHEADER is dominated by 'Unknown' (88.0% of records)

   prop1:
     Unique values: 227
     Most common: 'Unknown' (195 times)

   prop2:
     Unique values: 402
     Most common: 'Unknown' (38 times)

   prop3:
     Unique values: 3
     Most common: 'No' (291 times)
     Top categories: {'No': 291, 'Yes': 180, 'Unknown': 29}

   prop4:
     Unique values: 14
     Most common: '0' (283 times)
     Top categories: {'0': 283, '1': 105, 'Unknown': 54, '-1': 35, '2': 5}

   prop5:
     Unique values: 247
     Most common: '1/9/2017' (23 times)

   prop6:
     Unique values: 142
     Most common: 'Unknown' (181 times)

 DateTime Analysis: 2 columns
   createddate: 1970-01-01 00:00:00.020170823 to 1970-01-01 00:00:00.020250710 (500 records)
   expirydate: 1970-01-01 00:00:00.020170804 to 1970-01-01 00:00:00.020250710 (500 records)
 Processing choice_AMX_DONATION_HEADER...


============================================================
 DETAILED ANALYSIS: CHOICE_AMX_DONATION_HEADER
============================================================
   No numeric columns found in choice_AMX_DONATION_HEADER

 Categorical Analysis: choice_AMX_DONATION_HEADER (22 columns)
--------------------------------------------------

   donationnumber:
     Unique values: 500
     Most common: 'WD24090027' (1 times)
 Data Quality: donationnumber in choice_AMX_DONATION_HEADER has very high uniqueness (100.0%) - possibly an identifier

   donorid:
     Unique values: 84
     Most common: 'ConAgraFoods' (63 times)

   donorname:
     Unique values: 84
     Most common: 'ConAgraFoods' (63 times)

   dcontactname:
     Unique values: 213
     Most common: 'Mary Harmon' (18 times)

   dcontactphone:
     Unique values: 202
     Most common: 'Unknown' (58 times)

   dcontactfax:
     Unique values: 30
     Most common: 'Unknown' (441 times)
 Data Pattern: dcontactfax in choice_AMX_DONATION_HEADER is dominated by 'Unknown' (88.2% of records)

   donorreferencenumber:
     Unique values: 228
     Most common: 'Unknown' (217 times)

   dcontactemail:
     Unique values: 211
     Most common: 'Remarketing@kellogg.com' (30 times)

   rcontactname:
     Unique values: 183
     Most common: 'Unknown' (38 times)

   rcontactphone:
     Unique values: 176
     Most common: 'Unknown' (76 times)

 DateTime Analysis: 3 columns
   donationdate: 2017-01-23 00:00:00 to 2025-07-10 00:00:00 (492 records)
 Temporal Coverage: donationdate in choice_AMX_DONATION_HEADER spans 3090 days - good for trend analysis
   releasedate: 2003-01-29 00:00:00 to 2025-07-10 00:00:00 (489 records)
 Temporal Coverage: releasedate in choice_AMX_DONATION_HEADER spans 8198 days - good for trend analysis
   outbydate: 2003-03-07 00:00:00 to 2025-09-30 00:00:00 (468 records)
 Temporal Coverage: outbydate in choice_AMX_DONATION_HEADER spans 8243 days - good for trend analysis
 Processing choice_AMX_DONATION_LINES...


============================================================
 DETAILED ANALYSIS: CHOICE_AMX_DONATION_LINES
============================================================

 Numeric Analysis: choice_AMX_DONATION_LINES (6 columns)
--------------------------------------------------

   quantity:
     Count: 500 | Unique: 63 | Zeros: 0
     Mean: 123.30 | Median: 20.00 | Std: 360.47
     Range: [1.00, 6001.00] | Skewness: 10.01
 Distribution: quantity in choice_AMX_DONATION_LINES is highly right-skewed (skewness: 10.01)

   quantityperpallet:
     Count: 500 | Unique: 38 | Zeros: 0
     Mean: 74.71 | Median: 50.00 | Std: 199.30
     Range: [1.00, 2231.00] | Skewness: 10.21
 Distribution: quantityperpallet in choice_AMX_DONATION_LINES is highly right-skewed (skewness: 10.21)

   totalpallets:
     Count: 500 | Unique: 66 | Zeros: 7
     Mean: 3.57 | Median: 0.67 | Std: 11.80
     Range: [0.00, 200.03] | Skewness: 11.18
 Distribution: totalpallets in choice_AMX_DONATION_LINES is highly right-skewed (skewness: 11.18)

   grossweight:
     Count: 500 | Unique: 50 | Zeros: 0
     Mean: 152.54 | Median: 25.00 | Std: 480.21
     Range: [0.00, 2231.00] | Skewness: 3.79
 Distribution: grossweight in choice_AMX_DONATION_LINES is highly right-skewed (skewness: 3.79)

   totalgrossweight:
     Count: 500 | Unique: 98 | Zeros: 0
     Mean: 3014.61 | Median: 598.85 | Std: 6979.86
     Range: [0.05, 60010.00] | Skewness: 4.22
 Distribution: totalgrossweight in choice_AMX_DONATION_LINES is highly right-skewed (skewness: 4.22)

   netweight:
     Count: 500 | Unique: 24 | Zeros: 0
     Mean: 460.66 | Median: 432.00 | Std: 293.95
     Range: [2.19, 2327.00] | Skewness: 5.30
 Distribution: netweight in choice_AMX_DONATION_LINES is highly right-skewed (skewness: 5.30)

 Categorical Analysis: choice_AMX_DONATION_LINES (14 columns)
--------------------------------------------------

   donationnumber:
     Unique values: 40
     Most common: 'WD18020051' (152 times)

   itemnumber:
     Unique values: 98
     Most common: 'Chk636T3' (48 times)

   itemdescription:
     Unique values: 99
     Most common: 'SML WING CSE' (48 times)

   donationreason:
     Unique values: 13
     Most common: 'Discontinued Item' (236 times)
     Top categories: {'Discontinued Item': 236, 'CLOSE CODE': 180, 'Out of Code': 23, 'Disaster Relief': 23, 'Inventory': 14}

   pack:
     Unique values: 34
     Most common: '/ Bag' (178 times)

   size_:
     Unique values: 19
     Most common: 'Unknown' (348 times)
     Top categories: {'Unknown': 348, '12': 54, '17.1': 13, '16': 12, '20': 12}

   sizeuom:
     Unique values: 12
     Most common: 'Bag' (178 times)
     Top categories: {'Bag': 178, 'Unknown': 164, 'Ounce': 122, 'CS': 12, 'Box': 7}

   packagingtype:
     Unique values: 10
     Most common: 'Unknown' (354 times)
     Top categories: {'Unknown': 354, 'Other': 42, 'Can': 38, 'Bag': 30, 'PAPER': 19}

   unitofmeasure:
     Unique values: 10
     Most common: 'Case' (306 times)
     Top categories: {'Case': 306, 'Unknown': 89, 'Carton': 48, 'Box': 26, 'Each': 12}

   storagerequirement:
     Unique values: 4
     Most common: 'DRY' (312 times)
     Top categories: {'DRY': 312, 'FROZEN': 163, 'Refrigerated': 21, 'Unknown': 4}

 DateTime Analysis: 3 columns
   manufacturedate: 1752-12-31 00:00:00 to 2018-10-20 00:00:00 (336 records)
 Temporal Coverage: manufacturedate in choice_AMX_DONATION_LINES spans 97082 days - good for trend analysis
   expirationdate: 1752-12-31 00:00:00 to 2019-03-18 00:00:00 (75 records)
 Temporal Coverage: expirationdate in choice_AMX_DONATION_LINES spans 97231 days - good for trend analysis
   usebydate: 2016-02-25 00:00:00 to 2028-01-02 00:00:00 (480 records)
 Temporal Coverage: usebydate in choice_AMX_DONATION_LINES spans 4329 days - good for trend analysis
 Processing choice_RW_ORG...


============================================================
 DETAILED ANALYSIS: CHOICE_RW_ORG
============================================================

 Numeric Analysis: choice_RW_ORG (5 columns)
--------------------------------------------------

   group_size:
     Count: 500 | Unique: 1 | Zeros: 0
     Mean: 3.00 | Median: 3.00 | Std: 0.00
     Range: [3.00, 3.00] | Skewness: 0.00

   sys_flags:
     Count: 500 | Unique: 2 | Zeros: 499
     Mean: 0.00 | Median: 0.00 | Std: 0.04
     Range: [0.00, 1.00] | Skewness: 22.36
 Distribution: sys_flags in choice_RW_ORG is highly right-skewed (skewness: 22.36)
 Data Pattern: sys_flags in choice_RW_ORG has 99.8% zero values

   years_in_business:
     Count: 500 | Unique: 1 | Zeros: 500
     Mean: 0.00 | Median: 0.00 | Std: 0.00
     Range: [0.00, 0.00] | Skewness: 0.00
 Data Pattern: years_in_business in choice_RW_ORG has 100.0% zero values

   industry_val_num:
     Count: 500 | Unique: 1 | Zeros: 500
     Mean: 0.00 | Median: 0.00 | Std: 0.00
     Range: [0.00, 0.00] | Skewness: 0.00
 Data Pattern: industry_val_num in choice_RW_ORG has 100.0% zero values

   oca:
     Count: 500 | Unique: 21 | Zeros: 14
     Mean: 3.09 | Median: 3.00 | Std: 3.36
     Range: [0.00, 29.00] | Skewness: 4.61
 Distribution: oca in choice_RW_ORG is highly right-skewed (skewness: 4.61)

 Categorical Analysis: choice_RW_ORG (19 columns)
--------------------------------------------------

   org_id:
     Unique values: 500
     Most common: 'ORG_00004NB1' (1 times)
 Data Quality: org_id in choice_RW_ORG has very high uniqueness (100.0%) - possibly an identifier

   entity_name:
     Unique values: 500
     Most common: 'Ottumwa' (1 times)
 Data Quality: entity_name in choice_RW_ORG has very high uniqueness (100.0%) - possibly an identifier

   printable_name:
     Unique values: 374
     Most common: 'Unknown' (122 times)

   status_flag:
     Unique values: 2
     Most common: 'A' (436 times)
     Top categories: {'A': 436, 'I': 64}
 Data Pattern: status_flag in choice_RW_ORG is dominated by 'A' (87.2% of records)

   currency:
     Unique values: 1
     Most common: 'USD' (500 times)
     Top categories: {'USD': 500}
 Data Pattern: currency in choice_RW_ORG is dominated by 'USD' (100.0% of records)

   currency_pattern:
     Unique values: 1
     Most common: '*###,##0.00' (500 times)
     Top categories: {'*###,##0.00': 500}
 Data Pattern: currency_pattern in choice_RW_ORG is dominated by '*###,##0.00' (100.0% of records)

   float_pattern:
     Unique values: 1
     Most common: '###,##0.###' (500 times)
     Top categories: {'###,##0.###': 500}
 Data Pattern: float_pattern in choice_RW_ORG is dominated by '###,##0.###' (100.0% of records)

   group_separator:
     Unique values: 1
     Most common: ',' (500 times)
     Top categories: {',': 500}
 Data Pattern: group_separator in choice_RW_ORG is dominated by ',' (100.0% of records)

   decimal_char:
     Unique values: 1
     Most common: '.' (500 times)
     Top categories: {'.': 500}
 Data Pattern: decimal_char in choice_RW_ORG is dominated by '.' (100.0% of records)

   language:
     Unique values: 1
     Most common: 'en' (500 times)
     Top categories: {'en': 500}
 Data Pattern: language in choice_RW_ORG is dominated by 'en' (100.0% of records)

 DateTime Analysis: 3 columns
   created_time: 2001-01-01 00:00:00 to 2014-05-27 12:31:57 (500 records)
 Temporal Coverage: created_time in choice_RW_ORG spans 4894 days - good for trend analysis
   modified_time: 2001-08-23 00:50:46 to 2014-05-27 12:31:57 (500 records)
 Temporal Coverage: modified_time in choice_RW_ORG spans 4660 days - good for trend analysis
 Processing agency_DOCUMENTHEADER...


============================================================
 DETAILED ANALYSIS: AGENCY_DOCUMENTHEADER
============================================================

 Numeric Analysis: agency_DOCUMENTHEADER (4 columns)
--------------------------------------------------

   status:
     Count: 500 | Unique: 7 | Zeros: 0
     Mean: 6.50 | Median: 4.00 | Std: 11.28
     Range: [1.00, 100.00] | Skewness: 8.00
 Distribution: status in agency_DOCUMENTHEADER is highly right-skewed (skewness: 8.00)

   notify:
     Count: 500 | Unique: 8 | Zeros: 6
     Mean: 100.60 | Median: 101.00 | Std: 15.58
     Range: [0.00, 301.00] | Skewness: 2.11
 Distribution: notify in agency_DOCUMENTHEADER is highly right-skewed (skewness: 2.11)

   isarchived:
     Count: 500 | Unique: 1 | Zeros: 0
     Mean: 1.00 | Median: 1.00 | Std: 0.00
     Range: [1.00, 1.00] | Skewness: 0.00

   isae4order:
     Count: 500 | Unique: 1 | Zeros: 500
     Mean: 0.00 | Median: 0.00 | Std: 0.00
     Range: [0.00, 0.00] | Skewness: 0.00
 Data Pattern: isae4order in agency_DOCUMENTHEADER has 100.0% zero values

 Categorical Analysis: agency_DOCUMENTHEADER (11 columns)
--------------------------------------------------

   documentid:
     Unique values: 500
     Most common: 'ID_505' (1 times)
 Data Quality: documentid in agency_DOCUMENTHEADER has very high uniqueness (100.0%) - possibly an identifier

   refnumber:
     Unique values: 500
     Most common: 'PO505' (1 times)
 Data Quality: refnumber in agency_DOCUMENTHEADER has very high uniqueness (100.0%) - possibly an identifier

   sourceorg:
     Unique values: 314
     Most common: 'ORG_00004N05' (9 times)

   userid:
     Unique values: 38
     Most common: 'Unknown' (426 times)
 Data Pattern: userid in agency_DOCUMENTHEADER is dominated by 'Unknown' (85.2% of records)

   warehouseid:
     Unique values: 29
     Most common: 'Unknown' (438 times)
 Data Pattern: warehouseid in agency_DOCUMENTHEADER is dominated by 'Unknown' (87.6% of records)

   prop1:
     Unique values: 39
     Most common: 'Unknown' (196 times)

   username:
     Unique values: 37
     Most common: 'Unknown' (426 times)
 Data Pattern: username in agency_DOCUMENTHEADER is dominated by 'Unknown' (85.2% of records)

   useremail:
     Unique values: 30
     Most common: 'Unknown' (426 times)
 Data Pattern: useremail in agency_DOCUMENTHEADER is dominated by 'Unknown' (85.2% of records)

   sourceorgname:
     Unique values: 37
     Most common: 'Unknown' (426 times)
 Data Pattern: sourceorgname in agency_DOCUMENTHEADER is dominated by 'Unknown' (85.2% of records)

   domainid:
     Unique values: 2
     Most common: 'Unknown' (432 times)
     Top categories: {'Unknown': 432, 'DOM_00000001': 68}
 Data Pattern: domainid in agency_DOCUMENTHEADER is dominated by 'Unknown' (86.4% of records)

 DateTime Analysis: 4 columns
   createddate: 1970-01-01 00:00:00.020040512 to 1970-01-01 00:00:00.020120920 (500 records)
   expirydate: 1970-01-01 00:00:00 to 1970-01-01 00:00:00.020120921 (500 records)
   modifieddate: 1970-01-01 00:00:00.020040512 to 1970-01-01 00:00:00.020120920 (500 records)
 Processing agency_DOCUMENTLINES...


============================================================
 DETAILED ANALYSIS: AGENCY_DOCUMENTLINES
============================================================

 Numeric Analysis: agency_DOCUMENTLINES (3 columns)
--------------------------------------------------

   lineitemnumber:
     Count: 500 | Unique: 43 | Zeros: 0
     Mean: 9.71 | Median: 6.00 | Std: 9.17
     Range: [1.00, 43.00] | Skewness: 1.74

   donatedquantity:
     Count: 500 | Unique: 17 | Zeros: 466
     Mean: 0.74 | Median: 0.00 | Std: 3.41
     Range: [0.00, 30.00] | Skewness: 5.56
 Distribution: donatedquantity in agency_DOCUMENTLINES is highly right-skewed (skewness: 5.56)
 Data Pattern: donatedquantity in agency_DOCUMENTLINES has 93.2% zero values

   acceptedquantity:
     Count: 500 | Unique: 73 | Zeros: 16
     Mean: 95.75 | Median: 5.00 | Std: 622.05
     Range: [0.00, 8039.00] | Skewness: 9.67
 Distribution: acceptedquantity in agency_DOCUMENTLINES is highly right-skewed (skewness: 9.67)

 Categorical Analysis: agency_DOCUMENTLINES (12 columns)
--------------------------------------------------

   headerid:
     Unique values: 78
     Most common: '019537496' (27 times)

   itemname:
     Unique values: 285
     Most common: 'Milk 2% Reduced Fat 8oz' (17 times)

   itemcode:
     Unique values: 287
     Most common: '82048' (17 times)

   prop1:
     Unique values: 5
     Most common: 'CASE' (187 times)
     Top categories: {'CASE': 187, 'CS': 169, 'EA': 93, 'LB': 41, 'Unknown': 10}

   prop2:
     Unique values: 187
     Most common: '0' (15 times)

   prop3:
     Unique values: 141
     Most common: '0' (114 times)

   prop4:
     Unique values: 10
     Most common: 'CASE' (244 times)
     Top categories: {'CASE': 244, 'Unknown': 132, 'OTHER': 90, 'BULKBOX': 9, 'BAG': 7}

   prop5:
     Unique values: 140
     Most common: 'Unknown' (236 times)

   prop6:
     Unique values: 6
     Most common: 'DRY' (274 times)
     Top categories: {'DRY': 274, 'Unknown': 114, 'REF': 60, 'FROZEN': 45, 'Dry': 6}

   prop7:
     Unique values: 32
     Most common: '0' (459 times)
 Data Pattern: prop7 in agency_DOCUMENTLINES is dominated by '0' (91.8% of records)

 DateTime Analysis: 1 columns
   accepteddate: 1970-01-01 00:00:00.020040610 to 1970-01-01 00:00:00.020060215 (500 records)
 Processing agency_RW_ORG...


============================================================
 DETAILED ANALYSIS: AGENCY_RW_ORG
============================================================

 Numeric Analysis: agency_RW_ORG (5 columns)
--------------------------------------------------

   group_size:
     Count: 500 | Unique: 1 | Zeros: 0
     Mean: 3.00 | Median: 3.00 | Std: 0.00
     Range: [3.00, 3.00] | Skewness: 0.00

   sys_flags:
     Count: 500 | Unique: 2 | Zeros: 499
     Mean: 0.00 | Median: 0.00 | Std: 0.04
     Range: [0.00, 1.00] | Skewness: 22.36
 Distribution: sys_flags in agency_RW_ORG is highly right-skewed (skewness: 22.36)

### 4.2 Visual Analysis - Distribution and Pattern Visualization

Creating interactive visualizations to understand data distributions and identify patterns.

In [64]:
# Visualization Functions for EDA
def create_distribution_plots(df, dataset_name, numeric_cols, max_plots=6):
    """Create distribution plots for numeric columns"""
    
    if len(numeric_cols) == 0:
        print(f"   No numeric columns to plot for {dataset_name}")
        return None
    
    # Limit number of plots
    cols_to_plot = numeric_cols[:max_plots]
    
    # Calculate subplot layout
    n_plots = len(cols_to_plot)
    n_cols = min(3, n_plots)
    n_rows = (n_plots + n_cols - 1) // n_cols
    
    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[f"{col} Distribution" for col in cols_to_plot],
        vertical_spacing=0.12
    )
    
    for i, col in enumerate(cols_to_plot):
        row = (i // n_cols) + 1
        col_pos = (i % n_cols) + 1
        
        # Clean data for plotting
        data = df[col].dropna()
        
        if len(data) > 0:
            fig.add_trace(
                go.Histogram(
                    x=data,
                    nbinsx=30,
                    name=col,
                    showlegend=False,
                    opacity=0.7
                ),
                row=row, col=col_pos
            )
    
    fig.update_layout(
        height=300 * n_rows,
        title_text=f" Numeric Distributions: {dataset_name}",
        showlegend=False
    )
    
    return fig

def create_category_plots(df, dataset_name, categorical_cols, max_plots=4):
    """Create bar plots for top categorical values"""
    
    if len(categorical_cols) == 0:
        print(f"   No categorical columns to plot for {dataset_name}")
        return None
    
    cols_to_plot = categorical_cols[:max_plots]
    
    # Calculate subplot layout
    n_plots = len(cols_to_plot)
    n_cols = min(2, n_plots)
    n_rows = (n_plots + n_cols - 1) // n_cols
    
    fig = make_subplots(
        rows=n_rows, cols=n_cols,
        subplot_titles=[f"Top {col} Values" for col in cols_to_plot],
        vertical_spacing=0.15
    )
    
    for i, col in enumerate(cols_to_plot):
        row = (i // n_cols) + 1
        col_pos = (i % n_cols) + 1
        
        # Get top 10 values
        top_values = df[col].value_counts().head(10)
        
        if len(top_values) > 0:
            fig.add_trace(
                go.Bar(
                    x=top_values.values,
                    y=top_values.index,
                    orientation='h',
                    name=col,
                    showlegend=False
                ),
                row=row, col=col_pos
            )
    
    fig.update_layout(
        height=400 * n_rows,
        title_text=f" Categorical Distributions: {dataset_name}",
        showlegend=False
    )
    
    return fig

# Generate visualizations for key datasets
if 'eda' in globals():
    print(" CREATING DISTRIBUTION VISUALIZATIONS")
    print("=" * 50)
    
    visualization_results = {}
    
    # Focus on the most important datasets (limit to prevent overwhelming output)
    priority_datasets = list(eda.datasets.keys())[:4]  # First 4 datasets
    
    for dataset_name in priority_datasets:
        df = eda.datasets[dataset_name]
        
        if len(df) > 0:
            print(f"\n Visualizing {dataset_name}...")
            
            # Get column types
            numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
            categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
            
            results = {}
            
            # Create numeric distribution plots
            if len(numeric_cols) > 0:
                print(f"   Creating {len(numeric_cols[:6])} numeric distribution plots...")
                dist_fig = create_distribution_plots(df, dataset_name, numeric_cols)
                if dist_fig:
                    dist_fig.show()
                    
                    # Save plot
                    plot_file = eda.viz_dir / f"{dataset_name}_distributions.html"
                    dist_fig.write_html(plot_file)
                    print(f"     Saved: {plot_file.name}")
                    results['distributions'] = str(plot_file)
            
            # Create categorical plots
            if len(categorical_cols) > 0:
                print(f"   Creating {len(categorical_cols[:4])} categorical plots...")
                cat_fig = create_category_plots(df, dataset_name, categorical_cols)
                if cat_fig:
                    cat_fig.show()
                    
                    # Save plot
                    plot_file = eda.viz_dir / f"{dataset_name}_categories.html"
                    cat_fig.write_html(plot_file)
                    print(f"     Saved: {plot_file.name}")
                    results['categories'] = str(plot_file)
            
            visualization_results[dataset_name] = results
    
    print(f"\n✅ Created visualizations for {len(visualization_results)} datasets")
    print(f" All plots saved to: {eda.viz_dir}")
else:
    print(" EDA toolkit not available - run previous sections first")

 CREATING DISTRIBUTION VISUALIZATIONS
==================================================

 Visualizing choice_DOCUMENTHEADER...
   Creating 2 numeric distribution plots...

     Saved: choice_DOCUMENTHEADER_distributions.html
   Creating 4 categorical plots...

     Saved: choice_DOCUMENTHEADER_categories.html

 Visualizing choice_AMX_DONATION_HEADER...
   Creating 4 categorical plots...

     Saved: choice_AMX_DONATION_HEADER_categories.html

 Visualizing choice_AMX_DONATION_LINES...
   Creating 6 numeric distribution plots...

     Saved: choice_AMX_DONATION_LINES_distributions.html
   Creating 4 categorical plots...

     Saved: choice_AMX_DONATION_LINES_categories.html

 Visualizing choice_RW_ORG...
   Creating 5 numeric distribution plots...

     Saved: choice_RW_ORG_distributions.html
   Creating 4 categorical plots...

     Saved: choice_RW_ORG_categories.html

✅ Created visualizations for 4 datasets
 All plots saved to: notebook_output/visualizations

## 5. Bivariate & Multivariate Analysis

Analyzing relationships between variables to understand dependencies, correlations, and complex patterns in the HungerHub data.

### Analysis Strategy:
1. **Bivariate Analysis**: Relationships between pairs of variables
   - Numeric vs Numeric: Correlation analysis and scatter plots
   - Numeric vs Categorical: Group comparisons and box plots
   - Categorical vs Categorical: Cross-tabulations and chi-square tests

2. **Multivariate Analysis**: Complex relationships across multiple variables
   - Correlation matrices with hierarchical clustering
   - Principal Component Analysis (PCA) for dimensionality reduction
   - Multi-dimensional scatter plots and parallel coordinates

### Key Questions:
- Which variables are strongly correlated?
- How do donations vary by organization type and geography?
- What are the key drivers of food distribution volumes?
- Are there hidden patterns or clusters in the data?

In [65]:
# Advanced Analysis Functions
class HungerHubAdvancedAnalysis:
    """Advanced bivariate and multivariate analysis toolkit"""
    
    def __init__(self, datasets, output_dir):
        self.datasets = datasets
        self.output_dir = Path(output_dir)
        self.viz_dir = self.output_dir / 'visualizations'
        self.viz_dir.mkdir(exist_ok=True)
        
        self.correlations = {}
        self.insights = []
    
    def add_insight(self, category, insight, dataset=None):
        """Add analytical insight"""
        entry = {
            'category': category,
            'insight': insight,
            'dataset': dataset,
            'timestamp': datetime.now().isoformat()
        }
        self.insights.append(entry)
        dataset_info = f" ({dataset})" if dataset else ""
        print(f"Insight - {category}{dataset_info}: {insight}")
    
    def calculate_correlations(self, df, dataset_name, min_correlation=0.3):
        """Calculate and analyze correlations between numeric variables"""
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        
        if len(numeric_cols) < 2:
            print(f"  Insufficient numeric columns ({len(numeric_cols)}) for correlation analysis in {dataset_name}")
            return None
        
        # Calculate correlation matrix
        corr_matrix = df[numeric_cols].corr()
        
        # Find strong correlations
        strong_correlations = []
        for i in range(len(corr_matrix.columns)):
            for j in range(i+1, len(corr_matrix.columns)):
                col1, col2 = corr_matrix.columns[i], corr_matrix.columns[j]
                correlation = corr_matrix.iloc[i, j]
                
                if not np.isnan(correlation) and abs(correlation) >= min_correlation:
                    strong_correlations.append({
                        'var1': col1,
                        'var2': col2,
                        'correlation': correlation,
                        'strength': 'Strong' if abs(correlation) > 0.7 else 'Moderate'
                    })
        
        # Sort by absolute correlation strength
        strong_correlations.sort(key=lambda x: abs(x['correlation']), reverse=True)
        
        print(f"\nCorrelation Analysis: {dataset_name}")
        print("-" * 50)
        print(f"Numeric columns analyzed: {len(numeric_cols)}")
        print(f"Strong correlations found (|r| >= {min_correlation}): {len(strong_correlations)}")
        
        if strong_correlations:
            print("\nTop correlations:")
            for corr in strong_correlations[:10]:  # Show top 10
                print(f"  {corr['var1']} <-> {corr['var2']}: {corr['correlation']:.3f} ({corr['strength']})")
                
                # Generate insights
                if abs(corr['correlation']) > 0.8:
                    self.add_insight('Strong Correlation', 
                                   f"{corr['var1']} and {corr['var2']} are highly correlated (r={corr['correlation']:.3f})",
                                   dataset_name)
        
        self.correlations[dataset_name] = {
            'matrix': corr_matrix,
            'strong_correlations': strong_correlations
        }
        
        return corr_matrix
    
    def analyze_numeric_relationships(self, df, dataset_name, max_pairs=5):
        """Analyze relationships between numeric variables"""
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        
        if len(numeric_cols) < 2:
            return None
        
        # Get top correlated pairs from correlation analysis
        if dataset_name in self.correlations and self.correlations[dataset_name]['strong_correlations']:
            top_pairs = self.correlations[dataset_name]['strong_correlations'][:max_pairs]
            
            print(f"\nNumeric Relationship Analysis: {dataset_name}")
            print("-" * 50)
            
            for pair in top_pairs:
                var1, var2 = pair['var1'], pair['var2']
                correlation = pair['correlation']
                
                # Calculate additional statistics
                valid_data = df[[var1, var2]].dropna()
                if len(valid_data) > 10:  # Need sufficient data points
                    
                    # Linear regression statistics
                    x, y = valid_data[var1], valid_data[var2]
                    if x.std() > 0 and y.std() > 0:  # Avoid division by zero
                        
                        print(f"\n  {var1} vs {var2}:")
                        print(f"    Correlation: {correlation:.3f}")
                        print(f"    Sample size: {len(valid_data)}")
                        print(f"    {var1} range: [{x.min():.2f}, {x.max():.2f}]")
                        print(f"    {var2} range: [{y.min():.2f}, {y.max():.2f}]")
                        
                        # Check for outliers using IQR
                        def count_outliers(series):
                            Q1, Q3 = series.quantile([0.25, 0.75])
                            IQR = Q3 - Q1
                            lower_bound = Q1 - 1.5 * IQR
                            upper_bound = Q3 + 1.5 * IQR
                            return ((series < lower_bound) | (series > upper_bound)).sum()
                        
                        x_outliers = count_outliers(x)
                        y_outliers = count_outliers(y)
                        
                        if x_outliers > 0 or y_outliers > 0:
                            print(f"    Outliers: {x_outliers} in {var1}, {y_outliers} in {var2}")
                            
                            if (x_outliers + y_outliers) / len(valid_data) > 0.1:
                                self.add_insight('Data Quality',
                                               f"{var1} vs {var2} relationship has many outliers ({x_outliers + y_outliers} total)",
                                               dataset_name)
        
        return True
    
    def analyze_categorical_relationships(self, df, dataset_name, max_combinations=3):
        """Analyze relationships between categorical variables"""
        categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
        
        if len(categorical_cols) < 2:
            print(f"  Insufficient categorical columns ({len(categorical_cols)}) for relationship analysis in {dataset_name}")
            return None
        
        print(f"\nCategorical Relationship Analysis: {dataset_name}")
        print("-" * 50)
        
        # Analyze pairs of categorical variables
        combinations_analyzed = 0
        for i in range(len(categorical_cols)):
            for j in range(i+1, len(categorical_cols)):
                if combinations_analyzed >= max_combinations:
                    break
                    
                col1, col2 = categorical_cols[i], categorical_cols[j]
                
                # Filter to reasonable number of categories
                if df[col1].nunique() <= 20 and df[col2].nunique() <= 20:
                    crosstab = pd.crosstab(df[col1], df[col2])
                    
                    print(f"\n  {col1} vs {col2}:")
                    print(f"    {col1} categories: {df[col1].nunique()}")
                    print(f"    {col2} categories: {df[col2].nunique()}")
                    print(f"    Cross-tabulation shape: {crosstab.shape}")
                    
                    # Look for dominant patterns
                    total_combinations = crosstab.sum().sum()
                    max_cell = crosstab.max().max()
                    dominance_ratio = max_cell / total_combinations
                    
                    if dominance_ratio > 0.5:
                        max_idx = crosstab.stack().idxmax()
                        self.add_insight('Pattern',
                                       f"{col1}='{max_idx[0]}' and {col2}='{max_idx[1]}' combination dominates ({dominance_ratio:.1%} of data)",
                                       dataset_name)
                    
                    combinations_analyzed += 1
            
            if combinations_analyzed >= max_combinations:
                break
        
        return True

# Initialize advanced analysis
if 'all_datasets' in globals() and all_datasets:
    advanced_analysis = HungerHubAdvancedAnalysis(all_datasets, notebook_outputs['base'])
    print("✅ Advanced analysis toolkit initialized")
    print(f"Ready for bivariate and multivariate analysis of {len(all_datasets)} datasets")
else:
    print("Advanced analysis requires processed datasets")
    print("Please run previous sections first")

✅ Advanced analysis toolkit initialized
Ready for bivariate and multivariate analysis of 10 datasets

### 5.1 Correlation Analysis

Analyzing correlations between numeric variables to identify strong relationships and dependencies.

In [66]:
# Comprehensive Correlation Analysis
if 'advanced_analysis' in globals():
    print("CORRELATION ANALYSIS")
    print("=" * 50)
    
    correlation_results = {}
    
    # Analyze correlations for each dataset
    for dataset_name, df in advanced_analysis.datasets.items():
        if len(df) > 0:
            print(f"\nAnalyzing correlations in: {dataset_name}")
            
            corr_matrix = advanced_analysis.calculate_correlations(df, dataset_name)
            if corr_matrix is not None:
                correlation_results[dataset_name] = corr_matrix
    
    print(f"\n✅ Correlation analysis completed for {len(correlation_results)} datasets")
else:
    print("❌ Advanced analysis toolkit not available")

CORRELATION ANALYSIS
==================================================

Analyzing correlations in: choice_DOCUMENTHEADER

Correlation Analysis: choice_DOCUMENTHEADER
--------------------------------------------------
Numeric columns analyzed: 2
Strong correlations found (|r| >= 0.3): 0

Analyzing correlations in: choice_AMX_DONATION_HEADER
  Insufficient numeric columns (0) for correlation analysis in choice_AMX_DONATION_HEADER

Analyzing correlations in: choice_AMX_DONATION_LINES

Correlation Analysis: choice_AMX_DONATION_LINES
--------------------------------------------------
Numeric columns analyzed: 6
Strong correlations found (|r| >= 0.3): 4

Top correlations:
  quantity <-> totalpallets: 0.823 (Strong)
Insight - Strong Correlation (choice_AMX_DONATION_LINES): quantity and totalpallets are highly correlated (r=0.823)
  totalpallets <-> totalgrossweight: 0.674 (Moderate)
  quantity <-> totalgrossweight: 0.609 (Moderate)
  grossweight <-> netweight: 0.538 (Moderate)

Analyzing correlations in: choice_RW_ORG

Correlation Analysis: choice_RW_ORG
--------------------------------------------------
Numeric columns analyzed: 5
Strong correlations found (|r| >= 0.3): 0

Analyzing correlations in: agency_DOCUMENTHEADER

Correlation Analysis: agency_DOCUMENTHEADER
--------------------------------------------------
Numeric columns analyzed: 4
Strong correlations found (|r| >= 0.3): 0

Analyzing correlations in: agency_DOCUMENTLINES

Correlation Analysis: agency_DOCUMENTLINES
--------------------------------------------------
Numeric columns analyzed: 3
Strong correlations found (|r| >= 0.3): 1

Top correlations:
  lineitemnumber <-> donatedquantity: 0.319 (Moderate)

Analyzing correlations in: agency_RW_ORG

Correlation Analysis: agency_RW_ORG
--------------------------------------------------
Numeric columns analyzed: 5
Strong correlations found (|r| >= 0.3): 0

Analyzing correlations in: unified_documentheader

Correlation Analysis: unified_documentheader
--------------------------------------------------
Numeric columns analyzed: 2
Strong correlations found (|r| >= 0.3): 0

Analyzing correlations in: unified_donation_header
  Insufficient numeric columns (0) for correlation analysis in unified_donation_header

Analyzing correlations in: unified_rw_org

Correlation Analysis: unified_rw_org
--------------------------------------------------
Numeric columns analyzed: 5
Strong correlations found (|r| >= 0.3): 0

✅ Correlation analysis completed for 8 datasets

### 5.2 Bivariate Relationship Analysis

Detailed analysis of relationships between pairs of variables.

In [67]:
# Bivariate Relationship Analysis
if 'advanced_analysis' in globals():
    print("BIVARIATE RELATIONSHIP ANALYSIS")
    print("=" * 50)
    
    # Analyze numeric relationships
    print("\n1. NUMERIC VARIABLE RELATIONSHIPS:")
    print("=" * 40)
    
    for dataset_name, df in advanced_analysis.datasets.items():
        if len(df) > 0:
            advanced_analysis.analyze_numeric_relationships(df, dataset_name)
    
    # Analyze categorical relationships
    print("\n\n2. CATEGORICAL VARIABLE RELATIONSHIPS:")
    print("=" * 40)
    
    for dataset_name, df in advanced_analysis.datasets.items():
        if len(df) > 0:
            advanced_analysis.analyze_categorical_relationships(df, dataset_name)
    
    print("\n✅ Bivariate analysis completed")
else:
    print("❌ Advanced analysis toolkit not available")

BIVARIATE RELATIONSHIP ANALYSIS
==================================================

1. NUMERIC VARIABLE RELATIONSHIPS:
========================================

Numeric Relationship Analysis: choice_AMX_DONATION_LINES
--------------------------------------------------

  quantity vs totalpallets:
    Correlation: 0.823
    Sample size: 500
    quantity range: [1.00, 6001.00]
    totalpallets range: [0.00, 200.03]
    Outliers: 78 in quantity, 107 in totalpallets
Insight - Data Quality (choice_AMX_DONATION_LINES): quantity vs totalpallets relationship has many outliers (185 total)

  totalpallets vs totalgrossweight:
    Correlation: 0.674
    Sample size: 500
    totalpallets range: [0.00, 200.03]
    totalgrossweight range: [0.05, 60010.00]
    Outliers: 107 in totalpallets, 74 in totalgrossweight
Insight - Data Quality (choice_AMX_DONATION_LINES): totalpallets vs totalgrossweight relationship has many outliers (181 total)

  quantity vs totalgrossweight:
    Correlation: 0.609
    Sample size: 500
    quantity range: [1.00, 6001.00]
    totalgrossweight range: [0.05, 60010.00]

    Outliers: 78 in quantity, 74 in totalgrossweight
Insight - Data Quality (choice_AMX_DONATION_LINES): quantity vs totalgrossweight relationship has many outliers (152 total)

  grossweight vs netweight:
    Correlation: 0.538
    Sample size: 500
    grossweight range: [0.00, 2231.00]
    netweight range: [2.19, 2327.00]
    Outliers: 45 in grossweight, 41 in netweight
Insight - Data Quality (choice_AMX_DONATION_LINES): grossweight vs netweight relationship has many outliers (86 total)

Numeric Relationship Analysis: agency_DOCUMENTLINES
--------------------------------------------------

  lineitemnumber vs donatedquantity:
    Correlation: 0.319
    Sample size: 500
    lineitemnumber range: [1.00, 43.00]
    donatedquantity range: [0.00, 30.00]
    Outliers: 65 in lineitemnumber, 34 in donatedquantity
Insight - Data Quality (agency_DOCUMENTLINES): lineitemnumber vs donatedquantity relationship has many outliers (99 total)


2. CATEGORICAL VARIABLE RELATIONSHIPS:
========================================

Categorical Relationship Analysis: choice_DOCUMENTHEADER
--------------------------------------------------

  userid vs prop3:
    userid categories: 9
    prop3 categories: 3
    Cross-tabulation shape: (9, 3)
Insight - Pattern (choice_DOCUMENTHEADER): userid='Unknown' and prop3='No' combination dominates (55.4% of data)

  userid vs prop4:
    userid categories: 9
    prop4 categories: 14
    Cross-tabulation shape: (9, 14)
Insight - Pattern (choice_DOCUMENTHEADER): userid='Unknown' and prop4='0' combination dominates (53.2% of data)

  userid vs prop8:
    userid categories: 9
    prop8 categories: 5
    Cross-tabulation shape: (9, 5)
Insight - Pattern (choice_DOCUMENTHEADER): userid='Unknown' and prop8='Member will pick up' combination dominates (79.4% of data)

Categorical Relationship Analysis: choice_AMX_DONATION_HEADER
--------------------------------------------------

  shipmentmethod vs stagingmethod:
    shipmentmethod categories: 6
    stagingmethod categories: 8
    Cross-tabulation shape: (6, 8)

  shipmentmethod vs status:
    shipmentmethod categories: 6
    status categories: 8
    Cross-tabulation shape: (6, 8)
Insight - Pattern (choice_AMX_DONATION_HEADER): shipmentmethod='PICKUP' and status='Acknowledged' combination dominates (62.6% of data)

  stagingmethod vs status:
    stagingmethod categories: 8
    status categories: 8
    Cross-tabulation shape: (8, 8)

Categorical Relationship Analysis: choice_AMX_DONATION_LINES
--------------------------------------------------

  donationreason vs size_:
    donationreason categories: 13
    size_ categories: 19
    Cross-tabulation shape: (13, 19)

  donationreason vs sizeuom:
    donationreason categories: 13
    sizeuom categories: 12
    Cross-tabulation shape: (13, 12)

  donationreason vs packagingtype:
    donationreason categories: 13
    packagingtype categories: 10
    Cross-tabulation shape: (13, 10)

Categorical Relationship Analysis: choice_RW_ORG
--------------------------------------------------

  status_flag vs currency:
    status_flag categories: 2
    currency categories: 1
    Cross-tabulation shape: (2, 1)
Insight - Pattern (choice_RW_ORG): status_flag='A' and currency='USD' combination dominates (87.2% of data)

  status_flag vs currency_pattern:
    status_flag categories: 2
    currency_pattern categories: 1
    Cross-tabulation shape: (2, 1)
Insight - Pattern (choice_RW_ORG): status_flag='A' and currency_pattern='*###,##0.00' combination dominates (87.2% of data)

  status_flag vs float_pattern:
    status_flag categories: 2
    float_pattern categories: 1
    Cross-tabulation shape: (2, 1)
Insight - Pattern (choice_RW_ORG): status_flag='A' and float_pattern='###,##0.###' combination dominates (87.2% of data)

Categorical Relationship Analysis: agency_DOCUMENTHEADER
--------------------------------------------------

  domainid vs domainname:
    domainid categories: 2
    domainname categories: 2
    Cross-tabulation shape: (2, 2)
Insight - Pattern (agency_DOCUMENTHEADER): domainid='Unknown' and domainname='Unknown' combination dominates (85.2% of data)

Categorical Relationship Analysis: agency_DOCUMENTLINES
--------------------------------------------------

  prop1 vs prop4:
    prop1 categories: 5
    prop4 categories: 10
    Cross-tabulation shape: (5, 10)

  prop1 vs prop6:
    prop1 categories: 5
    prop6 categories: 6
    Cross-tabulation shape: (5, 6)

  prop1 vs status:
    prop1 categories: 5
    status categories: 3
    Cross-tabulation shape: (5, 3)

Categorical Relationship Analysis: agency_RW_ORG
--------------------------------------------------

  status_flag vs currency:
    status_flag categories: 2
    currency categories: 1
    Cross-tabulation shape: (2, 1)
Insight - Pattern (agency_RW_ORG): status_flag='I' and currency='USD' combination dominates (94.2% of data)

  status_flag vs currency_pattern:
    status_flag categories: 2
    currency_pattern categories: 1
    Cross-tabulation shape: (2, 1)
Insight - Pattern (agency_RW_ORG): status_flag='I' and currency_pattern='*###,##0.00' combination dominates (94.2% of data)

  status_flag vs float_pattern:
    status_flag categories: 2
    float_pattern categories: 2
    Cross-tabulation shape: (2, 2)
Insight - Pattern (agency_RW_ORG): status_flag='I' and float_pattern='###,##0.00' combination dominates (94.2% of data)

Categorical Relationship Analysis: unified_documentheader
--------------------------------------------------

  domainid vs source_database:
    domainid categories: 2
    source_database categories: 2
    Cross-tabulation shape: (2, 2)

  domainid vs domainname:
    domainid categories: 2
    domainname categories: 2
    Cross-tabulation shape: (2, 2)
Insight - Pattern (unified_documentheader): domainid='Unknown' and domainname='Unknown' combination dominates (86.8% of data)

  domainid vs source_table:
    domainid categories: 2
    source_table categories: 2
    Cross-tabulation shape: (2, 2)

Categorical Relationship Analysis: unified_donation_header
--------------------------------------------------

  shipmentmethod vs source_table:
    shipmentmethod categories: 6
    source_table categories: 1
    Cross-tabulation shape: (6, 1)
Insight - Pattern (unified_donation_header): shipmentmethod='PICKUP' and source_table='choice_AMX_DONATION_HEADER' combination dominates (83.8% of data)

  shipmentmethod vs source_database:
    shipmentmethod categories: 6
    source_database categories: 1
    Cross-tabulation shape: (6, 1)
Insight - Pattern (unified_donation_header): shipmentmethod='PICKUP' and source_database='choice' combination dominates (83.8% of data)

  shipmentmethod vs stagingmethod:
    shipmentmethod categories: 6
    stagingmethod categories: 8
    Cross-tabulation shape: (6, 8)

Categorical Relationship Analysis: unified_rw_org
--------------------------------------------------

  annual_rev_vid vs source_table:
    annual_rev_vid categories: 1
    source_table categories: 2
    Cross-tabulation shape: (1, 2)

  annual_rev_vid vs currency_pattern:
    annual_rev_vid categories: 1
    currency_pattern categories: 1
    Cross-tabulation shape: (1, 1)
Insight - Pattern (unified_rw_org): annual_rev_vid='0.0' and currency_pattern='*###,##0.00' combination dominates (100.0% of data)

  annual_rev_vid vs source_database:
    annual_rev_vid categories: 1
    source_database categories: 2
    Cross-tabulation shape: (1, 2)

✅ Bivariate analysis completed

### 5.3 Advanced Visualizations

Creating advanced visualizations to explore multivariate relationships and patterns.

In [68]:
# Advanced Visualization Functions
def create_correlation_heatmap(corr_matrix, dataset_name, min_size=3):
    """Create interactive correlation heatmap"""
    
    if corr_matrix is None or corr_matrix.shape[0] < min_size:
        print(f"  Insufficient data for correlation heatmap in {dataset_name}")
        return None
    
    fig = px.imshow(
        corr_matrix,
        x=corr_matrix.columns,
        y=corr_matrix.columns,
        color_continuous_scale='RdBu_r',
        range_color=[-1, 1],
        title=f"Correlation Matrix: {dataset_name}",
        aspect='auto'
    )
    
    fig.update_layout(
        height=max(400, len(corr_matrix.columns) * 25),
        width=max(400, len(corr_matrix.columns) * 25)
    )
    
    return fig

def create_scatter_matrix(df, dataset_name, numeric_cols, max_vars=5):
    """Create scatter plot matrix for numeric variables"""
    
    if len(numeric_cols) < 2:
        return None
    
    # Limit variables to prevent overwhelming plots
    cols_to_plot = numeric_cols[:max_vars]
    
    # Sample data if too large
    plot_df = df[cols_to_plot].dropna()
    if len(plot_df) > 1000:
        plot_df = plot_df.sample(n=1000, random_state=42)
    
    if len(plot_df) < 10:
        print(f"  Insufficient data points for scatter matrix in {dataset_name}")
        return None
    
    fig = px.scatter_matrix(
        plot_df,
        dimensions=cols_to_plot,
        title=f"Scatter Matrix: {dataset_name} (Top {len(cols_to_plot)} variables)",
        opacity=0.6
    )
    
    fig.update_traces(diagonal_visible=False)
    fig.update_layout(height=600, width=800)
    
    return fig

def create_grouped_analysis(df, dataset_name, numeric_col, categorical_col):
    """Create grouped analysis visualization"""
    
    # Check if columns exist and have reasonable cardinality
    if (numeric_col not in df.columns or categorical_col not in df.columns or
        df[categorical_col].nunique() > 20 or df[categorical_col].nunique() < 2):
        return None
    
    # Clean data
    clean_data = df[[numeric_col, categorical_col]].dropna()
    if len(clean_data) < 20:
        return None
    
    fig = px.box(
        clean_data,
        x=categorical_col,
        y=numeric_col,
        title=f"{numeric_col} by {categorical_col}: {dataset_name}",
        points="outliers"
    )
    
    fig.update_layout(
        height=400,
        xaxis_tickangle=45
    )
    
    return fig

# Generate advanced visualizations
if 'advanced_analysis' in globals() and 'correlation_results' in globals():
    print("ADVANCED VISUALIZATIONS")
    print("=" * 50)
    
    visualization_count = 0
    
    # Create correlation heatmaps
    print("\n1. CORRELATION HEATMAPS:")
    for dataset_name, corr_matrix in correlation_results.items():
        print(f"\nCreating correlation heatmap for {dataset_name}...")
        
        heatmap_fig = create_correlation_heatmap(corr_matrix, dataset_name)
        if heatmap_fig:
            heatmap_fig.show()
            
            # Save plot
            plot_file = advanced_analysis.viz_dir / f"{dataset_name}_correlation_heatmap.html"
            heatmap_fig.write_html(plot_file)
            print(f"  Saved: {plot_file.name}")
            visualization_count += 1
    
    # Create scatter matrices for datasets with sufficient numeric variables
    print("\n2. SCATTER MATRICES:")
    matrices_created = 0
    
    for dataset_name, df in advanced_analysis.datasets.items():
        if matrices_created >= 3:  # Limit to prevent too many plots
            break
            
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if len(numeric_cols) >= 3:
            print(f"\nCreating scatter matrix for {dataset_name}...")
            
            scatter_fig = create_scatter_matrix(df, dataset_name, numeric_cols)
            if scatter_fig:
                scatter_fig.show()
                
                # Save plot
                plot_file = advanced_analysis.viz_dir / f"{dataset_name}_scatter_matrix.html"
                scatter_fig.write_html(plot_file)
                print(f"  Saved: {plot_file.name}")
                visualization_count += 1
                matrices_created += 1
    
    # Create some grouped analysis examples
    print("\n3. GROUPED ANALYSIS EXAMPLES:")
    grouped_created = 0
    
    for dataset_name, df in advanced_analysis.datasets.items():
        if grouped_created >= 2:  # Limit examples
            break
            
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
        
        if len(numeric_cols) > 0 and len(categorical_cols) > 0:
            # Try first numeric and first categorical column
            numeric_col = numeric_cols[0]
            categorical_col = categorical_cols[0]
            
            print(f"\nCreating grouped analysis: {numeric_col} by {categorical_col} in {dataset_name}...")
            
            grouped_fig = create_grouped_analysis(df, dataset_name, numeric_col, categorical_col)
            if grouped_fig:
                grouped_fig.show()
                
                # Save plot
                plot_file = advanced_analysis.viz_dir / f"{dataset_name}_grouped_analysis.html"
                grouped_fig.write_html(plot_file)
                print(f"  Saved: {plot_file.name}")
                visualization_count += 1
                grouped_created += 1
    
    print(f"\n✅ Created {visualization_count} advanced visualizations")
    print(f"All plots saved to: {advanced_analysis.viz_dir}")
else:
    print("❌ Advanced analysis results not available")

ADVANCED VISUALIZATIONS
==================================================

1. CORRELATION HEATMAPS:

Creating correlation heatmap for choice_DOCUMENTHEADER...
  Insufficient data for correlation heatmap in choice_DOCUMENTHEADER

Creating correlation heatmap for choice_AMX_DONATION_LINES...

  Saved: choice_AMX_DONATION_LINES_correlation_heatmap.html

Creating correlation heatmap for choice_RW_ORG...

  Saved: choice_RW_ORG_correlation_heatmap.html

Creating correlation heatmap for agency_DOCUMENTHEADER...

  Saved: agency_DOCUMENTHEADER_correlation_heatmap.html

Creating correlation heatmap for agency_DOCUMENTLINES...

  Saved: agency_DOCUMENTLINES_correlation_heatmap.html

Creating correlation heatmap for agency_RW_ORG...

  Saved: agency_RW_ORG_correlation_heatmap.html

Creating correlation heatmap for unified_documentheader...
  Insufficient data for correlation heatmap in unified_documentheader

Creating correlation heatmap for unified_rw_org...

  Saved: unified_rw_org_correlation_heatmap.html

2. SCATTER MATRICES:

Creating scatter matrix for choice_AMX_DONATION_LINES...

  Saved: choice_AMX_DONATION_LINES_scatter_matrix.html

Creating scatter matrix for choice_RW_ORG...

  Saved: choice_RW_ORG_scatter_matrix.html

Creating scatter matrix for agency_DOCUMENTHEADER...

  Saved: agency_DOCUMENTHEADER_scatter_matrix.html

3. GROUPED ANALYSIS EXAMPLES:

Creating grouped analysis: status by documentid in choice_DOCUMENTHEADER...

Creating grouped analysis: quantity by donationnumber in choice_AMX_DONATION_LINES...

Creating grouped analysis: group_size by org_id in choice_RW_ORG...

Creating grouped analysis: status by documentid in agency_DOCUMENTHEADER...

Creating grouped analysis: lineitemnumber by headerid in agency_DOCUMENTLINES...

Creating grouped analysis: group_size by org_id in agency_RW_ORG...

Creating grouped analysis: notify by domainid in unified_documentheader...

  Saved: unified_documentheader_grouped_analysis.html

Creating grouped analysis: industry_val_num by entity_name in unified_rw_org...

✅ Created 10 advanced visualizations
All plots saved to: notebook_output/visualizations

## 6. Business Intelligence Reports & Conclusions

Synthesizing analytical findings into actionable business intelligence reports and strategic recommendations for HungerHub operations.

### Report Strategy:
1. **Executive Summary**: Key findings and metrics overview
2. **Data Quality Assessment**: Comprehensive data health report
3. **Operational Insights**: Patterns affecting food distribution efficiency
4. **Strategic Recommendations**: Data-driven action items
5. **Technical Documentation**: Analysis methodology and limitations

### Business Questions Answered:
- What is the overall health and quality of HungerHub data?
- Which operational patterns drive the most efficient food distribution?
- What are the key performance indicators for hunger relief operations?
- Where should HungerHub focus improvement efforts?
- What data collection and analysis capabilities should be enhanced?

In [69]:
# Business Intelligence Report Generator
class HungerHubBusinessIntelligence:
    """Business intelligence and reporting toolkit"""
    
    def __init__(self, datasets, eda_results=None, advanced_results=None, output_dir=None):
        self.datasets = datasets
        self.eda_results = eda_results
        self.advanced_results = advanced_results
        self.output_dir = Path(output_dir) if output_dir else Path('notebook_output')
        self.reports_dir = self.output_dir / 'reports'
        self.reports_dir.mkdir(exist_ok=True)
        
        self.report_data = {
            'executive_summary': {},
            'data_quality': {},
            'operational_insights': [],
            'recommendations': [],
            'technical_details': {}
        }
    
    def generate_executive_summary(self):
        """Generate high-level executive summary"""
        print("EXECUTIVE SUMMARY")
        print("=" * 50)
        
        total_datasets = len(self.datasets)
        total_records = sum(len(df) for df in self.datasets.values())
        total_columns = sum(len(df.columns) for df in self.datasets.values())
        
        # Dataset size analysis
        dataset_sizes = [(name, len(df)) for name, df in self.datasets.items()]
        dataset_sizes.sort(key=lambda x: x[1], reverse=True)
        
        # Data type analysis
        numeric_cols = sum(len(df.select_dtypes(include=[np.number]).columns) for df in self.datasets.values())
        categorical_cols = sum(len(df.select_dtypes(include=['object']).columns) for df in self.datasets.values())
        datetime_cols = sum(len(df.select_dtypes(include=['datetime64']).columns) for df in self.datasets.values())
        
        summary = {
            'total_datasets': total_datasets,
            'total_records': total_records,
            'total_columns': total_columns,
            'largest_dataset': dataset_sizes[0] if dataset_sizes else ('None', 0),
            'numeric_columns': numeric_cols,
            'categorical_columns': categorical_cols,
            'datetime_columns': datetime_cols
        }
        
        print(f"\nDATA INVENTORY:")
        print(f"  Total Datasets Analyzed: {summary['total_datasets']}")
        print(f"  Total Records Processed: {summary['total_records']:,}")
        print(f"  Total Data Fields: {summary['total_columns']}")
        print(f"  Largest Dataset: {summary['largest_dataset'][0]} ({summary['largest_dataset'][1]:,} records)")
        
        print(f"\nDATA COMPOSITION:")
        print(f"  Numeric Fields: {summary['numeric_columns']} ({numeric_cols/total_columns*100:.1f}%)")
        print(f"  Categorical Fields: {summary['categorical_columns']} ({categorical_cols/total_columns*100:.1f}%)")
        print(f"  DateTime Fields: {summary['datetime_columns']} ({datetime_cols/total_columns*100:.1f}%)")
        
        print(f"\nTOP 5 DATASETS BY SIZE:")
        for i, (name, size) in enumerate(dataset_sizes[:5], 1):
            print(f"  {i}. {name}: {size:,} records")
        
        self.report_data['executive_summary'] = summary
        return summary
    
    def assess_data_quality(self):
        """Comprehensive data quality assessment"""
        print("\n\nDATA QUALITY ASSESSMENT")
        print("=" * 50)
        
        quality_report = {}
        overall_quality_score = 0
        total_assessments = 0
        
        for dataset_name, df in self.datasets.items():
            if len(df) == 0:
                continue
                
            print(f"\nAssessing: {dataset_name}")
            print("-" * 30)
            
            # Calculate quality metrics
            total_cells = len(df) * len(df.columns)
            missing_cells = df.isnull().sum().sum()
            missing_percentage = (missing_cells / total_cells) * 100 if total_cells > 0 else 0
            
            # Duplicate analysis
            duplicate_rows = len(df) - len(df.drop_duplicates())
            duplicate_percentage = (duplicate_rows / len(df)) * 100 if len(df) > 0 else 0
            
            # Data type consistency
            numeric_cols = df.select_dtypes(include=[np.number]).columns
            consistent_numerics = 0
            for col in numeric_cols:
                if df[col].dtype in ['int64', 'float64']:
                    consistent_numerics += 1
            
            type_consistency = (consistent_numerics / len(numeric_cols)) * 100 if len(numeric_cols) > 0 else 100
            
            # Calculate quality scores (0-100)
            completeness_score = max(0, 100 - missing_percentage)
            uniqueness_score = max(0, 100 - duplicate_percentage)
            consistency_score = type_consistency
            
            overall_score = (completeness_score + uniqueness_score + consistency_score) / 3
            
            quality_metrics = {
                'missing_percentage': missing_percentage,
                'duplicate_percentage': duplicate_percentage,
                'type_consistency': type_consistency,
                'completeness_score': completeness_score,
                'uniqueness_score': uniqueness_score,
                'consistency_score': consistency_score,
                'overall_score': overall_score
            }
            
            quality_report[dataset_name] = quality_metrics
            overall_quality_score += overall_score
            total_assessments += 1
            
            # Display results
            print(f"  Missing Data: {missing_percentage:.1f}% (Score: {completeness_score:.1f}/100)")
            print(f"  Duplicates: {duplicate_percentage:.1f}% (Score: {uniqueness_score:.1f}/100)")
            print(f"  Type Consistency: {type_consistency:.1f}% (Score: {consistency_score:.1f}/100)")
            print(f"  Overall Quality Score: {overall_score:.1f}/100")
            
            # Quality rating
            if overall_score >= 90:
                rating = "Excellent"
            elif overall_score >= 80:
                rating = "Good"
            elif overall_score >= 70:
                rating = "Fair"
            elif overall_score >= 60:
                rating = "Poor"
            else:
                rating = "Critical"
            
            print(f"  Quality Rating: {rating}")
        
        # Overall assessment
        avg_quality_score = overall_quality_score / total_assessments if total_assessments > 0 else 0
        
        print(f"\nOVERALL DATA QUALITY ASSESSMENT:")
        print("-" * 40)
        print(f"Average Quality Score: {avg_quality_score:.1f}/100")
        
        if avg_quality_score >= 85:
            overall_rating = "High Quality - Ready for production analytics"
        elif avg_quality_score >= 75:
            overall_rating = "Good Quality - Minor improvements recommended"
        elif avg_quality_score >= 65:
            overall_rating = "Fair Quality - Data cleaning required"
        else:
            overall_rating = "Low Quality - Significant data work needed"
        
        print(f"Overall Rating: {overall_rating}")
        
        self.report_data['data_quality'] = {
            'individual_scores': quality_report,
            'average_score': avg_quality_score,
            'overall_rating': overall_rating
        }
        
        return quality_report
    
    def generate_operational_insights(self):
        """Generate operational insights from analysis"""
        print("\n\nOPERATIONAL INSIGHTS")
        print("=" * 50)
        
        insights = []
        
        # Analyze dataset patterns
        print("\nDATA PATTERNS ANALYSIS:")
        print("-" * 30)
        
        # Find unified vs individual datasets
        unified_datasets = [name for name in self.datasets.keys() if 'unified' in name.lower()]
        individual_datasets = [name for name in self.datasets.keys() if 'unified' not in name.lower()]
        
        if unified_datasets:
            insight = f"Successfully created {len(unified_datasets)} unified datasets for cross-database analysis"
            insights.append(('Data Integration', insight))
            print(f"  Data Integration: {insight}")
        
        # Analyze data sources
        choice_datasets = [name for name in self.datasets.keys() if 'choice' in name.lower()]
        agency_datasets = [name for name in self.datasets.keys() if 'agency' in name.lower()]
        
        if choice_datasets and agency_datasets:
            insight = f"Multi-source data available: {len(choice_datasets)} Choice datasets, {len(agency_datasets)} Agency datasets"
            insights.append(('Data Coverage', insight))
            print(f"  Data Coverage: {insight}")
        
        # Analyze data volume distribution
        total_records = sum(len(df) for df in self.datasets.values())
        if total_records > 1000:
            insight = f"Substantial data volume ({total_records:,} records) suitable for statistical analysis and trend identification"
            insights.append(('Data Volume', insight))
            print(f"  Data Volume: {insight}")
        
        # Analyze data types for operational capabilities
        has_geographic = any('state' in str(df.columns).lower() or 'city' in str(df.columns).lower() 
                           or 'zip' in str(df.columns).lower() for df in self.datasets.values())
        has_temporal = any(len(df.select_dtypes(include=['datetime64']).columns) > 0 
                          for df in self.datasets.values())
        has_amounts = any('amount' in str(df.columns).lower() or 'quantity' in str(df.columns).lower()
                         or 'weight' in str(df.columns).lower() for df in self.datasets.values())
        
        if has_geographic:
            insight = "Geographic data available - enables location-based analysis and mapping"
            insights.append(('Geographic Analysis', insight))
            print(f"  Geographic Capability: {insight}")
        
        if has_temporal:
            insight = "Temporal data available - enables trend analysis and seasonal pattern identification"
            insights.append(('Temporal Analysis', insight))
            print(f"  Temporal Capability: {insight}")
        
        if has_amounts:
            insight = "Quantitative data available - enables volume and efficiency analysis"
            insights.append(('Quantitative Analysis', insight))
            print(f"  Quantitative Capability: {insight}")
        
        self.report_data['operational_insights'] = insights
        return insights
    
    def generate_recommendations(self):
        """Generate strategic recommendations based on analysis"""
        print("\n\nSTRATEGIC RECOMMENDATIONS")
        print("=" * 50)
        
        recommendations = []
        
        # Data quality recommendations
        if 'data_quality' in self.report_data:
            avg_score = self.report_data['data_quality']['average_score']
            
            print("\nDATA QUALITY IMPROVEMENTS:")
            print("-" * 30)
            
            if avg_score < 80:
                rec = "Implement data validation rules and quality monitoring dashboards"
                recommendations.append(('High Priority', 'Data Quality', rec))
                print(f"  High Priority: {rec}")
            
            if avg_score < 70:
                rec = "Establish data governance policies and regular data cleansing procedures"
                recommendations.append(('Critical', 'Data Governance', rec))
                print(f"  Critical: {rec}")
        
        # Analytics capabilities recommendations
        print("\nANALYTICS CAPABILITIES:")
        print("-" * 30)
        
        total_records = sum(len(df) for df in self.datasets.values())
        if total_records > 5000:
            rec = "Data volume supports advanced analytics - consider implementing machine learning models for predictive insights"
            recommendations.append(('Medium Priority', 'Advanced Analytics', rec))
            print(f"  Advanced Analytics: {rec}")
        
        # Integration recommendations
        unified_count = len([name for name in self.datasets.keys() if 'unified' in name.lower()])
        if unified_count > 0:
            rec = "Unified datasets created successfully - establish automated ETL pipelines for real-time data integration"
            recommendations.append(('Medium Priority', 'Data Integration', rec))
            print(f"  Data Integration: {rec}")
        
        # Visualization and reporting recommendations
        print("\nREPORTING & VISUALIZATION:")
        print("-" * 30)
        
        rec = "Deploy interactive dashboards for real-time operational monitoring"
        recommendations.append(('High Priority', 'Business Intelligence', rec))
        print(f"  Business Intelligence: {rec}")
        
        rec = "Implement automated report generation for key stakeholders"
        recommendations.append(('Medium Priority', 'Automation', rec))
        print(f"  Automation: {rec}")
        
        # Operational recommendations
        print("\nOPERATIONAL EFFICIENCY:")
        print("-" * 30)
        
        rec = "Leverage correlation analysis findings to optimize food distribution logistics"
        recommendations.append(('High Priority', 'Operations', rec))
        print(f"  Operations: {rec}")
        
        rec = "Use geographic and temporal patterns to improve resource allocation"
        recommendations.append(('High Priority', 'Resource Planning', rec))
        print(f"  Resource Planning: {rec}")
        
        self.report_data['recommendations'] = recommendations
        return recommendations

# Initialize Business Intelligence toolkit
if 'all_datasets' in globals() and all_datasets:
    # Collect results from previous analyses if available
    eda_results = eda.insights if 'eda' in globals() else None
    advanced_results = advanced_analysis.insights if 'advanced_analysis' in globals() else None
    
    bi_reporter = HungerHubBusinessIntelligence(
        datasets=all_datasets,
        eda_results=eda_results,
        advanced_results=advanced_results,
        output_dir=notebook_outputs['base']
    )
    
    print("✅ Business Intelligence toolkit initialized")
    print(f"Ready to generate comprehensive reports for {len(all_datasets)} datasets")
else:
    print("❌ Business Intelligence requires processed datasets")
    print("Please run previous sections first")

✅ Business Intelligence toolkit initialized
Ready to generate comprehensive reports for 10 datasets

### 6.1 Executive Summary Report

High-level overview of the data analysis results for executive stakeholders.

In [70]:
# Generate Executive Summary
if 'bi_reporter' in globals():
    executive_summary = bi_reporter.generate_executive_summary()
else:
    print("❌ Business Intelligence toolkit not available")

EXECUTIVE SUMMARY
==================================================

DATA INVENTORY:
  Total Datasets Analyzed: 10
  Total Records Processed: 6,000
  Total Data Fields: 255
  Largest Dataset: unified_documentheader (1,000 records)

DATA COMPOSITION:
  Numeric Fields: 32 (12.5%)
  Categorical Fields: 197 (77.3%)
  DateTime Fields: 26 (10.2%)

TOP 5 DATASETS BY SIZE:
  1. unified_documentheader: 1,000 records
  2. unified_rw_org: 1,000 records
  3. choice_DOCUMENTHEADER: 500 records
  4. choice_AMX_DONATION_HEADER: 500 records
  5. choice_AMX_DONATION_LINES: 500 records

### 6.2 Data Quality Assessment

Comprehensive evaluation of data health and readiness for operational use.

In [71]:
# Generate Data Quality Assessment
if 'bi_reporter' in globals():
    quality_assessment = bi_reporter.assess_data_quality()
else:
    print("❌ Business Intelligence toolkit not available")

DATA QUALITY ASSESSMENT
==================================================

Assessing: choice_DOCUMENTHEADER
------------------------------
  Missing Data: 0.0% (Score: 100.0/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 100.0/100
  Quality Rating: Excellent

Assessing: choice_AMX_DONATION_HEADER
------------------------------
  Missing Data: 0.4% (Score: 99.6/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 99.9/100
  Quality Rating: Excellent

Assessing: choice_AMX_DONATION_LINES
------------------------------
  Missing Data: 5.3% (Score: 94.7/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 98.2/100
  Quality Rating: Excellent

Assessing: choice_RW_ORG
------------------------------
  Missing Data: 3.7% (Score: 96.3/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 98.8/100
  Quality Rating: Excellent

Assessing: agency_DOCUMENTHEADER
------------------------------
  Missing Data: 0.0% (Score: 100.0/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 100.0/100
  Quality Rating: Excellent

Assessing: agency_DOCUMENTLINES
------------------------------
  Missing Data: 0.0% (Score: 100.0/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 100.0/100
  Quality Rating: Excellent

Assessing: agency_RW_ORG
------------------------------
  Missing Data: 3.6% (Score: 96.4/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 98.8/100
  Quality Rating: Excellent

Assessing: unified_documentheader
------------------------------
  Missing Data: 0.0% (Score: 100.0/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 100.0/100
  Quality Rating: Excellent

Assessing: unified_donation_header
------------------------------
  Missing Data: 0.0% (Score: 100.0/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 100.0/100
  Quality Rating: Excellent

Assessing: unified_rw_org
------------------------------
  Missing Data: 0.0% (Score: 100.0/100)
  Duplicates: 0.0% (Score: 100.0/100)
  Type Consistency: 100.0% (Score: 100.0/100)
  Overall Quality Score: 100.0/100
  Quality Rating: Excellent

OVERALL DATA QUALITY ASSESSMENT:
----------------------------------------
Average Quality Score: 99.6/100
Overall Rating: High Quality - Ready for production analytics

### 6.3 Operational Insights & Strategic Recommendations

Actionable insights and recommendations based on comprehensive data analysis.

In [72]:
# Generate Operational Insights and Recommendations
if 'bi_reporter' in globals():
    operational_insights = bi_reporter.generate_operational_insights()
    strategic_recommendations = bi_reporter.generate_recommendations()
else:
    print("❌ Business Intelligence toolkit not available")

OPERATIONAL INSIGHTS
==================================================

DATA PATTERNS ANALYSIS:
------------------------------
  Data Integration: Successfully created 3 unified datasets for cross-database analysis
  Data Coverage: Multi-source data available: 4 Choice datasets, 3 Agency datasets
  Data Volume: Substantial data volume (6,000 records) suitable for statistical analysis and trend identification
  Geographic Capability: Geographic data available - enables location-based analysis and mapping
  Temporal Capability: Temporal data available - enables trend analysis and seasonal pattern identification
  Quantitative Capability: Quantitative data available - enables volume and efficiency analysis


STRATEGIC RECOMMENDATIONS
==================================================

DATA QUALITY IMPROVEMENTS:
------------------------------

ANALYTICS CAPABILITIES:
------------------------------
  Advanced Analytics: Data volume supports advanced analytics - consider implementing machine learning models for predictive insights
  Data Integration: Unified datasets created successfully - establish automated ETL pipelines for real-time data integration

REPORTING & VISUALIZATION:
------------------------------
  Business Intelligence: Deploy interactive dashboards for real-time operational monitoring
  Automation: Implement automated report generation for key stakeholders

OPERATIONAL EFFICIENCY:
------------------------------
  Operations: Leverage correlation analysis findings to optimize food distribution logistics
  Resource Planning: Use geographic and temporal patterns to improve resource allocation

### 6.4 Comprehensive Analysis Summary & Next Steps

Final summary of all analytical findings and recommended next steps.

In [73]:
# Generate Final Analysis Summary
if 'bi_reporter' in globals():
    print("COMPREHENSIVE ANALYSIS SUMMARY")
    print("=" * 50)
    
    # Collect all insights from previous analyses
    all_insights = []
    
    # EDA insights
    if 'eda' in globals() and hasattr(eda, 'insights'):
        all_insights.extend([(insight['category'], insight['insight']) for insight in eda.insights])
    
    # Advanced analysis insights
    if 'advanced_analysis' in globals() and hasattr(advanced_analysis, 'insights'):
        all_insights.extend([(insight['category'], insight['insight']) for insight in advanced_analysis.insights])
    
    # BI insights
    all_insights.extend(bi_reporter.report_data['operational_insights'])
    
    print(f"\nTOTAL INSIGHTS GENERATED: {len(all_insights)}")
    print("\nKEY FINDINGS BY CATEGORY:")
    print("-" * 30)
    
    # Group insights by category
    insights_by_category = {}
    for category, insight in all_insights:
        if category not in insights_by_category:
            insights_by_category[category] = []
        insights_by_category[category].append(insight)
    
    # Display key findings
    for category, insights in insights_by_category.items():
        print(f"\n{category.upper()} ({len(insights)} findings):")
        for i, insight in enumerate(insights[:3], 1):  # Show top 3 per category
            print(f"  {i}. {insight}")
        if len(insights) > 3:
            print(f"     ... and {len(insights)-3} more")
    
    # Analysis completion status
    print("\n\nANALYSIS COMPLETION STATUS:")
    print("=" * 40)
    
    analysis_stages = [
        ('Data Extraction', 'Oracle database connection and data extraction'),
        ('ETL Pipeline', 'Data cleaning, transformation, and standardization'),
        ('Univariate Analysis', 'Individual variable analysis and distributions'),
        ('Bivariate Analysis', 'Correlation and relationship analysis'),
        ('Advanced Visualizations', 'Interactive charts and plots'),
        ('Business Intelligence', 'Executive reports and recommendations')
    ]
    
    for stage, description in analysis_stages:
        print(f"  ✅ {stage}: {description}")
    
    # Next steps
    print("\n\nRECOMMENDED NEXT STEPS:")
    print("=" * 30)
    
    next_steps = [
        "Deploy findings in production dashboard environment",
        "Implement automated data pipelines based on ETL framework",
        "Establish regular data quality monitoring",
        "Develop predictive models using correlation insights",
        "Create stakeholder-specific reporting dashboards",
        "Schedule regular analysis updates and reviews"
    ]
    
    for i, step in enumerate(next_steps, 1):
        print(f"  {i}. {step}")
    
    # Save comprehensive report
    final_report = {
        'analysis_date': datetime.now().isoformat(),
        'executive_summary': bi_reporter.report_data['executive_summary'],
        'data_quality': bi_reporter.report_data['data_quality'],
        'operational_insights': bi_reporter.report_data['operational_insights'],
        'recommendations': bi_reporter.report_data['recommendations'],
        'all_insights': all_insights,
        'analysis_stages_completed': [stage for stage, _ in analysis_stages],
        'next_steps': next_steps
    }
    
    report_file = bi_reporter.reports_dir / 'hungerhub_comprehensive_analysis_report.json'
    with open(report_file, 'w') as f:
        json.dump(final_report, f, indent=2, default=str)
    
    print(f"\n✅ ANALYSIS COMPLETE")
    print(f"Comprehensive report saved: {report_file}")
    print(f"All visualizations saved to: {bi_reporter.output_dir / 'visualizations'}")
    print(f"All processed data saved to: {bi_reporter.output_dir / 'csv'} and {bi_reporter.output_dir / 'parquet'}")
    
    print("\nTHANK YOU FOR USING THE HUNGERHUB COMPREHENSIVE ANALYSIS NOTEBOOK!")
    print("This analysis provides a complete Oracle-to-Graphics workflow for data-driven")
    print("decision making in hunger relief operations.")

else:
    print("❌ Cannot generate final summary - Business Intelligence toolkit not available")

COMPREHENSIVE ANALYSIS SUMMARY
==================================================

TOTAL INSIGHTS GENERATED: 120

KEY FINDINGS BY CATEGORY:
------------------------------

DISTRIBUTION (20 findings):
  1. status in choice_DOCUMENTHEADER is highly right-skewed (skewness: 7.58)
  2. notify in choice_DOCUMENTHEADER is highly right-skewed (skewness: 8.62)
  3. quantity in choice_AMX_DONATION_LINES is highly right-skewed (skewness: 10.01)
     ... and 17 more

DATA QUALITY (20 findings):
  1. documentid in choice_DOCUMENTHEADER has very high uniqueness (100.0%) - possibly an identifier
  2. refnumber in choice_DOCUMENTHEADER has very high uniqueness (100.0%) - possibly an identifier
  3. donationnumber in choice_AMX_DONATION_HEADER has very high uniqueness (100.0%) - possibly an identifier
     ... and 17 more

DATA PATTERN (43 findings):
  1. userid in choice_DOCUMENTHEADER is dominated by 'Unknown' (88.0% of records)
  2. dcontactfax in choice_AMX_DONATION_HEADER is dominated by 'Unknown' (88.2% of records)
  3. sys_flags in choice_RW_ORG has 99.8% zero values
     ... and 40 more

TEMPORAL COVERAGE (15 findings):
  1. donationdate in choice_AMX_DONATION_HEADER spans 3090 days - good for trend analysis
  2. releasedate in choice_AMX_DONATION_HEADER spans 8198 days - good for trend analysis
  3. outbydate in choice_AMX_DONATION_HEADER spans 8243 days - good for trend analysis
     ... and 12 more

STRONG CORRELATION (1 findings):
  1. quantity and totalpallets are highly correlated (r=0.823)

PATTERN (15 findings):
  1. userid='Unknown' and prop3='No' combination dominates (55.4% of data)
  2. userid='Unknown' and prop4='0' combination dominates (53.2% of data)
  3. userid='Unknown' and prop8='Member will pick up' combination dominates (79.4% of data)
     ... and 12 more

DATA INTEGRATION (1 findings):
  1. Successfully created 3 unified datasets for cross-database analysis

DATA COVERAGE (1 findings):
  1. Multi-source data available: 4 Choice datasets, 3 Agency datasets

DATA VOLUME (1 findings):
  1. Substantial data volume (6,000 records) suitable for statistical analysis and trend identification

GEOGRAPHIC ANALYSIS (1 findings):
  1. Geographic data available - enables location-based analysis and mapping

TEMPORAL ANALYSIS (1 findings):
  1. Temporal data available - enables trend analysis and seasonal pattern identification

QUANTITATIVE ANALYSIS (1 findings):
  1. Quantitative data available - enables volume and efficiency analysis


ANALYSIS COMPLETION STATUS:
========================================
  ✅ Data Extraction: Oracle database connection and data extraction
  ✅ ETL Pipeline: Data cleaning, transformation, and standardization
  ✅ Univariate Analysis: Individual variable analysis and distributions
  ✅ Bivariate Analysis: Correlation and relationship analysis
  ✅ Advanced Visualizations: Interactive charts and plots
  ✅ Business Intelligence: Executive reports and recommendations


RECOMMENDED NEXT STEPS:
==============================
  1. Deploy findings in production dashboard environment
  2. Implement automated data pipelines based on ETL framework
  3. Establish regular data quality monitoring
  4. Develop predictive models using correlation insights
  5. Create stakeholder-specific reporting dashboards
  6. Schedule regular analysis updates and reviews

✅ ANALYSIS COMPLETE
Comprehensive report saved: notebook_output/reports/hungerhub_comprehensive_analysis_report.json
All visualizations saved to: notebook_output/visualizations
All processed data saved to: notebook_output/csv and notebook_output/parquet

THANK YOU FOR USING THE HUNGERHUB COMPREHENSIVE ANALYSIS NOTEBOOK!
This analysis provides a complete Oracle-to-Graphics workflow for data-driven
decision making in hunger relief operations.

In [74]:
# Analysis execution timer - END
analysis_end_time = datetime.now()
elapsed_time = analysis_end_time - analysis_start_time

# Format elapsed time as H:M:S
hours, remainder = divmod(elapsed_time.total_seconds(), 3600)
minutes, seconds = divmod(remainder, 60)

print("\n" + "=" * 60)
print("ANALYSIS EXECUTION COMPLETED")
print("=" * 60)
print(f"Start time: {analysis_start_time.strftime('%Y-%m-%d %H:%M:%S')}")
print(f"End time: {analysis_end_time.strftime('%Y-%m-%d %H:%M:%S')}")
print(f"Elapsed time: {int(hours):02d}:{int(minutes):02d}:{int(seconds):02d}")
print(f"Notebook type: SAMPLE DATA ANALYSIS")
print("\nSample-based analysis completed successfully!")
print("For production analysis with complete data, use: hungerhub_full_data_analysis.ipynb")

============================================================
ANALYSIS EXECUTION COMPLETED
============================================================
Start time: 2025-08-09 16:56:17
End time: 2025-08-09 16:56:36
Elapsed time: 00:00:19
Notebook type: SAMPLE DATA ANALYSIS

Sample-based analysis completed successfully!
For production analysis with complete data, use: hungerhub_full_data_analysis.ipynb